kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/ibm-datastax-hcd/cass-operator:v1.28.1@sha256:8facbeba19eea4ce7ae3947fdd71d9049dd661b4cd669a8b60ad5d15ae4cec35
  - name: cp.icr.io/cp/cpd/ibm-datastax-hcd/cassandra-reaper:4.1.1-ubi@sha256:fce8442e1efa0b4799af817557bb9a222398eb0ae1f73662d5ea12827f6f790b
  - name: cp.icr.io/cp/cpd/ibm-datastax-hcd/cql-router:0c3ce625@sha256:ba4970152f8a18c98d9ffc7096cf6446b6f849fa2814006129493e5d894f9df4
  - name: cp.icr.io/cp/cpd/ibm-datastax-hcd/cqlsh-pod:6a037ab6-1.16-latest@sha256:c3658d88b141afa52cf654374f6b92fb3425e2d3561b4c1e2dae73341eeccf4d
  - name: cp.icr.io/cp/cpd/ibm-datastax-hcd/data-api:v1.0.35@sha256:82fb23859d9d973705252ee15bf79df2b7c021bb23f07dd4cbb0518aca76079f
  - name: cp.icr.io/cp/cpd/ibm-datastax-hcd/hcd:1.2.5-ubi@sha256:b0ffc75a4ba317f45b63d02c8e40f3d1445aabe2918f799768b1831a60a65cc8
  - name: cp.icr.io/cp/cpd/ibm-datastax-hcd/k8ssandra-client:v0.8.7@sha256:4d32f59a80d4d0e0dfbe68eb4e802a9c7bcf11fb9d8e17df366659c167d84c29
  - name: cp.icr.io/cp/cpd/ibm-datastax-hcd/k8ssandra-operator:v1.29.1@sha256:14275a152b7379be95da3bc7d9238b04d4155aaead0182e942b413f5a411dfb0
  - name: cp.icr.io/cp/cpd/ibm-datastax-hcd/mission-control-dex:6a037ab6-1.16-latest@sha256:a8b29d350ffe80a4d167634eea8e03bb2c1deb0c87e0ddc2b06e364667ca9ac0
  - name: cp.icr.io/cp/cpd/ibm-datastax-hcd/mission-control-ui:6a037ab6-1.16-embedded-latest@sha256:c9848827cf0161d41a40796f01c6141f6e5cb0319fdc033ceb79afaf68bb0964
  - name: cp.icr.io/cp/cpd/ibm-datastax-hcd/mission-control:6a037ab6-1.16-latest@sha256:eca6fb010fd74adb28db20ef7d14a97645465ec7acc3635db66a6cad0c10d324
  - name: cp.icr.io/cp/cpd/ibm-datastax-hcd/system-logger:v1.28.1@sha256:eca61da238391254c375d6bd7d97f692c3fb3cec7b16df28af2639a6b439c951
