kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cp4a/odm/dbserver:9.5.0.1-IF004@sha256:63016ebaffd5b52c05d6e73fc0b6c74cfe6627e8294cc94eade914e5655a61c3
  - name: cp.icr.io/cp/cp4a/odm/odm-decisioncenter:9.5.0.1-IF004@sha256:db63723951100e95ef9f6bef9755db67c219a428b0c02d1f297a306bc296093b
  - name: cp.icr.io/cp/cp4a/odm/odm-decisionrunner:9.5.0.1-IF004@sha256:bcf87df66fcf6cf57738fa818771396f6a378e87c0c33b9b79e636a08991d407
  - name: cp.icr.io/cp/cp4a/odm/odm-decisionserverconsole:9.5.0.1-IF004@sha256:b9cef8a4d3c7dbb892ae28ff34c070bf293a1bdfc266164b68a4f4b8f9e3967b
  - name: cp.icr.io/cp/cp4a/odm/odm-decisionserverruntime:9.5.0.1-IF004@sha256:4374dbed6e426f43d60ff92f5b8c3d067376a310384d55f6f470948ce7589ce7
