kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-cdws/cdws:6.4.0.6_iFix00-2026-02-06@sha256:4984b8dbd121c960ef0c44024aa7999fd4df36e8a0589509728ce117859d544b
