kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-scc/ibmscc:6.4.0.0.iFix02_2026-02-04@sha256:80c9ded09da481622f0f6a2688106f6526fdeff6eeac5b455e091a0af479d866
  - name: cp.icr.io/cp/ibm-scc/ibmscc_resources:dbdrivers@sha256:995b4efff9a9002baccab2034ce18ac8e7a39ecef4b3000b0541dba92685737f
