kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/dp-api:1.0.2654@sha256:8c1537342f81157f57aa9d65d5ece7ced2a0b49dc3fe5a691a91cc79fce18be7
  - name: cp.icr.io/cp/cpd/dp-privacyprocessor:1.0.2593@sha256:8dc1c1f143d48bdc26b122924d8873cdbd3895c3315762951964ccc24b80427f
  - name: cp.icr.io/cp/cpd/dp-subset:1.0.2635@sha256:41b20d07fb421f47bf77f6fcc20dae9c66e53450e70c844377c16467c6a02392
  - name: cp.icr.io/cp/cpd/dp-ui:1.0.2745@sha256:c4ce97fe1a3d979e1bd0b6dd755e0c66b38745acaa28bc22cbe6c2c756a727eb
  - name: cp.icr.io/cp/cpd/spark-hb-control-plane:5.3.00787@sha256:f7cda81cb2315647eecbe7e12477b0b71f956415d9b777238f418230b2355707
  - name: cp.icr.io/cp/cpd/spark-hb-cpd-miniconda-runtimes:3.4.4-v1327-5.3.0@sha256:ccce2ef6bbe3395843685d65bdf885c9619de309fceef77e9f77cb9e251d05a4
  - name: cp.icr.io/cp/cpd/spark-hb-cpd-miniconda-runtimes:3.5.4-v1327-5.3.0@sha256:ee023a9b703cc3a441c4299e4991597a86a3bdc28022979878ffc29150f35052
  - name: cp.icr.io/cp/cpd/spark-hb-cpd-miniconda-runtimes:4.0.0-v1327-5.3.0@sha256:e0c0b9c1faf5c287d3f8fd49ab7bac8dc43e4d58312233031c3beedf4227283b
  - name: cp.icr.io/cp/cpd/spark-hb-cpd-miniforge-runtimes:3.4.4-v1327-5.3.0@sha256:6219bae453a01059fc88a3f3fc4cf0382cc7dda6e11d1defd0e91bce0e9b29e5
  - name: cp.icr.io/cp/cpd/spark-hb-cpd-miniforge-runtimes:3.5.4-v1327-5.3.0@sha256:e185a5d3552af2c9e808694f0ad59cbb742ba6a5542ada2e309723502d3eaac1
  - name: cp.icr.io/cp/cpd/spark-hb-cpd-miniforge-runtimes:4.0.0-v1327-5.3.0@sha256:fe4024c72f7916abd29b71cb3dcc5dfb55c6a3b1be2004e604e4e5346932185a
  - name: cp.icr.io/cp/cpd/spark-hb-deployer-agent:5.3.00787@sha256:1deabc4e73da23ffd0bd9d3937779e6feed1d0e3d3c9c5c33a5a989e1dead729
  - name: cp.icr.io/cp/cpd/spark-hb-helm-repo:5.3.00787@sha256:6fe97b4fc334a90c07b8822f09dd09f908326fcc749b5ca71daa44907e3c5efb
  - name: cp.icr.io/cp/cpd/spark-hb-instance-operator:5.3.00787@sha256:789dfc97c4538227fee3970a47ea264c85648d0de35ec41098c9f6bc5165bc3e
  - name: cp.icr.io/cp/cpd/spark-hb-nginx:5.3.00787@sha256:9c277c409e7d925ed9eba4b1890950f36ee3b5d81e5705c4303631000b10bea9
  - name: cp.icr.io/cp/cpd/spark-hb-python:5.3.00787@sha256:a1cf7213f2f751e4ed0d99a3b8e0210978aeda8ee376dd40f9fe0ed6b239c8e9
  - name: cp.icr.io/cp/cpd/spark-hb-rsyslog-sidecar:5.3.00787@sha256:5ce279d6dbf196b48aaf3765aa46dac895f5621d97d0000ea962ae9c7bc627f2
  - name: cp.icr.io/cp/cpd/spark-hb-truststore-util:5.3.00787@sha256:c1f8bc43519ecc2a4f07d092bac6882aae5ae7297ea533fc24407f8a449ff74b
  - name: cp.icr.io/cp/cpd/spark-hb-ui:5.3.00787@sha256:72b4ef71957cdc9b79982d36ec7bd78bdc2f0b8e7d21e21eb695373c9ab811bf
  - name: cp.icr.io/cp/cpd/spark-hb-wxd-cpd-miniforge-runtimes:3.4.4-v1327-5.3.0@sha256:0a8a88eb9152a74f98940c1f45e9e1fe62519b37f1e82c0596e134f783701252
  - name: cp.icr.io/cp/cpd/spark-hb-wxd-cpd-miniforge-runtimes:3.5.4-v1327-5.3.0@sha256:fae1b3e2416ad11d26c8801325cd97a3610bcb1c9e6a89534f41eccb25af4a8d
  - name: cp.icr.io/cp/cpd/spark-hb-wxd-cpd-miniforge-runtimes:4.0.0-v1327-5.3.0@sha256:43cdd4dfcab3857db60d0e3d4cd1abf0a99394c230e5779f8d2cc71437906205
  - name: icr.io/cpopen/ibm-cpd-analyticsengine-dataplane-operator:5.3.1295-amd64@sha256:65ba782ec63d4de56e0af4bd46d4f154c062cf6a7091ea9bb18af3e331799375
  - name: icr.io/cpopen/ibm-cpd-analyticsengine-operator-bundle:5.3.1295@sha256:c40c1da98c035f271836433a6433c96620cb01ded5bd5e27e8b1dcefd3c67ec4
  - name: icr.io/cpopen/ibm-cpd-analyticsengine-operator-catalog:5.3.1295@sha256:81316d91d33a40f0dd7ede2b477fb54d2c8220abc88fe4626e860ddd75f371b0
  - name: icr.io/cpopen/ibm-cpd-analyticsengine-operator:5.3.1295@sha256:bc3dd42c5d35cc97bb1eaa51f3765aecb23f6ef8d09d8e7a66ec5a38fab5fb75
  - name: icr.io/cpopen/ibm-cpd-dp-operator-bundle:v11.1.2756@sha256:9ebfdd35bb4d99a00cbb00cd23287f7dbb35ca5d306063100f801d33d1a3a50b
  - name: icr.io/cpopen/ibm-cpd-dp-operator-catalog:v11.1.2756@sha256:b605828407e6d24710b0e171c0fb78b40dc52a6ca1bbd5c0ba654d74791b1d58
  - name: icr.io/cpopen/ibm-cpd-dp-operator:v11.1.2756@sha256:83d1e52954086e0494f0ef59507bd40695d90ca80f33f9cd35db882fc3b8241b
