kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/manage/bdi:8.3.15@sha256:1aba8d6c6888c597b4d1650afafb74921679551c2353ec5b97f2d723324bfa3e
  - name: cp.icr.io/cp/manage/extension-acm:8.1.29@sha256:7f912a7bd2c5cb769bba06416da359ba87b4d724561d307ef3cb912cfc69faae
  - name: cp.icr.io/cp/manage/extension-aviation:8.1.34@sha256:42be871f8c21ef4033669f491d217cfa4c354210761fd044e205d8a61f879a9d
  - name: cp.icr.io/cp/manage/extension-civil:8.6.26@sha256:9f1029075a337c4923d95825940e9264a17ed6ead4ee376c4e1f9c4fdff9c39c
  - name: cp.icr.io/cp/manage/extension-envizi:8.1.0@sha256:eed9671e993c7550b6e57796fdb44f0ceb5f98cd3e7289652116269fd4c4376e
  - name: cp.icr.io/cp/manage/extension-health:8.9.26@sha256:be06d589e0ac33a30279fef4a10011652c122145082843599efe5516f15bfc46
  - name: cp.icr.io/cp/manage/extension-hse:8.1.17@sha256:e20a240e646423f3ad94563f619df9b2e731572364c9a2acd63882346b08af5a
  - name: cp.icr.io/cp/manage/extension-icd:8.1.15@sha256:39061e5a036f69f23cb140242ef18727ba124760448da1a0aee6a1de609011f3
  - name: cp.icr.io/cp/manage/extension-nuclear:8.1.10@sha256:373ec2becc3bb6d4f6eefbd336c20f021cade50a747e520a1e9d94cf106a5af4
  - name: cp.icr.io/cp/manage/extension-oilandgas:8.1.17@sha256:370e44f734567be7c1ef9fb5dd3469cc817dbbc919293b257e76e10baee4370b
  - name: cp.icr.io/cp/manage/extension-oracleadapter:8.2.0@sha256:d8f3a47ca74207bcef561176fe8f0a6ab05b477aa2e43e432c72c6bda1391234
  - name: cp.icr.io/cp/manage/extension-sapadapter:8.2.0@sha256:eb83c9e0e155d1c6bee8bb63ac3c1581c076dbaec7ec3513ab23ccaae097645c
  - name: cp.icr.io/cp/manage/extension-serviceprovider:8.1.18@sha256:881399f54b28abb8969c0d337a35ea498323e20c777ea5e9bccc01fd7801ce4f
  - name: cp.icr.io/cp/manage/extension-spatial:8.7.23@sha256:8935174280603bf289f9a03b93e71e32260e123fabf05ddcda715a78cc14c049
  - name: cp.icr.io/cp/manage/extension-strategize:8.0.0@sha256:9544f55a6f7c8e3a4aaeae39e9454c3885bce84378ba88e97555a5f9bb66bff5
  - name: cp.icr.io/cp/manage/extension-transportation:8.1.22@sha256:d5fb22efae95f44893b9ca3a299928e0a9a58d92dc94e1494430e5f99622c557
  - name: cp.icr.io/cp/manage/extension-tririga:8.1.1@sha256:b1c0d58b99ac3837f5071c2e22d95f9f150b4b024580cbdc2c25274ace0ec32a
  - name: cp.icr.io/cp/manage/extension-utilities:8.1.20@sha256:a421064b585b92875a8c03ed3c87ecc8b409473d84282d84230a469a97fc8199
  - name: cp.icr.io/cp/manage/extension-workday:8.1.0@sha256:fef64cccc1e544072c7440c7ab9c60fc7b4208df606c120e4d6901a33cb408d3
  - name: cp.icr.io/cp/manage/health-aio:8.9.26@sha256:19cc92854ca159470a383a5776bb7ebeae55517afa596f4c8e6b8877c1ec4bd9
  - name: cp.icr.io/cp/manage/healthext-model-engine:1.0.18@sha256:17f928e604a5d53dfd6cd12a2560aa590daa8050fee283f6db2b0a975862846f
  - name: cp.icr.io/cp/manage/ibm-mas-healthext-ws:1.0.27@sha256:6ffe30e8d273076cdaab21cf353dc65b13972aa1ae99755da676e259a3ed937c
  - name: cp.icr.io/cp/manage/ibm-mas-imagestitching:1.0.11@sha256:16f2a44a2f9b9adfad76e3bcccf08c9511930e17e0bdfedca5953e0d0b9cf34a
  - name: cp.icr.io/cp/manage/ibm-mas-manage-appstatus:8.7.30@sha256:5a3d883fb919e9d1d421b206714d9996b312f4ec5109d98cb1226fd08b653085
  - name: cp.icr.io/cp/manage/ibm-mas-manage-bdi:8.7.30@sha256:574311b74b9d5a25161128a49998c34283eb8721576b9ded0f6d280754f82e36
  - name: cp.icr.io/cp/manage/ibm-mas-manage-primary-entity:8.7.30@sha256:5954bb65049bfc2bc38b76150fea16f581117c3547a2e27d89be80716990a331
  - name: cp.icr.io/cp/manage/ibm-mas-manage-ws:8.7.30@sha256:c508459a8d10d6309d79c0302aafda92485081671bfe3d2f22ca7fc755f5ec50
  - name: cp.icr.io/cp/manage/image-stitching:1.1.41-amd64@sha256:132ce88dff671beca7add6b0041ffc8d841d94b566a04ef54fd47262b44f83d4
  - name: cp.icr.io/cp/manage/maf-tools:8.10.6@sha256:c1dbc2f9572942f6a625259582bafee093ed8b9a377540b78db7a6dcd60bff49
  - name: cp.icr.io/cp/manage/manage-groupsyncagent:1.2.47@sha256:c3055919382f19439ebec05d8974e6926f21eb373b7d2278b47bb5384d5fd253
  - name: cp.icr.io/cp/manage/manage-usersyncagent:2.3.38@sha256:193694161ddb1053db2c776f24977ce8e1b2d801e76e0fb49c742ffd1146f92c
  - name: cp.icr.io/cp/manage/manageadmin:8.7.29@sha256:64f96c2461ecbe00d4671d8f1b562810d2383edc6c5981ab3ab84057afe1c430
  - name: cp.icr.io/cp/manage/maxloader:9.0.12-amd64@sha256:1d89bc2195809b02342418ca7fae5d762c144c1a9f59ddc66c691d4395e39110
  - name: cp.icr.io/cp/manage/monitoragent:4.1.34@sha256:e63eaaca47b63fe675d8a42772f5abe265c3cf0435284fb1a7c499e8520550ff
  - name: cp.icr.io/cp/manage/ubi-wlp-jms-manage:2.2.13@sha256:30e5f08695500c28827766477e99eab39110bfa00d85b8925927879edbe9923b
  - name: cp.icr.io/cp/manage/ubi-wlp-manage:3.2.25@sha256:efffea56027bf8c61213e18a609435cc8e3e51b6451c98ee14a206b6795d0555
  - name: icr.io/cpopen/ibm-mas-manage-operator-bundle:8.7.30@sha256:6a68a767186c12ab06a69482049ef0614aca41432077f63f93e71fa6a7c8f670
  - name: icr.io/cpopen/ibm-mas-manage-webhook:8.7.30@sha256:e046be34008536b0ebc7969df3bc820a0f290528d9419383e50c437277d14312
  - name: icr.io/cpopen/ibm-mas-manage:8.7.30@sha256:b7e539605e207c7b4d11a164e09a98ffa33569e0bb01609a30663b0ab1c3a096
