kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/wslocal-init-241-py:12.1.023.01895@sha256:74a64093f4e9cf12513a8323d7ae824f0cd828bb4b89a369c9609db8eb8eff35
  - name: cp.icr.io/cp/cpd/wslocal-init-241-pygpu:12.1.023.01895@sha256:0d7d53cb8d2a8302aaee5c95342d0e01fee20ef7cee9c154594de7000fb1bdaa
  - name: cp.icr.io/cp/cpd/wslocal-init-241-r:12.1.023.01895@sha256:42962df6ace8be0e5d01e5a8a0b155c2e80408e60071775535926e47a0f928dd
  - name: cp.icr.io/cp/cpd/wslocal-init-251-py-restricted:12.1.023.01895@sha256:320e1a870b15f537daa9a254df845523a56b34d67831408ef56d2c48f83ec148
  - name: cp.icr.io/cp/cpd/wslocal-init-251-py:12.1.023.01895@sha256:21c8391529da6204268c977491bcc89a042d0f5e8b3244e086b0984080cd28f5
  - name: cp.icr.io/cp/cpd/wslocal-init-251-pygpu-restricted:12.1.023.01895@sha256:7b30cc8f0d9488b74d86eb80ed4baaebc0f24e9f94a0c8b15d333188283aae64
  - name: cp.icr.io/cp/cpd/wslocal-init-251-pygpu:12.1.023.01895@sha256:c09c52582092ff7fdc7e43de8c2d955ab5902451c6c92e1f5fcd72689e3cedf0
  - name: cp.icr.io/cp/cpd/wslocal-init-251-r-restricted:12.1.023.01895@sha256:821576664a9718bd40178355b400cd27c9b8a60eaaedf3e1e7ef9eed4da7bc60
  - name: cp.icr.io/cp/cpd/wslocal-init-251-r:12.1.023.01895@sha256:7a240362145f0b4a222d28d503ba32f0eba5fd1dec2e01155fab677ce24bece0
  - name: cp.icr.io/cp/cpd/wslocal-init-251a-restricted:12.1.023.01895@sha256:77083f1970e0411e4de6245c42819abd59a8f2b0c02a701c221eff14dee69e24
  - name: cp.icr.io/cp/cpd/wslocal-init-251a:12.1.023.01895@sha256:946514b4faaad5cd801e78333e936b21567ccd2b7ef780b49c26b4cc5a28e52d
  - name: cp.icr.io/cp/cpd/wslocal-init-nlp24.1:5.5.1.2@sha256:39551ec2f6ef751887e110257c8dff9a97c7ac506fbfeed5a16242669c945218
  - name: cp.icr.io/cp/cpd/wslocal-init-nlp25.1:5.10.2.1@sha256:0bdbff8a9017e0ee948c147d0363daea4a28f42af30bb68b543caa449b288648
  - name: cp.icr.io/cp/cpd/wslocal-runtime-241-py:12.1.023.01912@sha256:d2e6665fe206b272028220e514570efd8ceb17b737f97ceab6c90035a0b0e12c
  - name: cp.icr.io/cp/cpd/wslocal-runtime-241-pygpu:12.1.023.01912@sha256:b6351058b9075f5cdd8718cb9ba9699a5be7cb96414aa0efb713427ff611c2d8
  - name: cp.icr.io/cp/cpd/wslocal-runtime-241-r:12.1.023.01912@sha256:7141563dc2e7f0532570879ab5a134cfb8dd6782a550d0fa08794afa5355354d
  - name: cp.icr.io/cp/cpd/wslocal-runtime-251-py-restricted:12.1.023.01919@sha256:2e8145dc96ac1dabf52454ac80b7662510f066c76fc023d01b6e94d560069b22
  - name: cp.icr.io/cp/cpd/wslocal-runtime-251-py:12.1.023.01919@sha256:b31c8b2f8286c6cbd9552b4005bbfc53068b6a0c5bc5bdb8ceadbc2b52cc8ade
  - name: cp.icr.io/cp/cpd/wslocal-runtime-251-pygpu-restricted:12.1.023.01919@sha256:28123d89e7f1473dc0b87247e9d54200865bab7cc3605f0d59d7a0c2d6a071dc
  - name: cp.icr.io/cp/cpd/wslocal-runtime-251-pygpu:12.1.023.01919@sha256:80f8f60af262b4d5aa0224fe1da8fa2953eb226d1133a2fac0887eecadea79cc
  - name: cp.icr.io/cp/cpd/wslocal-runtime-251-r-restricted:12.1.023.01919@sha256:bcc8bc4d808f939ef896762bfd6a76a5eb69f4e428b479f84c5decfb79f5822d
  - name: cp.icr.io/cp/cpd/wslocal-runtime-251-r:12.1.023.01919@sha256:43513727e889bd80171607845c7fdea863ab8827900866f1f97041980380c2d8
  - name: cp.icr.io/cp/cpd/wslocal-runtime-251a-restricted:12.1.023.01919@sha256:269b8f7971a720a6cbe976c1a8c222d1c92c826c027dc259690d60e97cee4711
  - name: cp.icr.io/cp/cpd/wslocal-runtime-251a:12.1.023.01919@sha256:487bb6c2167c1a6867e663fbda548c4d94183bba93ff0cb9425d71857cf311a8
  - name: icr.io/cpopen/ibm-cpd-ws-runtimes-operator:12.1.023@sha256:888b0d948760c5da94a576f4fb422f948805be7b78c87d3de31eed0bc6d87912
