kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/replication-apiserver:2.0.1790-release.5.3.1.12@sha256:58c7734fa4f53a360e9af09a573a56277cba2da530945847f601e0a3f4cf2510
  - name: cp.icr.io/cp/cpd/replication-engine:2.0.1790-release.5.3.1.12@sha256:2043798c61f2d78d1d9f9fae24dce0815bba10212d8f213ff74443c056a3f44b
  - name: cp.icr.io/cp/cpd/replication-ui:2.0.2288-release.5.3.1.14@sha256:55b70159d919e96345eafa7522ea28bfcda22ad54ebda8d7f2b5215280978be0
  - name: icr.io/cpopen/ibm-replication-catalog:5.3.1-release.5.3.1.144@sha256:18bc3fd82320d25e5bee248408952af0634692d7848a4c96b9aeb9db0705f41f
  - name: icr.io/cpopen/ibm-replication-operator-bundle:5.3.1-release.5.3.1.144@sha256:3d2f2554f52bb32505da7c53d8cb7e0a105c22f13e2b348858221a8a24fdadc2
  - name: icr.io/cpopen/ibm-replication-operator:5.3.1-release.5.3.1.144@sha256:f66a6f0ea5c6d59bbec634d2d54bade6df245b1b1eab33f583954f284023a68f
