kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/df/ceph:v4.20.5-7@sha256:b2817cf2f2f0d0d9206f144cebff7b3a7925eb6dfa25f4e6bb548c21847a66e9
  - name: cp.icr.io/cp/df/cephcsi-rhel9:v4.20.5-7@sha256:1efe354fb892b9c6596e83f40b10ac1180714f0a7f51cedcf4ffdf65f522099e
  - name: cp.icr.io/cp/df/mcg-core-rhel9:v4.20.5-7@sha256:e2a4a77c7369101a222e94a965fed9f3d879ca1371d2aaaf71a0f49bbf2ebc53
  - name: cp.icr.io/cp/df/ocs-client-console-rhel9:v4.20.5-7@sha256:e858b220b7d3002516d33b51eabe8ca5ab6c3b6de8bf32baf4bd6ea8d519ee17
  - name: cp.icr.io/cp/df/ocs-metrics-exporter-rhel9:v4.20.5-7@sha256:d94e61a31ef57a619a01b0bfb55afa3fb9f6e9ade15f73df80a36ee3b6840158
  - name: cp.icr.io/cp/df/odf-console-rhel9:v4.20.5-7@sha256:6568b58413693fa48e168bf3565cd9154cd68fce9fa2fea11fac3f58e2db4398
  - name: cp.icr.io/cp/df/odf-cosi-sidecar-rhel9:v4.20.5-7@sha256:11e7c5ecc1c208025f6a01e7d39cab6b87cb38c1160ad5dc18645b35e129c70d
  - name: cp.icr.io/cp/df/odf-csi-addons-sidecar-rhel9:v4.20.5-7@sha256:9599aac018c304f51daa583e7a72a96ca42899afb0aa46688891888124e091cf
  - name: cp.icr.io/cp/df/odf-multicluster-console-rhel9:v4.20.5-7@sha256:b2a5420920a81541456779260dfec860c7dbfe0aa5fb0da8b632a9e240ebb17b
  - name: icr.io/cpopen/cephcsi-operator-bundle:v4.20.5-7@sha256:8d5e5a8dac7efd035ec45e3db450e19c3487599195447f6687e98d94f43959fd
  - name: icr.io/cpopen/cephcsi-operator:v4.20.5-7@sha256:216873125251827191954e72d683685c19eb8385247a4495fe82c1e9b895ccec
  - name: icr.io/cpopen/cnsa-dependencies-operator-bundle:v4.20.5-7@sha256:c63293349a0f1179c5c551225461df64899171332c4fe3e972eaf7d0818989fd
  - name: icr.io/cpopen/isf-data-foundation-catalog:v4.20.5-7@sha256:91b629bb100c5ae187ff9249d5d41475b46aeb9e0d11ffc7092f894698736eac
  - name: icr.io/cpopen/mcg-operator-bundle:v4.20.5-7@sha256:26c24b57e7aa199a980941d9a3219eeacc697fa8d7457377920971f878d24fa8
  - name: icr.io/cpopen/mcg-operator:v4.20.5-7@sha256:105272720e7d95c88b75d4e6771661f13b3dc7569f794288817fdc47c707b9bf
  - name: icr.io/cpopen/ocs-client-operator-bundle:v4.20.5-7@sha256:24ef3ae22e836b5fb9911b12572f0cf1e3ad1add6a57eb805133395631efe253
  - name: icr.io/cpopen/ocs-client-operator:v4.20.5-7@sha256:40f85b60ebf494cbfb9e8f64c2b026daa620286fb63d9509b92d91a129a7d98e
  - name: icr.io/cpopen/ocs-operator-bundle:v4.20.5-7@sha256:138cdfcb408deb45818411b8af2e3cbf637195417369eefd3b03da7862e794e3
  - name: icr.io/cpopen/ocs-operator:v4.20.5-7@sha256:057968f0586650a322179e43c9f3cd3a66add923efdbff5da53642538b628a80
  - name: icr.io/cpopen/odf-csi-addons-operator-bundle:v4.20.5-7@sha256:1bf2b130788d56308d6ad53b8e102c2c72e067afd0292579da5e69b06abc60a1
  - name: icr.io/cpopen/odf-csi-addons-operator:v4.20.5-7@sha256:365344c6a355716ef6fac64a9c48a9453f375ae696a2ec1362bd584c63225bc3
  - name: icr.io/cpopen/odf-dependencies-operator-bundle:v4.20.5-7@sha256:8a3fcf7ddc4037581fa5c5cc0cef24035ebe0bac415dec5b5c258e741d7303a7
  - name: icr.io/cpopen/odf-external-snapshotter-operator-bundle:v4.20.5-7@sha256:40b8430017792206df548593ac2fe7bdc9b4bf04197f1b50b7259299b16af190
  - name: icr.io/cpopen/odf-external-snapshotter-operator:v4.20.5-7@sha256:3b1f61db82dab214dfedeb7aba63a6a9d1c4cc7f559bc92730af912977ba688b
  - name: icr.io/cpopen/odf-multicluster-operator-bundle:v4.20.5-7@sha256:56a1507050fe522cd81c68ddb3e383a359cc2492fc13605a158b49e6c90ace99
  - name: icr.io/cpopen/odf-multicluster-operator:v4.20.5-7@sha256:79821103dc4049c5aa52bd6aa11ced41766849beb761bf6b077bdc8ecff407c2
  - name: icr.io/cpopen/odf-must-gather:v4.20.5-7@sha256:1f1071c472362409891289f88f5f498a8ffb1ec3503d276d01d178301266312a
  - name: icr.io/cpopen/odf-operator-bundle:v4.20.5-7@sha256:407e6a1953f6487b2145878557a35e8e8018349cfc17965a37168e3d33e2f8b6
  - name: icr.io/cpopen/odf-operator:v4.20.5-7@sha256:17e9a0a5e486f9633d4ea03db0e3c0130a5b70debe77321239bb96a25ecd00a8
  - name: icr.io/cpopen/odf-prometheus-operator-bundle:v4.20.5-7@sha256:d80fd9b2b586e1c63263f76a8d425cfede08631ce025c2e606e7ba9efa78bfa0
  - name: icr.io/cpopen/odr-cluster-operator-bundle:v4.20.5-7@sha256:c57bfbd2aa3ef70bf099b72a44b2447509c6c2e89bd60b2356defc3aec84fc32
  - name: icr.io/cpopen/odr-hub-operator-bundle:v4.20.5-7@sha256:27baf28525c79a3ce9d63cdd4ee0d8030ba2112486bfb1fd8400b765a62952b9
  - name: icr.io/cpopen/odr-operator:v4.20.5-7@sha256:b3c10a5b4bc00b789eeb2504e9dcb529527a66c52a24c766d5dcaf7c2fffc6f0
  - name: icr.io/cpopen/odr-recipe-operator-bundle:v4.20.5-7@sha256:d35093555177623d9dd985da1cde5ad36fe236982c9a108304c8a8bc5e3cd114
  - name: icr.io/cpopen/rook-ceph-operator-bundle:v4.20.5-7@sha256:d7c3273c836f971795619b66c646be7e5b2c636eefc3c39f75a9521733c0e493
  - name: icr.io/cpopen/rook-ceph-operator:v4.20.5-7@sha256:01f0394072b01bd2c465a5be7311dde253b8b912488c89ded541aae57f4aa8aa
