kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-ssp-ps/ssp-ps-docker-image:6.2.1.2-iFix00-2026-02-19@sha256:b0d1c8daba4038072b65072dc7c09ff452bced0594f21850e652ffa18da8bb05
