kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/facilities/datainit:9.1.8@sha256:fa0a54e18cdba090b9c886668fdbaa54083181e8c56cf415cf3552acad26828b
  - name: cp.icr.io/cp/facilities/ibm-mas-facilities-ws:9.1.8@sha256:f068c9cd31b049a442d938cb182705816e8993d514c642957bdd365ea87f206b
  - name: cp.icr.io/cp/facilities/platform:9.1.8@sha256:b8092d128bbd957161d70d472e528dffb20592a97599120d8ed60a8317531f82
  - name: cp.icr.io/cp/facilities/usersyncagent:1.0.2@sha256:7980b168503581e8cdbdb52d4d7f113fa7807baf9926ebec4b514fb62684625a
  - name: icr.io/cpopen/ibm-mas-facilities-operator-bundle:9.1.8@sha256:1eb1da00bfe3f25ddfa9e690e7fcb346737eb9bee760905ccaeeb4b2a6f2e1e7
  - name: icr.io/cpopen/ibm-mas-facilities:9.1.8@sha256:c971d06853559077b30a156d5f395ff40393e2e37f23e667baa49fb7051c3f66
