kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/mas/kubectl:5.0.20@sha256:61bc875d64a472380e690ea485300b35c0491aaf68368664831a2a8db8161bbe
  - name: cp.icr.io/cp/predict/explainability:1.7.12@sha256:e3578ea0c0616a0bf62714c1da1d933df35a53c7b805f17cedc74307cce20fba
  - name: cp.icr.io/cp/predict/ibm-mas-predict-ws:9.1.5@sha256:9b40f380787005d77e5e15d6ed4dbd43ac0ab7e1c5e2f4da928a299070dbbec1
  - name: cp.icr.io/cp/predict/mat-service:1.5.3@sha256:82b8c8d7e6fd4fb05d50513fe9141217264aba6fa20dce1fb9a3af12b2153080
  - name: cp.icr.io/cp/predict/predict-api:6.1.10@sha256:a81778a9655b0b5a5c17e38d47e6657eefeb1fd4b0181594cfa8755374b0eae5
  - name: icr.io/cpopen/ibm-mas-predict-operator-bundle:9.1.5@sha256:2791944777b79bc0f6eb4c7fbf0c58dd3363318559a63be01ecaa8844c22ce19
  - name: icr.io/cpopen/ibm-mas-predict:9.1.5@sha256:062427943ce8b1848b9a98d88257629b36ba9b8f6a0cba4f8af26d70eb9752b2
