kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-redis-cp-haproxy:1.3.1@sha256:56a0eee3aa08b1a4a20bcec86a2e4fa7511d124b6cf91b37f5c4bfa09d559380
  - name: cp.icr.io/cp/ibm-redis-cp-operand:1.3.1@sha256:13cbd3b851a8f8624a79111e4e502d2128f53217505eee6693d7bda9f0a0bd58
  - name: icr.io/cpopen/ibm-redis-cp-operator-bundle:1.3.1@sha256:45cd6db9efe0156b63e8caaeee689d832835fab736134f1a063d9c883bb04501
  - name: icr.io/cpopen/ibm-redis-cp-operator-catalog:1.3.1@sha256:33aa607160683e22e89c86a81d59eb9c4a6e4b6cb85ab2825a78ece7f36ea194
  - name: icr.io/cpopen/ibm-redis-cp-operator:1.3.1@sha256:21555bf64cefb36efe14027b4db0cf289fba74749f014a154e943db00f899b5c
