kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/mas/kubectl:5.0.20@sha256:61bc875d64a472380e690ea485300b35c0491aaf68368664831a2a8db8161bbe
  - name: cp.icr.io/cp/predict/explainability:1.7.12@sha256:e3578ea0c0616a0bf62714c1da1d933df35a53c7b805f17cedc74307cce20fba
  - name: cp.icr.io/cp/predict/ibm-mas-predict-ws:9.0.12@sha256:ae00965e79cfbd6f37e24f2a85f3be48d1153f48c0dc98f595128ae9c9969c36
  - name: cp.icr.io/cp/predict/mat-service:1.5.3@sha256:82b8c8d7e6fd4fb05d50513fe9141217264aba6fa20dce1fb9a3af12b2153080
  - name: cp.icr.io/cp/predict/predict-api:6.0.17@sha256:f0246750d9a909991c5fc9cb1cdd7607a71cc9e0a1d017c31cd75017f09efdf3
  - name: icr.io/cpopen/ibm-mas-predict-operator-bundle:9.0.12@sha256:173279633e3b7ee1b1fd34acad4166e86f401e744996b4833611bb76c41d5df9
  - name: icr.io/cpopen/ibm-mas-predict:9.0.12@sha256:4965a21f9bff6399ab9f61b5784b9f50598734bfac268578fe5daed5fdc017b6
