kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/optimizer/admin-ui:9.0.17-amd64@sha256:73683abf6b0578d72ea39b8aff76b59ff793d8029256e99f2f8d1527dc693860
  - name: cp.icr.io/cp/optimizer/api:9.0.19-amd64@sha256:178c78deca59037b16cbe3d40779fe75f6e562ad6c46e17f14a2a91de5b2d395
  - name: cp.icr.io/cp/optimizer/execution-service:9.0.19-amd64@sha256:7594466cc445886ef37ee3189efad29a8041d953b977aa17f3327e509b1b6439
  - name: cp.icr.io/cp/optimizer/ibm-mas-optimizer-appstatus:9.0.19-amd64@sha256:b8758b13886248aed77807a914a2f0997fb1c60cbebf08f37dda163b72f6eafb
  - name: cp.icr.io/cp/optimizer/ibm-mas-optimizer-ws:9.0.19-amd64@sha256:dbaeb6227205d03b2fa11833a0b2fb0146e26c3d4a707d47d1b7cbdfcd6303f3
  - name: cp.icr.io/cp/optimizer/usersyncagent:9.0.21-amd64@sha256:7f3452d82fc12195283ba32bf8ffcd5dbe38fe9818954c30a6031024e2af24cf
  - name: cp.icr.io/cp/optimizer/workspace-init:9.0.19-amd64@sha256:70d0fff4fea6ad64047aed0c01bbd1493d20e4022cf776f5b7271a9dd5a1f987
  - name: icr.io/cpopen/ibm-mas-optimizer-operator-bundle:9.0.19-amd64@sha256:42a084952869863b116881ba4db2bfe72b04dc14ad2cbedc5c37d6a0f25208d3
  - name: icr.io/cpopen/ibm-mas-optimizer-webhook:9.0.19-amd64@sha256:ef7dd47517f9b2c3978548895308b655a65925ed1e30ce00e54f3038223417bc
  - name: icr.io/cpopen/ibm-mas-optimizer:9.0.19-amd64@sha256:642c2daeb12774ed3e8cf57baa20b8fa802345905f0244e47f7b3c881bda9090
