commands:
- set resources deployment iis-xmetarepo --requests=cpu=1 --limits=cpu=3.1,memory=30Gi
- set resources deploymentÂ  iis-services --requests=cpu=3.1
- set resources sts is-en-conductor --requests=cpu=4,memory=5Gi --limits=cpu=10,memory=20Gi
