kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/monitor/as-library:9.1.83@sha256:bc033ab334f7004e014d0416e3eb9c6092a975b49a1c433721ae94171284de3e
  - name: cp.icr.io/cp/monitor/as-ui:9.1.151@sha256:033e035e74d3f73cff761fadf2da443d07e5408805bd593f72f17bc776691308
  - name: cp.icr.io/cp/monitor/db2-dataingest-ciscodnaspaceinputprocessor:9.1.81@sha256:e59c2eefecb5d579e98964858e858ff1c1020515731cfd44f8b73f95f597b404
  - name: cp.icr.io/cp/monitor/db2-dataingest-ciscodnaspacereceiver:9.1.81@sha256:e3efa2a2f5cd8c9602fef965023c777cd406e42742f3ce286b10ee13dbfc599b
  - name: cp.icr.io/cp/monitor/db2-dataingest-datameter:9.1.81@sha256:bc22bba4a4e545b6eb2b6a290e498b30f1e1c032a8b337e285bfea55e29a49c8
  - name: cp.icr.io/cp/monitor/db2-dataingest-inputerrorprocessor:9.1.81@sha256:cbbdc8d0988bb70e6842b02925f07a517dbbd2064f0cc23f5392bb17eac25190
  - name: cp.icr.io/cp/monitor/db2-dataingest-inputprocessor:9.1.81@sha256:ed015b4d0fef430aa62014392583519f4dd0a90f7285b667ff1b41625b6a5315
  - name: cp.icr.io/cp/monitor/db2-dataingest-outputerrorprocessor:9.1.81@sha256:c92672733feab2c9276ae88a0fd732fbda8319b263c82ba1d4cbd50d25fd482d
  - name: cp.icr.io/cp/monitor/db2-dataingest-outputprocessor:9.1.81@sha256:f5a322396e2e0f152a5879e66e26b01b900fc5809d277d4815114c32d3c61897
  - name: cp.icr.io/cp/monitor/db2-dataingest-usagereport:9.1.81@sha256:73536888dcf255cf5805401f7990552698d3e1395d159cf9b57d2e51eaa6c41b
  - name: cp.icr.io/cp/monitor/hook-db-monitor:9.1.121@sha256:cba49efbdbc650c515076a0207a1599e957d7f95527880855e2a49c3102c5ef9
  - name: cp.icr.io/cp/monitor/ibm-mas-monitor-ws:9.1.8@sha256:c341e0b16f5ca0792c695bd65c645f4c834dab002d690699d198bd4d4198973c
  - name: cp.icr.io/cp/monitor/migration-manager:9.1.397@sha256:d4a7ac2979cf8108f6c91449bf872fc9710e5bbb74c5d5dcaa38411160d2058e
  - name: cp.icr.io/cp/monitor/pipeline-engine:9.1.82@sha256:897e34816c2d3a2a8b502a3904cb309aea2f6d898b46c6862dc525ff4874bb9d
  - name: cp.icr.io/cp/monitor/pipeline2-sync-scheduler:9.1.397@sha256:c6eed18bef12aa516828925b30605ccd1ca8e76a3fde2c3eea67c00620e4692f
  - name: cp.icr.io/cp/monitor/rest-dscmanager:9.1.397@sha256:829c6826e22e1aa4aa4447f614af0b4c104237bc35b9d53186d17d8d00a1839f
  - name: cp.icr.io/cp/monitor/v2-core-api:9.1.397@sha256:6f503f7b6e79c30e8bfba8240435064bbfd8bf760db1a50a7109b9555fc7c1fb
  - name: cp.icr.io/cp/monitor/v2-core-scheduler:9.1.397@sha256:1065183ab7b19c65dabbce9fd7653fb39baadd5cbc3cb2a31047b3668f9b8e97
  - name: cp.icr.io/cp/monitor/v2-datalake-api:9.1.397@sha256:8992d0bf1fe47e93b27c4c7d0a0afa0e40aa0c83f28c1784ecb03220b7e4c2cc
  - name: cp.icr.io/cp/monitor/v2-hierarchy-management:9.1.397@sha256:580426c5a0d4bd2b77b66672862d484e74e15c49861e12c1faab604ebf140422
  - name: cp.icr.io/cp/monitor/v2-sync-scheduler:9.1.397@sha256:d263f1de77a46083f4c64508a85d9ca5a836b9c85dc5f7fa21d1a22ceb97f490
  - name: icr.io/cpopen/ibm-mas-monitor-operator-bundle:9.1.8@sha256:f1e8b47b9520f490540e789ec0322cd158a29a3bbdf98b860767a94e5e40b4a1
  - name: icr.io/cpopen/ibm-mas-monitor:9.1.8@sha256:6cd720235576bebbd9cb0a3f00cca12a657c552657dfd106590b5fa89fd73c97
  - name: icr.io/cpopen/ibm-mas/edgedatacollector:2.5.9@sha256:acb17a1b6f2cd9dfff70a4228c03485f81d1ff31b5b51bcd4ece58bd4203c56c
  - name: icr.io/cpopen/ibm-mas/scadaconnector:9.1.4@sha256:194832d0c1146f215a973aa515c9666c4c7557f35611a03b11db1f6d4f4350f9
