kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/dcs/auth:2.5.0@sha256:7f250a45908b4e1dc38e27f78b5059ef792f41befdeabbc9e2fe39730e460909
  - name: cp.icr.io/cp/dcs/connmgr-scheduler:2.5.0@sha256:66077157c0075e7bc8a394ae6ead9145055905fadcbbaa918207655fba979b0b
  - name: cp.icr.io/cp/dcs/connmgr:2.5.0@sha256:b6cf6119ea3c8b132ebb318585b3df31d7546dcede426f4e242e941e1578e239
  - name: cp.icr.io/cp/dcs/db-schema:2.5.0@sha256:2670bb6e15d13d105429373015a0d983bf7551888283f24a19503c6af2bad333
  - name: cp.icr.io/cp/dcs/db2whrest:2.5.0@sha256:45b5cbe849b48db1a0e4562219391af1d488cc13015e6d266c84a09cfe84de4b
  - name: cp.icr.io/cp/dcs/dcs-ai-mcp-server:2.5.0@sha256:ab32ff89dde8101a8f6aac32e3cd2b0cd90009f740411d79770f4d019fd46e80
  - name: cp.icr.io/cp/dcs/import-service:2.5.0@sha256:2519a0250e8e4845e1b3f2edfab5fa8c4b91daf258e9560eebd7b55c801b15e1
  - name: cp.icr.io/cp/dcs/import-tags-app:2.5.0@sha256:a1df2bdbead026e4330ac2ca6f6ee3d98753e86dbc2de11f278ab4367aeaed92
  - name: cp.icr.io/cp/dcs/isd-proxy:2.5.0@sha256:d3ec09a39b8204fb012b6cfca0467e3b40b6971d51faa6ee2b51a4c55b9f4245
  - name: cp.icr.io/cp/dcs/keystone:2.5.0@sha256:803b31e447016782964c53874de4864648aa96b757e1666ed0137c0da22daeae
  - name: cp.icr.io/cp/dcs/metadata-extender:2.5.0@sha256:eb8d8f13bb485f4c07a12f5d6196a0f1511c52d4a9e71da81fa8936c895e0213
  - name: cp.icr.io/cp/dcs/mo-agent-extract:2.5.0@sha256:517dd456066f875a2e3f8e266f008db0d479645599adffd74d8a56b05855419c
  - name: cp.icr.io/cp/dcs/mo-ubi-init:2.5.0@sha256:cbff4ee88318e8f2d19e4dbba506d604cd596aea067743e3925ef4ebe2862c60
  - name: cp.icr.io/cp/dcs/moconsumer:2.5.0@sha256:94b0691c3ca17c804f64d897eff58e1dff4d72ca964a01cf3a6cc46803c6cf9c
  - name: cp.icr.io/cp/dcs/moproducer:2.5.0@sha256:4697ddf2c6055b697279a5fdf734ddeeb58233e7cdad08d71ddad808b147273c
  - name: cp.icr.io/cp/dcs/must-gather:2.5.0@sha256:6193fd192bac6aaa2eef266c863ea7e8b0b773bce1ec3a267af9d82f06404735
  - name: cp.icr.io/cp/dcs/policyengine:2.5.0@sha256:d8a53243048ae84bc24e4af7991c1d1bb84d4da0bac10b50b9a3a3d82f7e078a
  - name: cp.icr.io/cp/dcs/remote-content-search:2.5.0@sha256:5506dd0068810723d337f60ba25a40f242f3a8f20f733070fd45bc9a1d67d6d0
  - name: cp.icr.io/cp/dcs/reports:2.5.0@sha256:940736a9cfd4a5675bc24f31a966f4c789927743b1b0d8162b8edb72c1a36b13
  - name: cp.icr.io/cp/dcs/scaleafmdatamover:2.5.0@sha256:f64778c57cf3e393e3bc5c97539c28685a2e5757c51cbf1b61e3cabba7e40a8c
  - name: cp.icr.io/cp/dcs/scaleilmdatamover:2.5.0@sha256:9a5d15479dc012633798a113b9e474cb4363ace52e8c7f2608222bca7fbd1c2d
  - name: cp.icr.io/cp/dcs/sdmonitor:2.5.0@sha256:2d9e2c949bab5a92acbfe6f4f292fb4a121e00f5d26254fda8ccdee6cf41e83c
  - name: cp.icr.io/cp/dcs/tikaserver:2.5.0@sha256:13eb24ba5793f646681a4761810c3c9296d498a1785614a44b1a59bb1bec42e9
  - name: cp.icr.io/cp/dcs/uibackend:2.5.0@sha256:e060e203d04bb20aa3e9b72fd6f03c304239f065c7e6b1660840321ab3bd11d3
  - name: cp.icr.io/cp/dcs/uifrontend:2.5.0@sha256:f603daad9025c11e3d6d36e54069c609f28d92eda3f0733980d12a6062c500c9
  - name: cp.icr.io/cp/dcs/wkc-connector:2.5.0@sha256:0e22167d95fc973448fb7b8aaa9523c66e6fa808f88d4f2dd358165de5c7925b
  - name: icr.io/cpopen/ibm-spectrum-discover-operator-bundle:v2.5.0@sha256:f5f7f89587f4254f31cf12b9ff7886263fc1b1ca4c8dcdc86a39bc54a0a75dd5
  - name: icr.io/cpopen/ibm-spectrum-discover-operator-catalog:v250.0.0@sha256:a40e35d45abf70a3b66a92b871bf43ca4866b174edabfe5344957dfc75629d7a
  - name: icr.io/cpopen/ibm-spectrum-discover-operator:250.0.0@sha256:448e93dcbf06a4526c0ee8e08e2f39f09eec10375a0ef1aa472020728337c7b5
