kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/assist/assist-db-job:2.0.88@sha256:a33c8cd3f9eca1fa799da11e92d1b70dbb3bc0c0be0b074f923360206186f0ef
  - name: cp.icr.io/cp/assist/assist-useragent:2.0.91@sha256:4cc5d2eef69bfb42acaa5f82c275ed8053b72cff30acaaa2aeaf858a85a55db2
  - name: cp.icr.io/cp/assist/ema-admin-console:2.0.110@sha256:ac7dfe24a792204b7cf40ff4f2fe50d9c6ff43de47b405e88c232e3f6d0e18e4
  - name: cp.icr.io/cp/assist/ema-api:2.0.122@sha256:e6c6fd08a9681f5c2ce302d8c6927de45433ec2f52fb0c172c219316f9db028d
  - name: cp.icr.io/cp/assist/ema-common-util:2.0.76@sha256:1a7865b949cc8e208616e6bf931b821865211754d72ce3f58fd0477d91bf1daf
  - name: cp.icr.io/cp/assist/ema-haproxy:2.0.76@sha256:f29fe996f0f15a5e3a27380ae47f5fd79437beb11d01ed05c2f8b78be9a46680
  - name: cp.icr.io/cp/assist/ema-monitor:2.0.87@sha256:f8396be8b9bbf238659723108595eeb5e21888212cc1b8e32771e355583ae940
  - name: cp.icr.io/cp/assist/ema-multi-tenant:2.0.98@sha256:29cfed8575de71ec7d758ea94ad14b5c521099e7175e1a3511ee0b399f221a91
  - name: cp.icr.io/cp/assist/ema-pg-cronjob:2.0.67@sha256:0da0fe7ce836b3c22ff3fe9d3ec313b480ce908c46810121b318574faea78635
  - name: cp.icr.io/cp/assist/ema-redis:2.0.76@sha256:0a29954ed4155e4f33d15d80e544ff07da2b29320d23ca84c8b28237530cfce5
  - name: cp.icr.io/cp/assist/ema-studio:2.0.86@sha256:50d31c2cbc26bd8060443cc7ce010449624f23a21b86c10defaaebbcc14ff895
  - name: cp.icr.io/cp/assist/ema-technician:2.0.111@sha256:ef616fb8901b7591603b91aff26d18bb5a079c9729e5f026dd04a3f685e5b508
  - name: cp.icr.io/cp/assist/ibm-mas-assist-primary-entity:9.0.13@sha256:8712be859347f4a15fa916081ea7982e42f0c3e5c8a0913a47d7f402e96e0d22
  - name: cp.icr.io/cp/assist/ibm-mas-assist-ws:9.0.13@sha256:5a06e70290a0da40db6548c577f9d916192e524c3cb378a1df8d5a076044f7d8
  - name: icr.io/cpopen/ibm-mas-assist-operator-bundle:9.0.13@sha256:177422a11d97b408ab3274ef48eae0f67d97a53fc1c5d873cb826bc31ad8d5fb
  - name: icr.io/cpopen/ibm-mas-assist:9.0.13@sha256:e129703b5ce0679df8ccba3b7ee4709e2c02418f829cbc37af357f33ffbf5d35
