kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/manage/bdi:8.3.13@sha256:e1dea5c0a288009d03d5ed86f23ece0b28fab926f2b1a44dec15c59ae4f869c1
  - name: cp.icr.io/cp/manage/extension-acm:8.1.28@sha256:41d86062c18b49148fb3d40d1f77293b266521d8e068f71194ad5d400721d3f3
  - name: cp.icr.io/cp/manage/extension-aviation:8.1.33@sha256:dd6135204dd0d8918694cab9f40f893fb9f91c577edc5ac77861ccfa5176d9a0
  - name: cp.icr.io/cp/manage/extension-civil:8.6.26@sha256:9f1029075a337c4923d95825940e9264a17ed6ead4ee376c4e1f9c4fdff9c39c
  - name: cp.icr.io/cp/manage/extension-envizi:8.1.0@sha256:eed9671e993c7550b6e57796fdb44f0ceb5f98cd3e7289652116269fd4c4376e
  - name: cp.icr.io/cp/manage/extension-health:8.9.25@sha256:2df4cfb9c46d93ac33de6a830571d06456996d2f5aed3625121055116205ad78
  - name: cp.icr.io/cp/manage/extension-hse:8.1.17@sha256:e20a240e646423f3ad94563f619df9b2e731572364c9a2acd63882346b08af5a
  - name: cp.icr.io/cp/manage/extension-icd:8.1.15@sha256:39061e5a036f69f23cb140242ef18727ba124760448da1a0aee6a1de609011f3
  - name: cp.icr.io/cp/manage/extension-nuclear:8.1.10@sha256:373ec2becc3bb6d4f6eefbd336c20f021cade50a747e520a1e9d94cf106a5af4
  - name: cp.icr.io/cp/manage/extension-oilandgas:8.1.17@sha256:370e44f734567be7c1ef9fb5dd3469cc817dbbc919293b257e76e10baee4370b
  - name: cp.icr.io/cp/manage/extension-oracleadapter:8.2.0@sha256:d8f3a47ca74207bcef561176fe8f0a6ab05b477aa2e43e432c72c6bda1391234
  - name: cp.icr.io/cp/manage/extension-sapadapter:8.2.0@sha256:eb83c9e0e155d1c6bee8bb63ac3c1581c076dbaec7ec3513ab23ccaae097645c
  - name: cp.icr.io/cp/manage/extension-serviceprovider:8.1.18@sha256:881399f54b28abb8969c0d337a35ea498323e20c777ea5e9bccc01fd7801ce4f
  - name: cp.icr.io/cp/manage/extension-spatial:8.7.23@sha256:8935174280603bf289f9a03b93e71e32260e123fabf05ddcda715a78cc14c049
  - name: cp.icr.io/cp/manage/extension-strategize:8.0.0@sha256:9544f55a6f7c8e3a4aaeae39e9454c3885bce84378ba88e97555a5f9bb66bff5
  - name: cp.icr.io/cp/manage/extension-transportation:8.1.22@sha256:d5fb22efae95f44893b9ca3a299928e0a9a58d92dc94e1494430e5f99622c557
  - name: cp.icr.io/cp/manage/extension-tririga:8.1.1@sha256:b1c0d58b99ac3837f5071c2e22d95f9f150b4b024580cbdc2c25274ace0ec32a
  - name: cp.icr.io/cp/manage/extension-utilities:8.1.19@sha256:ecc8c880af399f103f91f355d751e802eb95513027538cdec99c93e8c8097aa8
  - name: cp.icr.io/cp/manage/extension-workday:8.1.0@sha256:fef64cccc1e544072c7440c7ab9c60fc7b4208df606c120e4d6901a33cb408d3
  - name: cp.icr.io/cp/manage/health-aio:8.9.25@sha256:026a83f8a3f2c557cc6de4afcccb8c8803c9a4ded7e5e764d544cb091ef1049e
  - name: cp.icr.io/cp/manage/healthext-model-engine:1.0.17@sha256:c671f5dfea30d55d94693d32cc37442bbf79bcd598c32873c90d94d3d620a78a
  - name: cp.icr.io/cp/manage/ibm-mas-healthext-ws:1.0.26@sha256:59ce34c30c825bbb25d5541d4945b535b8c9fa053cad02e55c1df6e07e9fb129
  - name: cp.icr.io/cp/manage/ibm-mas-imagestitching:1.0.11@sha256:16f2a44a2f9b9adfad76e3bcccf08c9511930e17e0bdfedca5953e0d0b9cf34a
  - name: cp.icr.io/cp/manage/ibm-mas-manage-appstatus:8.7.28@sha256:eab15e3cbef850f4568a4e4d98e16589817b90f3c26907ca620bb959a1bc620e
  - name: cp.icr.io/cp/manage/ibm-mas-manage-bdi:8.7.28@sha256:d5f3fcfc594468d22ad417896aadf495c672ae407bfb64a9305baaf0ec0b4ca6
  - name: cp.icr.io/cp/manage/ibm-mas-manage-primary-entity:8.7.28@sha256:c388e9951c30b872ec2c66013ad1a95b86851f476c248e9b4d4562ff695a31d4
  - name: cp.icr.io/cp/manage/ibm-mas-manage-ws:8.7.28@sha256:d06ec8f8734519f67b377f750f36a8f62f642a97dd09d12d1c031576eaff6fcb
  - name: cp.icr.io/cp/manage/image-stitching:1.1.41-amd64@sha256:132ce88dff671beca7add6b0041ffc8d841d94b566a04ef54fd47262b44f83d4
  - name: cp.icr.io/cp/manage/maf-tools:8.10.6@sha256:c1dbc2f9572942f6a625259582bafee093ed8b9a377540b78db7a6dcd60bff49
  - name: cp.icr.io/cp/manage/manage-groupsyncagent:1.2.43@sha256:9acaf617c975b7dfcd41ebbaff06656b07a7673ae28968ad9e5b2f2dabd9b929
  - name: cp.icr.io/cp/manage/manage-usersyncagent:2.3.32@sha256:10ebbdb77d60f5b757ad1e50c8d25a815804cec2dd98a4fb5af9042f2cc4d70f
  - name: cp.icr.io/cp/manage/manageadmin:8.7.28@sha256:0dfb7e25c372dcb2330fa03cb0fbda190447c452e973653e66ebc50cd13c9b42
  - name: cp.icr.io/cp/manage/maxloader:9.0.12-amd64@sha256:1d89bc2195809b02342418ca7fae5d762c144c1a9f59ddc66c691d4395e39110
  - name: cp.icr.io/cp/manage/monitoragent:4.1.31@sha256:09fe38cd1c3f992f5fc81a1728f55f6e4c37b656cfee7b9c2dbad267360e4db5
  - name: cp.icr.io/cp/manage/ubi-wlp-jms-manage:2.2.13@sha256:30e5f08695500c28827766477e99eab39110bfa00d85b8925927879edbe9923b
  - name: cp.icr.io/cp/manage/ubi-wlp-manage:3.2.25@sha256:efffea56027bf8c61213e18a609435cc8e3e51b6451c98ee14a206b6795d0555
  - name: icr.io/cpopen/ibm-mas-manage-operator-bundle:8.7.28@sha256:b289306bae17d1a16db8369b1778cc74e4002e22bc1dae6150b256ad1bbc5508
  - name: icr.io/cpopen/ibm-mas-manage-webhook:8.7.28@sha256:8b1bb13c0cca81652ede89d53cfab3387a5abf565798b85347562a676c6b32cf
  - name: icr.io/cpopen/ibm-mas-manage:8.7.28@sha256:b7b4e53adf16813622e33f91046ee60542a6b330f3fd2688dfa3f4ab69538332
