kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/neo4j:2025.12.1-212@sha256:cbd72be5d88726b446c067d06190c43e7e82feb60b7a8c5b27b198335411a970
  - name: cp.icr.io/cp/cpd/neo4j:5.26.20-212@sha256:34f907a0821f8168c3ed6e63c8566d5bf8e9a5ec66a8ee1b69a3fcbedd1172b7
  - name: icr.io/cpopen/ibm-cpd-neo4j-operator-bundle:v4.1.213@sha256:4d652172e8eec71b36906cd0d4b83f2f4a8377ec99f911977817377cdf76a669
  - name: icr.io/cpopen/ibm-cpd-neo4j-operator-catalog:v4.1.213@sha256:9a2e5453e41c7c34dd15fb91617c089f2db1b40c0db854a6422156e24beaf4f3
  - name: icr.io/cpopen/ibm-cpd-neo4j-operator:v4.1.213@sha256:cb18d51e6c976f8e34774bfa3c3238e93344c50948ea75362a53bc36e460e6ad
