kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/df/ceph:v4.18.15-7@sha256:b2817cf2f2f0d0d9206f144cebff7b3a7925eb6dfa25f4e6bb548c21847a66e9
  - name: cp.icr.io/cp/df/cephcsi-rhel9:v4.18.15-7@sha256:fd49a015678c9183a285fe1182b191cdc835c352e6ba93fe7a7bb786165c9451
  - name: cp.icr.io/cp/df/mcg-core-rhel9:v4.18.15-7@sha256:b9a529b9bb75c1d243e1885984202a1455bb1af1abd1b12c28ec7ac4ae297e7b
  - name: cp.icr.io/cp/df/ocs-client-console-rhel9:v4.18.15-7@sha256:fd4734d8ae675259d6b7b9eef2a3f47d0fa5ffd08949d994878a32b26213530c
  - name: cp.icr.io/cp/df/ocs-metrics-exporter-rhel9:v4.18.15-7@sha256:6abb82217baa9a4303d37ab22696592449ab139b707836ccf68c9274c91c2ec8
  - name: cp.icr.io/cp/df/odf-console-rhel9:v4.18.15-7@sha256:4f658541044531421945eb6070f04b25ab070eeb03db96bb3f504b7d3a4f95ec
  - name: cp.icr.io/cp/df/odf-cosi-sidecar-rhel9:v4.18.15-7@sha256:299d0599aef92a2daf80e94865a159661b29444157a192334da38b86db36ff43
  - name: cp.icr.io/cp/df/odf-csi-addons-sidecar-rhel9:v4.18.15-7@sha256:0c7eb52a1fd951a8c3d392ca99507558ec339c1b36ffde9300ae877f30a04c4b
  - name: cp.icr.io/cp/df/odf-multicluster-console-rhel9:v4.18.15-7@sha256:892ccf9fef5924cdab6f2f5a46af5061abe33414e477926d85189d96315bf2e1
  - name: icr.io/cpopen/cephcsi-operator-bundle:v4.18.15-7@sha256:f87bc45bedf8cb32d4fd654eb2755c374ec8c1c3c5364d6ef3a104b251ce4a36
  - name: icr.io/cpopen/cephcsi-operator:v4.18.15-7@sha256:723405a81a253d0b9d69f942f37231655fd677684967c26079aa7458ef033f77
  - name: icr.io/cpopen/isf-data-foundation-catalog:v4.18.15-7@sha256:78c686b5989025d773b5331a747f1d11dea2877dad298beef1c75a87d2c0f1a9
  - name: icr.io/cpopen/mcg-operator-bundle:v4.18.15-7@sha256:98387897b180743fa980330e3b17bec100b06027198b861dbfe4b908c4e618c7
  - name: icr.io/cpopen/mcg-operator:v4.18.15-7@sha256:633befb3f25a1df8b8468fd9ce6cbdded0e90bcfd3d453d46eeb955aa5c3beae
  - name: icr.io/cpopen/ocs-client-operator-bundle:v4.18.15-7@sha256:bd685be62d79d69f7ed6c88e847d9b6d61ca2ddfbd3e5272016639c3785a85a5
  - name: icr.io/cpopen/ocs-client-operator:v4.18.15-7@sha256:1a86a1b250285118fb67e08295ff286915a68d09adbc8de6d8791ffff9a424f1
  - name: icr.io/cpopen/ocs-operator-bundle:v4.18.15-7@sha256:befcd5fc6696e95462c3cbf16ee7764fa44e7a742c298ea30f8f464fca8d0a91
  - name: icr.io/cpopen/ocs-operator:v4.18.15-7@sha256:520fe014fb72421405b29b390ffb79026d63e39314078cc32992feca4ef6ebf0
  - name: icr.io/cpopen/odf-csi-addons-operator-bundle:v4.18.15-7@sha256:c53392a81f9ad14361e3a699855979a6eabcd48e96fe2acc96ca06a6ab559d78
  - name: icr.io/cpopen/odf-csi-addons-operator:v4.18.15-7@sha256:2240d9dae01fdc6fad3e4b2060b254a156d6e4a82740581ead263a10268bb6ee
  - name: icr.io/cpopen/odf-dependencies-operator-bundle:v4.18.15-7@sha256:edba8f68dc40ef9cbf3eb94fa02f81c1b6d0235a9bcf05572588a72b3b548acd
  - name: icr.io/cpopen/odf-multicluster-operator-bundle:v4.18.15-7@sha256:e65384859ff46f9c5ecbd6d301fdf03bfb770653a4e995387344304e466e3fe3
  - name: icr.io/cpopen/odf-multicluster-operator:v4.18.15-7@sha256:1d32a079dea3436f9e85c98b55d723db1253c01a41e0f364385c6d1502af18d2
  - name: icr.io/cpopen/odf-must-gather:v4.18.15-7@sha256:6ffa1b636acc2460a7892c248d54ad067c91b5930b1bb59ecd05515a79dea524
  - name: icr.io/cpopen/odf-operator-bundle:v4.18.15-7@sha256:0209af034b57af50e0c0e4db083829f486f8f85e78669b19ca43b4accd56006c
  - name: icr.io/cpopen/odf-operator:v4.18.15-7@sha256:9b1850b7270c290aec645cfeda6921cf9f15a21cb420acf0fd15f3f00ea8af01
  - name: icr.io/cpopen/odf-prometheus-operator-bundle:v4.18.15-7@sha256:e7dc0285df64f807cc3c7f4679a8597759b62308c150155563b35f479ff3c0fa
  - name: icr.io/cpopen/odr-cluster-operator-bundle:v4.18.15-7@sha256:c2260b5b1a9b4ebca10484580ecaf5c9438b6cac49c027ef5eb72c5e08c1d1a6
  - name: icr.io/cpopen/odr-hub-operator-bundle:v4.18.15-7@sha256:4751ebeb9f5df9152d3cd97a27c2a79c04d5dc822606c8d670a70c640793dbda
  - name: icr.io/cpopen/odr-operator:v4.18.15-7@sha256:64c3b56632d4baf6e8d8fe9ed44787c7b0ecc9b48f172c1eb5414e6833dbcb66
  - name: icr.io/cpopen/odr-recipe-operator-bundle:v4.18.15-7@sha256:4654b20907aa8e19ae542d2627d1128ca024ba0a0dd014b1f2a3ffbf45ac3fb9
  - name: icr.io/cpopen/rook-ceph-operator-bundle:v4.18.15-7@sha256:9cd52968351595f4ee8f2ed082335cf6b32c970a32f54544a75b4c3dae3067a0
  - name: icr.io/cpopen/rook-ceph-operator:v4.18.15-7@sha256:975f54e2fd2f633f727b03930ad01596ee37a8ffea42678e6bd0cf5d7d86952c
