kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/pa/agentic-ai:1.0.38@sha256:f85f0057001ace6c7414f0eefcb9df0b997dd1e06b52a14b3ac727af5c5bf8d3
  - name: cp.icr.io/cp/pa/async-service:1.0.624@sha256:6e5e7e889ef93481ace8a05cc19300487a776c749e47734b9276dc60732b2557
  - name: cp.icr.io/cp/pa/atlas-service:211@sha256:0af2b1afbcf7650aa49c57063199ec581a28c23d06fa586738a8c99679eaa929
  - name: cp.icr.io/cp/pa/bss-init:1.0.465@sha256:09fffe96d3063089d559ac5d13323f711ee645d7119aa782af366f93bcd69cc8
  - name: cp.icr.io/cp/pa/bss:1.0.1557@sha256:5426829b53b8c2bf5860941aa8891c572a1a0fa0791cc978e3d396c2d423b427
  - name: cp.icr.io/cp/pa/k8s-config:1.0.254@sha256:786d86f001da60409621df1ad7accfe2766d27d312e494281ff908842e1eeda5
  - name: cp.icr.io/cp/pa/mongo:1.0.311@sha256:4880d1acf07704cdc6fed36038898808a5fc252cc869a164e58001d20dbcd2ff
  - name: cp.icr.io/cp/pa/monitor:2.1.17.4135@sha256:b666d3c3a5f18c7ee3b5840bf14cb3ef0515a4bb3ef799e0703b6f7fa2087239
  - name: cp.icr.io/cp/pa/mysql-cluster:2.0.273@sha256:b54b9993c7be397804c68b9ce82b4d593d8581485fc4095a683e0ab8afc871e2
  - name: cp.icr.io/cp/pa/neo-idviz:9.0.5057@sha256:ba772f7adcc427135768120435ddb6d251528416f87214193ffc40cb08ff45f1
  - name: cp.icr.io/cp/pa/neo-provision:1.0.576@sha256:ef4b3c27af760de29da9fe5a3da966c7b6b15dbfdee8e17ee7ba02e6c44c22c2
  - name: cp.icr.io/cp/pa/pa-async-handler:12.5.6_1768498013@sha256:310660699ee13f9e1a6d2c04d590556330f3be72896c0a943b2e9a17ff28dbab
  - name: cp.icr.io/cp/pa/pa-authorization:12.5.6_1768498013@sha256:cd88cf0b6be08a890d69ce8fb294c716fbc2fafb2d5951f99063b8339866471f
  - name: cp.icr.io/cp/pa/pa-batch-handler:12.5.6_1768498013@sha256:9b8caa2d2bdca2ec26e2d2b1eb5cdafc9d659477159500c3e0f543e15e6bfc0c
  - name: cp.icr.io/cp/pa/pa-cdn:3.0.15393@sha256:f4da0acbe9c627d41774fada1d3e84400099b4e33ae8ef7d689e6bea119f87fb
  - name: cp.icr.io/cp/pa/pa-content-service:1.0.501@sha256:20061019a18ec032d082ec40bd652db912330fcfcbfe201829ed50440d60babd
  - name: cp.icr.io/cp/pa/pa-evalservice:11.0.110-26011517-1573@sha256:ae1e014223b1ba8c3e639ed62b3a0fd74a4553a3d7b31576b38ef8b2116600e3
  - name: cp.icr.io/cp/pa/pa-gateway:1.0.1152@sha256:1d49ae49174f29673bf5ee4ac3a7f4814a739d53b39bf8237addb386e265cf98
  - name: cp.icr.io/cp/pa/pa-glass:3.0.15393@sha256:970980b1b7392c638eba0b5ad964749bccb37a7fd863185976d4d34a6816ca01
  - name: cp.icr.io/cp/pa/pa-plan-service:1.0.2025121801@sha256:6e77d0d8ac023a9acce1c819e32f2546cf743e41a9df75b2b252cb4932c71077
  - name: cp.icr.io/cp/pa/pa-predict-svc:1.0.1854@sha256:6ea8ee98ca988b9aaef506bd5da42f1e1961f20cab941e6b4d77fe67db0f0a53
  - name: cp.icr.io/cp/pa/pa-scalingjob:0.0.3-1574@sha256:b4e204dbc5b5c269de9393ab39d0c641476f2adea603b61fbc53c04cf9d5ce44
  - name: cp.icr.io/cp/pa/pa-tm1-daemon:12.5.6_1768498013@sha256:fe14c842d1b5c2daad089c02ee782b85e27890175a4adb8c554e74b8ffdfe283
  - name: cp.icr.io/cp/pa/pa-tm1-gateway:12.5.6_1768498013@sha256:a58d74f2fbc62dfb903ab5ae0c10a9f850c997566c2bd98682f9022a3adc4600
  - name: cp.icr.io/cp/pa/pa-tm1-publisher:12.5.6_1768498013@sha256:aaae16ac0eee5856b70bb4906a18ac265c9fdfc0729036207941782360db24c5
  - name: cp.icr.io/cp/pa/pa-tm1:12.5.6_1768498013@sha256:3e1be442429d58fbb198687141abea09d857a9a9e4ce9bcc42cb843566657c29
  - name: cp.icr.io/cp/pa/pa-tm1web:11.0.110-26011517-1573@sha256:a48188d29802e91b476ff919a5e4192aabe56fd11e9b1d96080fd2a6c0c29a20
  - name: cp.icr.io/cp/pa/pa-tm1webproxy:0.0.2-1575@sha256:67dcd1933a2d38238fbbd478690f37b2c2905aadf4e4e3be38d18100a9aa183d
  - name: cp.icr.io/cp/pa/pa-wml-svc:0.0.280@sha256:4076fe7ca1a2e097530bb577c7ce763b1856da85b76aec4ffbe2f7d265ec080a
  - name: cp.icr.io/cp/pa/pacc-backup-restore:0.0.3@sha256:1520d1309e276558cc30171a72b9cf15ae90bde775e5066ae1e0aea5a51fd57d
  - name: cp.icr.io/cp/pa/palm-service:1.0.623@sha256:caf16426f1da5a00013ce3e7a1a63ef8c99a511ec983a815c1eb0332dcb623f2
  - name: cp.icr.io/cp/pa/paqa-service:1.0.497@sha256:e26c79bfbe6f11b4896671e15952c07cc4645f00b2c5f3b22a52e5e48fcb31cf
  - name: cp.icr.io/cp/pa/paw-ui-api:1.0.473@sha256:fb4fd6e0fa428ae4c5c6aa716e31ae571ed1c0967d5acffc4f91b5afe94e6370
  - name: cp.icr.io/cp/pa/prism-app:3.0.5693@sha256:3fd9540099bdc97367663179831a6337fc67004b95ade1cb2de3b5953e8c28bb
  - name: cp.icr.io/cp/pa/prism-platform:3.0.3155.5@sha256:d5caaeddc43e8fd505f1e4a3d7b9c36c2fc166c8f393420535c3dc66b462906f
  - name: cp.icr.io/cp/pa/prism-proxy:3.0.12171@sha256:eed7c97851fa853fe9f8e72a9cf16640a57e0ffd64eebb60c0029432f7aa2ffd
  - name: cp.icr.io/cp/pa/redis:1.0.285@sha256:8efed8182000d96e36ed1be823bc2a69673f195967b354e91d88f6d953e3336e
  - name: cp.icr.io/cp/pa/share-app:1.0.755@sha256:3b23e97a1a8e17a058c4143fd5fc0dfcccd6f5a3df85df188aba6bbad673d0e4
  - name: cp.icr.io/cp/pa/share-platform:1.0.535@sha256:c3c211025a91ca621568505bb122ff43dc0d121d47c34fbce508db4089a3170f
  - name: cp.icr.io/cp/pa/share-proxy:1.0.755@sha256:8544f60a25be966b119b96f3af1722d49b5ef0148d105fe219b87306974057ca
  - name: cp.icr.io/cp/pa/tm1proxy:1.0.534@sha256:153ac966695be8f4ca74b9beae7f7446cc0cb0ba1f151b95d8c6222f25aa0bc4
  - name: cp.icr.io/cp/pa/user-admin:1.0.1102@sha256:70cb8a56afc0f419bbea8974c44a0198aaa9ca5d05d9d037e83519eb0802a830
  - name: cp.icr.io/cp/pa/wa-proxy:1.0.1359@sha256:676fa32a4ad988d41ce72053151157e4d451881cd5e035cbf0819b435baf52f6
  - name: icr.io/cpopen/ibm-pacc-operator:0.0.19@sha256:f246146db2d36ed091b22bb02c603f90a4f09ca04788efc857442658e120a185
  - name: icr.io/cpopen/ibm-pacc-pae-operator:12.5.6_1768498013@sha256:e15c0d80dfdddaeab2343bd1dc9769bfb5783087801c1d36eb6c9d9994a73bf7
  - name: icr.io/cpopen/ibm-pacc-pass-operator:5.3.1-779@sha256:77ba3a41f9c5a75973636dbd8a144f5308a76cdc31dc2ad1fe9b10d491b8c986
  - name: icr.io/cpopen/ibm-pacc-paw-operator:0.0.22@sha256:8a74682f5d6d0095bcc26bb7647dace5f1ea2865eb87a2c569cd1b9459769a9f
