kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/pa-agentic-ai:1.0.38_4@sha256:b2238e6c98b25e360e769a30511b20a4f32db022c8b5434d44fb572949821396
  - name: cp.icr.io/cp/cpd/pa-async-handler:12.5.6_1769710201@sha256:8841fff9319467162a5798192fabca2c1cc70d8520cb46a5ad541f3db7eb1501
  - name: cp.icr.io/cp/cpd/pa-async-service:1.0.624_4@sha256:7f65cb7191379d15fd1fcff2f4c4d3bc521fc40102ed34fd47356d7203ab78c6
  - name: cp.icr.io/cp/cpd/pa-atlas-service:211_4@sha256:763e88025ce3f566985564f32676dfa3f8acdc8ded68707748a87ac045ae98b3
  - name: cp.icr.io/cp/cpd/pa-authorization:12.5.6_1769710201@sha256:f0f2f55c0dafa371880d03bb1bad7775f8ec1d4f3623024fffa07758083b15be
  - name: cp.icr.io/cp/cpd/pa-batch-handler:12.5.6_1769710201@sha256:05b0a8fbe06fef04aa8d179fa3ad28390b86c02d9896cc2be80864a0adeebacf
  - name: cp.icr.io/cp/cpd/pa-bss-init:1.0.465_4@sha256:ac61bdcb251de7eedcf9de95e04b11343fc2aa564aef058103a0090d21d9146e
  - name: cp.icr.io/cp/cpd/pa-bss:1.0.1557_4@sha256:7f74aab8a07f7a900883c32e7c1de9a8af51db8ad949adaa26032bd8450125cb
  - name: cp.icr.io/cp/cpd/pa-cdn:3.0.15393_4@sha256:b3c3cca541dd7bd59ff50785af5f6cf35d5591778506b1f6330f13c10e9842db
  - name: cp.icr.io/cp/cpd/pa-content-service:1.0.501_4@sha256:3995e369015068ec6079a9f39d138f304c95263f5142f568ad0b5571f6334981
  - name: cp.icr.io/cp/cpd/pa-cp4d-service-provider:1.0.60-90@sha256:fb4a5788ddac9bd02eac81c3f5f236e082f85b3cdaec5d6f94726ea4ecba6aaf
  - name: cp.icr.io/cp/cpd/pa-db-tasks:1.0.52-ubi9@sha256:ff17ab309b8367a89a984c73ee6b6339f1fd2f058aba804eb285f2359bcdfdf6
  - name: cp.icr.io/cp/cpd/pa-evalservice:11.0.110-26012212-1094@sha256:e33f1aca003ea928aceec56647560e87f7dec74b5fec4f6069324d0b80a3c6b2
  - name: cp.icr.io/cp/cpd/pa-gateway:1.0.1152_4@sha256:f40b5adedae3b7d62aa7864baab768c9b19a7716513f0dfb61ac9e9e2dcb8387
  - name: cp.icr.io/cp/cpd/pa-glass:3.0.15393_4@sha256:99f8c68901a28d35f60c19c31067912fc35be1fea5aee339a177952b7e319b29
  - name: cp.icr.io/cp/cpd/pa-k8s-config:1.0.254_4@sha256:dee74cd142c8974ff8638d2eae54f52085b8869ff7d0e937b4ceee6d5b56e3cd
  - name: cp.icr.io/cp/cpd/pa-mongo:1.0.311_4@sha256:5fbdeae92cf0436d147e89f2b1c9ea6e47f75b22271acfe8f126cc9874f1d277
  - name: cp.icr.io/cp/cpd/pa-monitor:2.1.17.4135_4@sha256:6638e8fa6fb14e439048d8e8046027840a85d8d4a7b780830807922fe5f3cc53
  - name: cp.icr.io/cp/cpd/pa-mysql-cluster:2.0.273_4@sha256:a02547ca666426d7aa9aecc2f8773644448eeb5b3c834e8d5b304b3fa1557bfa
  - name: cp.icr.io/cp/cpd/pa-neo-idviz:9.0.5057_4@sha256:20d2237764b0bf26dc70b88073f904a27a5e90b3b59acf2bf5f92f6453f966f7
  - name: cp.icr.io/cp/cpd/pa-neo-provision:1.0.576_4@sha256:19e0ec6026ab25ae3a3559fc90094fa0fb389e914554804117885611a4c51c22
  - name: cp.icr.io/cp/cpd/pa-palm-service:1.0.623_4@sha256:4933d9314cb77bdacafd924c067fcb64c9b4b6f3ba9ac3ca3ad024c22eea2deb
  - name: cp.icr.io/cp/cpd/pa-paqa-service:1.0.497_4@sha256:c23845fbaded30688474b0a2fe3fcd94ece6f6934a5e720dd0ba436cc346c78d
  - name: cp.icr.io/cp/cpd/pa-paw-ui-api:1.0.473_4@sha256:3fb0e8b6cd14e01780cc957c17d8b7a01e7bb6b95c25322f6488a08ce7ecd1a9
  - name: cp.icr.io/cp/cpd/pa-plan-service:1.0.2025121801_4@sha256:921a921c1c48be042d0cecf3e6515b1c366a685e3e23960ac0de72231a79d034
  - name: cp.icr.io/cp/cpd/pa-predict-svc:1.0.1854_4@sha256:8ba22eea62714b70d376f79c32e7ad2d61c215b2f13c6285aa9d319197fef5e0
  - name: cp.icr.io/cp/cpd/pa-prism-app:3.0.5693_4@sha256:49bb99744ddd3e3624174c21f6634dae52d00aefbe857d3b285429bcef7a2578
  - name: cp.icr.io/cp/cpd/pa-prism-platform:3.0.3155.5_4@sha256:f86203c874470e6759058fdb57e0187c1c46ae83acc945a3a7e11910bbf9ba73
  - name: cp.icr.io/cp/cpd/pa-prism-proxy:3.0.12171_4@sha256:a83a9541cbc36fd5894bb012c16c4bb9365b950af4f89f2ebca58535dd410144
  - name: cp.icr.io/cp/cpd/pa-redis:1.0.285_4@sha256:1df0273bc7fa834662fd4c7adc8f9dd690e08d2d56fde1784ddbd4301a247e94
  - name: cp.icr.io/cp/cpd/pa-scalingjob:0.0.3-1594@sha256:e38a61ae26764f09a6a278cc1c518d0f2452269c4f952dc01d45721d741a2bfd
  - name: cp.icr.io/cp/cpd/pa-share-app:1.0.755_4@sha256:ab7b2bdae82fa24076f3cfe543f11758bcc928e8a89e358cd3d4fe7a21be9d5e
  - name: cp.icr.io/cp/cpd/pa-share-platform:1.0.535_4@sha256:0739f1d34c86278cf61b0d671fa872c5860963745578176ad4ae76b55149c38a
  - name: cp.icr.io/cp/cpd/pa-share-proxy:1.0.755_4@sha256:a23f9b64d46dee3f2d38a019cc3eb1d0ad0dd27814f00e282c0f3f92b491ad62
  - name: cp.icr.io/cp/cpd/pa-tm1-daemon:12.5.6_1769710201@sha256:2e0da01d5fd969ef941d38ac078b79b42409d17d9abf5bbd14eb4bf0d9552ed4
  - name: cp.icr.io/cp/cpd/pa-tm1-gateway:12.5.6_1769710201@sha256:dc6e8f757beb4ebab9f845fc27aa14f09e3e1406f9c19f958f605fb18b2a2b08
  - name: cp.icr.io/cp/cpd/pa-tm1-publisher:12.5.6_1769710201@sha256:0438ebbd97d03e3acf52634721e51ffc0434e5908a49d3d6fbdef0b724cc0b19
  - name: cp.icr.io/cp/cpd/pa-tm1:12.5.6_1769710201@sha256:99ffc2835dcc51ccbf4cd5df3e16d331eb74af6562475fb3083195e92a20d441
  - name: cp.icr.io/cp/cpd/pa-tm1proxy:1.0.534_4@sha256:a01c53fded8782b74e030e85e032780028d3d78220fc6160339b34483102c8fe
  - name: cp.icr.io/cp/cpd/pa-tm1web:11.0.110-26012212-1094@sha256:0f59d5156e2854006e2801737c56254c6a3e3428c745493e5236ace3a4fa3b0f
  - name: cp.icr.io/cp/cpd/pa-tm1webproxy:0.0.2-1595@sha256:41dfcf099a7534bc24872ad10ee07ffd45051562cb2fc58156751d1a76dc6605
  - name: cp.icr.io/cp/cpd/pa-user-admin:1.0.1102_4@sha256:738d0895d8671f0d32cf20ef3c40478ec3ac8206d7a1959c5284e5b4ae54af29
  - name: cp.icr.io/cp/cpd/pa-wa-proxy:1.0.1346_4@sha256:aeee0983c8ab5a3f76f186b2b5ec1c4b02e09ab40ee7fdc07a7a49a02faf9e16
  - name: cp.icr.io/cp/cpd/pa-wml-svc:0.0.280_4@sha256:9a2324072e4261e90d1e0e7a86d49a4384d1c78f12d9492da6df279016e7192d
  - name: icr.io/cpopen/ibm-planning-analytics-operator-bundle:5.3.1-2315@sha256:8d39d3385dd0f88f6a96d0ae46e98d6c1796da6b62cdda787d2e8dd451cbc61a
  - name: icr.io/cpopen/ibm-planning-analytics-operator-catalog:5.3.1-2315@sha256:61a05c8eb239321c1cad890d5d2cf7eae1c909948966c4a93fa5e1306e0e159b
  - name: icr.io/cpopen/ibm-planning-analytics-operator:5.3.1-2315@sha256:fb8f8489dca64af28030bed9c5d710038f53119cb0d074430b1aca19ad1782a9
  - name: icr.io/cpopen/ibm-planning-analytics-spreadsheet-operator:5.3.1-844@sha256:c64a4eb97cf01b8281b7e0954c15527989a86515ce47be7910d589fac3c470e6
  - name: icr.io/cpopen/ibm-planning-analytics-tm1-operator:12.5.6_1769710201-676@sha256:e7d45f5b46323615ee1c1c428395e3937670c5f87a7425c4693bdeb080527134
