kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-sfg/sfg-dbsetup:6.1.2.8@sha256:884a178fb2388ec1d77101b2486085e9c8a0556ac7054dc30a9a8ee5501070ee
  - name: cp.icr.io/cp/ibm-sfg/sfg-ps:6.1.2.8@sha256:240e15ed6b773df27a0fb1af6b86ba84b346a11684ef39936e399ce1cea00e0c
  - name: cp.icr.io/cp/ibm-sfg/sfg-purge:6.1.2.8@sha256:e5c69521167ef8bbfac82b70625a8944d52feae5f2d720b0da9720d2543f18e4
  - name: cp.icr.io/cp/ibm-sfg/sfg-resources:6.1.2.8@sha256:231c71e2c2f5847156fb37b624df05060e3128b857715563da4ae15946a936e3
  - name: cp.icr.io/cp/ibm-sfg/sfg:6.1.2.8@sha256:b2b3da850fcef733be811b065d4ab1ff2ed97d75037ce2d79baeae789ebea334
  - name: cp.icr.io/cp/opencontent-common-utils:1.1.69@sha256:122ba7c754148d1a95a45a4a531fdf0a7ac90066cc965b8495d2301b93de96ab
