kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/processmining-acf-custom:2.1.0@sha256:c13aad9d0047209bf6935a913799c15285a36024aa49a2a1146979ce3d60adc6
  - name: cp.icr.io/cp/processmining-acf-custom:2.1.0_IF001@sha256:8b1526f75b7552833dec584d35ba316040e89cb19498c9c55733cc7d8e1794e5
  - name: cp.icr.io/cp/processmining-acf-custom:2.1.0_IF002@sha256:f0dd9c28500f7c9198c18b6624f798075a246857f48156fad4240967d4d522e3
  - name: cp.icr.io/cp/processmining-analytics:2.1.0@sha256:b68f7fadee1e78ced6aef333a6f9f99fbacd5c9c806e622d247b97b8452b4898
  - name: cp.icr.io/cp/processmining-analytics:2.1.0_IF001@sha256:4edacbbad0f66ef4d7fe8ea27f67ba78f0557842d71661c865ca1d8469d8038d
  - name: cp.icr.io/cp/processmining-analytics:2.1.0_IF002@sha256:97d3fb3c133a92b353518559c7e845a1490f45d166dd274b42884ecd8c04ef06
  - name: cp.icr.io/cp/processmining-bpa:2.1.0@sha256:b5df1c2195db401f230783e6f9f7d0274eb1eb9fd3d99288df389d012f3c639d
  - name: cp.icr.io/cp/processmining-bpa:2.1.0_IF001@sha256:ecbf6ba8dc75339c83560e588ad6a7918445074f98e5a7891696bb3757e75044
  - name: cp.icr.io/cp/processmining-bpa:2.1.0_IF002@sha256:9f5653e1510a1b90c4758da0edf8893660509bc27ac8d9f75014da7f797f23f1
  - name: cp.icr.io/cp/processmining-connectors:2.1.0@sha256:1a1f1ea71cb0efed43c011971d3de77afe32f965a71a63b998e25d9a797c57ce
  - name: cp.icr.io/cp/processmining-connectors:2.1.0_IF001@sha256:b096be9a3d1a6b602422f968b62a45575fd5b79bcdc4fbaef5163b8c9916114d
  - name: cp.icr.io/cp/processmining-connectors:2.1.0_IF002@sha256:b300e43163f90d51899d05bf4d22fa4d24e5cc4183be2a81bfd5d549f642ebd8
  - name: cp.icr.io/cp/processmining-db-utils:2.1.0@sha256:d3e6725c289dfb1049d9834f27caa4bbe17ede2c0704f5cd50f62cb08b693b7c
  - name: cp.icr.io/cp/processmining-db-utils:2.1.0_IF001@sha256:bf764f3b1e7b1ac14ac92fa8c39f2ae7444ba5151e50f25097b6dd48c4bd8cd0
  - name: cp.icr.io/cp/processmining-db-utils:2.1.0_IF002@sha256:04a9d65f12c263f146b53c7d4f1c887cf364ec08755f05d868aca1c5ec805a94
  - name: cp.icr.io/cp/processmining-discovery:2.1.0@sha256:ea6bde9e13110aa672cc67b55817f1a1cf043776fb41239be7910db61fc657cb
  - name: cp.icr.io/cp/processmining-discovery:2.1.0_IF001@sha256:73b694d1a8d9ac87ef2b249aafdcf92b1b3a386a403601ceacfdbba9a933cf4f
  - name: cp.icr.io/cp/processmining-discovery:2.1.0_IF002@sha256:d1e8f316e41384eff1bd17123ae1223816dc17899ffd069d60290b62ab872d5b
  - name: cp.icr.io/cp/processmining-dr-ml:2.1.0@sha256:31fb45456c764e10a9ad61b2c9a79976a3b67e7f0102388bb55e96587cacb208
  - name: cp.icr.io/cp/processmining-dr-ml:2.1.0_IF001@sha256:8feecb587e6210d9f4ac2830449b34b11eb1448e2935c8cd3f2001695f019b53
  - name: cp.icr.io/cp/processmining-dr-ml:2.1.0_IF002@sha256:68b8d1a8ccdb4a0ea2bd56bf0a6c42ed668ad35073bb3f1474da89c2b2a63ac1
  - name: cp.icr.io/cp/processmining-dr:2.1.0@sha256:0feed8dc8eb9bd47794d95c1d099c2d99e2cfef4e1ebeceb368b48b1167492df
  - name: cp.icr.io/cp/processmining-dr:2.1.0_IF001@sha256:76ed5a2dc46f3fded6539d644c639d44b380713d9151d1675edddf2e2066f813
  - name: cp.icr.io/cp/processmining-dr:2.1.0_IF002@sha256:ba91c21b01209560af96e558ceefdf201505b356327a30a8ae9687874f69182e
  - name: cp.icr.io/cp/processmining-monet:2.1.0@sha256:551c2eeda7dd89421b48d3d18d8b70edd42b8f647d950ae3e8f7228f90dbcb2f
  - name: cp.icr.io/cp/processmining-monet:2.1.0_IF001@sha256:a7f5827ffb8985c2a18f852cd74ac0ceca0b5ddcafb3f512d4f7f0cc86e4f584
  - name: cp.icr.io/cp/processmining-monet:2.1.0_IF002@sha256:d32fc5ec4b7842e3b51b61d4acee4d15c634d1629b1d9791b75e8ac5502ea1ff
  - name: cp.icr.io/cp/processmining-monitoring:2.1.0@sha256:a9ba366b956adefa0d37f4e1f6575c8f88fd3d9208749fe9376413e44719d9fd
  - name: cp.icr.io/cp/processmining-monitoring:2.1.0_IF001@sha256:057c123b232656e060a5ffdde22362ed6784491068847ea752e65d7fd0ca8393
  - name: cp.icr.io/cp/processmining-monitoring:2.1.0_IF002@sha256:a75c9b30ed6d4afcbd432234d2654d62a965605dbd3045468b02b881de45740c
  - name: cp.icr.io/cp/processmining-nginx:2.1.0@sha256:e7b9f43340364afc7cc46283a7cdb257cd946cc43b0cb439abbad023368c2c12
  - name: cp.icr.io/cp/processmining-nginx:2.1.0_IF001@sha256:f65293e662ac005b419eeb9651289b35f559dd640358cfe815500f232da961ef
  - name: cp.icr.io/cp/processmining-nginx:2.1.0_IF002@sha256:ccba5a8aeafcc44bc76f26b0bbd065e3954663f9972c36f257888e030da7b037
  - name: cp.icr.io/cp/processmining-ssl:2.1.0@sha256:db780757a56d1cae9c41709f0992cde8abe780a7be5c1a931a0a39273a13d11d
  - name: cp.icr.io/cp/processmining-ssl:2.1.0_IF001@sha256:34e07edc8d5e78137a673e3712e4219f1a0a3982a8ea70011b4550e7653eb0ae
  - name: cp.icr.io/cp/processmining-ssl:2.1.0_IF002@sha256:1fc7d29f2a043a370dd28e580cef21d3718106b4581a1f043655c644893f14f5
  - name: cp.icr.io/cp/processmining-tm-nginx:2.1.0@sha256:59d491c8917b4d4efa6a077ea69039ae0903ffc3e4fa4a50c50d897bb459baed
  - name: cp.icr.io/cp/processmining-tm-nginx:2.1.0_IF001@sha256:c72b538b7cb0c25f1977ae35caa45a150786a2128bd28f9c5dcd19d127d7beb0
  - name: cp.icr.io/cp/processmining-tm-nginx:2.1.0_IF002@sha256:c4a9bf527dcf571ff4db674943bc23e396df1955dd8c6d607cf6d6cbe2bc21ec
  - name: cp.icr.io/cp/processmining-tm-webapp:2.1.0@sha256:20dc09f9ef55e67d5260ad069658ca0811a323564d3a282aa591153ea785751f
  - name: cp.icr.io/cp/processmining-tm-webapp:2.1.0_IF001@sha256:3e43dae8180eb4743132ef71137ad8f8e734a52bd0dfba0baa5e86b0defdd428
  - name: cp.icr.io/cp/processmining-tm-webapp:2.1.0_IF002@sha256:db7dd899207746b2f2a13be24d7fc94305ba0ce1faca4e8aa901f250c911cc67
  - name: cp.icr.io/cp/processmining-usermanagement:2.1.0@sha256:c2ad486f7a516fc01c06b53a95245f76fe2b63ece2ed36bacb9b4fc166612197
  - name: cp.icr.io/cp/processmining-usermanagement:2.1.0_IF001@sha256:19e65389b86fc1c53eb10e38b1a604ceb9b0c37fe89076972dbdfba72e0c012c
  - name: cp.icr.io/cp/processmining-usermanagement:2.1.0_IF002@sha256:67fd711df3c11e57c39ff4947642bb60f4932fa7053ac6a1a139366d0220974b
  - name: icr.io/cpopen/processmining-operator-bundle:4.0.2@sha256:96bb61523ea6ad019854e41c2f6269621e42ec602eca72d1d596df1ec4412b61
  - name: icr.io/cpopen/processmining-operator-catalog:4.0.2@sha256:fcc97c41aca3239f86ca4265f9e18f5033a605488e606e218b81d8a6f01125e5
  - name: icr.io/cpopen/processmining-operator:4.0.2@sha256:abc3ed29619fe7a957e003cff4b4949ba60831e94ac7288199433f3d92063345
