kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ftm/common/ftm-core-ui-api:3.2.13.0_iFix6_20260128-2034@sha256:693f31fc394a0fae919e80ddc1aea8b54c852966936bd5afbfdc8263e9aedbd9
  - name: cp.icr.io/cp/ftm/common/ftm-secrets-sidecar:3.2.13.0_iFix6-20260129-1628-549@sha256:e1674667689550550cb45dc73c09cab9fa0758b636aeee8be71ae510389e7dab
  - name: cp.icr.io/cp/ftm/common/ftm-ui-boilerplate:3.2.13.0_iFix6_20260129-1524@sha256:14b29ab4beafce34219049aa34736b29652ca84562e2dabf284f3098f36050a1
  - name: cp.icr.io/cp/ftm/common/ftm-ui:3.2.13.0_iFix6_20260122-1625@sha256:44828616779765fd0e5ace84ba26315f549cbe03bfdfa4b6570093a1bef86414
  - name: cp.icr.io/cp/ftm/dp/ftm-j2ee-control-center-ui-no-struts:3.2.13.0_iFix6-20260129-1628-1125@sha256:3272079cae67e904b8cad241d130a06f3df826b4bc008098e88904d1cebce325
  - name: cp.icr.io/cp/ftm/dp/ftm-j2ee-control-center-ui-v3_2_13:3.2.13.0_iFix6-20260129-1628-1490@sha256:1a37b60678d6add06350d66990895bbeab0f1fa736f34ee29b3a75ff0f8a7181
  - name: icr.io/cpopen/ibm-ftm-catalog:4.5.6@sha256:65bd53186dc9f56d9f9a36d160ddfbf712bb978eb32007acb7d549d7fa24e4c6
  - name: icr.io/cpopen/ibm-ftm-operator-api-bundle:4.5.6@sha256:09eaf1be62a1be8e8027547990bfcf8492207cafe7a4f7cfc2a85b9199802d0f
  - name: icr.io/cpopen/ibm-ftm-operator-bundle:4.5.6@sha256:33cd105e1d768f6a74d2d0c2dffe3e886df9bcebf49b2da11f81d26c8d26db23
  - name: icr.io/cpopen/ibm-ftm-operator:4.5.6@sha256:5b7d373ebb2c36d9bc7b434362343e91013e637e25d5697ae3ad63d0988621ac
  - name: icr.io/cpopen/ibm-ftm/openshift4/ose-kube-rbac-proxy:4.5.6@sha256:c8336efb1269a7f40113aa9767c6dc9affe4fd830a1ca6004206bcef1d0274a3
