kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  operators:
  - catalog: icr.io/cpopen/isf-operator-catalog@sha256:deff5e4102374033c6e2db3b1420a2b02a37f10edb06a8c9cd56576dac9b5b4d
    packages:
    - name: isf-operator
      channels:
      - name: v2.0
    full: true
  additionalImages:
  - name: cp.icr.io/cp/fusion-hci/isf-validate-entitlement:2.11.0@sha256:1a0dbf7c537f02dc0091e3abebae0ccac83da6aa147529f5de49af0f23cd9e8e
  - name: icr.io/cpopen/isf-operator-catalog:v2.12.1@sha256:deff5e4102374033c6e2db3b1420a2b02a37f10edb06a8c9cd56576dac9b5b4d
