kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  operators:
  - catalog: icr.io/cpopen/ibm-fncm-catalog@sha256:8fd946c8414f6e387e2b9b86664224ff3cfabd1813b51fbc781256acf17028e9
    packages:
    - name: ibm-fncm-operator
      channels:
      - name: v22.1
      - name: v22.2
      - name: v23.1
      - name: v23.2
      - name: v24.0
      - name: v25.0
    full: true
  additionalImages:
  - name: icr.io/cpopen/ibm-fncm-catalog:v57.0.3-fbc-20260225.011512-6C86E63CA@sha256:8fd946c8414f6e387e2b9b86664224ff3cfabd1813b51fbc781256acf17028e9
