kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/ibm-wca-z-model-gateway:1.0.65@sha256:4e31813b5fc37be947805f1be2b373c0ce9ac6e2845338702e57452fd12dad01
  - name: cp.icr.io/cp/cpd/wca4z-agents-orchestrator-code-explain:1.3.68@sha256:b3a9c6e56367156b1aead2dbeb44fb6c8addecda6ada41f4297010e5c5677e11
  - name: icr.io/cpopen/ibm-wca-z-agentic-operator-bundle:0.10.18@sha256:840cecf50de4a123f5b6858c29002ccb3fc9692d67428fb3ebba3ab03c552583
  - name: icr.io/cpopen/ibm-wca-z-agentic-operator-catalog:0.10.18@sha256:2ec7cefd22276a5b315c1cbf05007086325a250373535e0ceb83710561366c60
  - name: icr.io/cpopen/ibm-wca-z-agentic-operator:0.10.18@sha256:f51837ff07fead869154b2891ace441750bf6ef671dd6b7d628cd96dc07713e0
