kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  operators:
  - catalog: icr.io/cpopen/ibm-data-governor-operator-catalog@sha256:44df273d60e2523e9b9c5c68e0216d769d0ab3bec37fb538195d798e1cf8588a
    packages:
    - name: ibm-data-governor-operator
      channels:
      - name: v3.0
      - name: v3.1
      - name: v3.2
      - name: v3.3
      - name: v4.0
      - name: v4.1
      - name: v4.2
      - name: v4.3
      - name: v4.4
      - name: v4.5
      - name: v4.6
      - name: v4.7
      - name: v4.8
      - name: v4.9
      - name: v5.0
      - name: v5.1
      - name: v5.2
      - name: v6.0
      - name: v6.1
      - name: v6.2
      - name: v6.3
      - name: v7.0
      - name: v7.1
      - name: v7.2
      - name: v8.0
      - name: v8.1
    full: true
  additionalImages:
  - name: icr.io/cpopen/ibm-data-governor-operator-catalog:v8.1.0@sha256:44df273d60e2523e9b9c5c68e0216d769d0ab3bec37fb538195d798e1cf8588a
