kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/mas/ltpakeys-generator:3.3.25-amd64@sha256:317a4edd084825b3c927506640e929e4d5127ca95ce2ed7bf6fc84a5b2630e05
  - name: cp.icr.io/cp/omnio/djangomodel-edgeconfig:1.0.138@sha256:ff111dd82d5a87faa323eee0e74bdfe31f4b5380b76ccc425c4fc771dd606327
  - name: cp.icr.io/cp/omnio/ibm-iot-edgeconfig:1.4.76@sha256:2e495817f565285210b6e7934016e21343563a4af2ae976f6724fd60db74a0b6
  - name: cp.icr.io/cp/omnio/omnio-server:1.0.138@sha256:83e25660f01204a4cea9d8bc3fdd1b1cf9f7276e122fc45d21d20178ae5a6b23
  - name: cp.icr.io/cp/omnio/sqlmodel-edgeconfig:1.0.138@sha256:c33a003aa3a2e3ee953896fb94a81bde6a72b2294b2fff943819b9607ecda199
  - name: cp.icr.io/cp/wiotp/action-mgr:3.0.90@sha256:c69f45412d36fbf07e3c4776fd6065d2a106872ef80ea27ba70038daada8b27a
  - name: cp.icr.io/cp/wiotp/api-actions:3.0.27@sha256:c791cd8551e78b666ab07c611f9d2756589c3604836f8a44deeb366610be12db
  - name: cp.icr.io/cp/wiotp/api-authentication:4.0.31@sha256:6b31383d96cf011b6c8322136ed2369c65bbb4fbf6640c9d17f1ab908afed103
  - name: cp.icr.io/cp/wiotp/api-authorization:7.0.26@sha256:d9112b062ab5ec8c0fc9504e9e194d88cce1fcbba38540f2115c2ea49bc33729
  - name: cp.icr.io/cp/wiotp/api-connectors:5.0.22@sha256:4c93de23a1aba718200a813715dc4a6450598a12c93caa007bcfed3204b1544d
  - name: cp.icr.io/cp/wiotp/api-dashboard:4.0.92@sha256:ef151733f9485b22c4e5bf818a4f8815be220329fc911ec16d15773e13ab6320
  - name: cp.icr.io/cp/wiotp/api-devicemgmt:4.0.21@sha256:ea4ac0b49aad18a8305a92408cd14d51d65fbf8624134156829db080b0f549da
  - name: cp.icr.io/cp/wiotp/api-devops:4.0.21@sha256:d2b45f9b1600901654a4a5e150c4022f7af3914954a2d00b18779fa698f35222
  - name: cp.icr.io/cp/wiotp/api-importconnectors:3.0.38@sha256:8ab2ee173f4a619fea27264471d4bd49bdb0ad26f944315b777a8bdb69888321
  - name: cp.icr.io/cp/wiotp/api-mbgadmin:3.0.83@sha256:4de8f134d8229b815240b9f9e67dc9957d2581b301c7c3fb32d7f7997876bf76
  - name: cp.icr.io/cp/wiotp/api-messagesight:4.0.20@sha256:913d390d9ec3a35ee77c784ba32075b6d31df4b895e797864c29a712b3f0695a
  - name: cp.icr.io/cp/wiotp/api-org:9.0.21@sha256:60999e875be32be63a526832f3d4684701890a862ccc68ba00a115544003258b
  - name: cp.icr.io/cp/wiotp/api-organizations:11.0.23@sha256:5b90b1b441d943bebb02c155b5aad1a4435e4a471c42739efbcd7fd0916ffc45
  - name: cp.icr.io/cp/wiotp/api-pipeline:2.0.66@sha256:9bad5fa922351f96286fb5ceb7bf5b2508f470061c475f4c4687ac2996f060d3
  - name: cp.icr.io/cp/wiotp/api-resourcecontroller:4.0.77@sha256:586ff916afb0e6203f6fe228869808a11c370cd402ea52bf5a74e1658d7d4ce0
  - name: cp.icr.io/cp/wiotp/api-riskmgmt-secguardian:6.0.27@sha256:e8dfc755fecc5effeffc97a5fa17256f850501f9fe40f92912336dc249850085
  - name: cp.icr.io/cp/wiotp/api-s2s:11.0.23@sha256:9312b2006547a7af61b99f585c1f1900be264f560f994ad8a55338e88b75d7c8
  - name: cp.icr.io/cp/wiotp/api-schemas:5.0.22@sha256:f7cc6691fac1bd1bfd8b2e5710af8595914882b89b0bb3d740343b58877d46e9
  - name: cp.icr.io/cp/wiotp/api-state:6.0.25@sha256:81f2bcea13b891e236480d844eb037139b20af6a5caa4d12a1e42f0963a1ccfd
  - name: cp.icr.io/cp/wiotp/api-status:3.4.193@sha256:e0182bb0a82a0ce97e6c9e7b06806a2230f5e90575b3e233616d332d561336db
  - name: cp.icr.io/cp/wiotp/auth-store:3.0.44@sha256:c5eaef7b9ba3fc02d2f77517342b5d5d9d708692273fa25b1bcbd6e395483363
  - name: cp.icr.io/cp/wiotp/config-store:5.0.35@sha256:b059b076106f08397c4e3ea3307790aa0bbf377590953b25d82286a2eb8d77d5
  - name: cp.icr.io/cp/wiotp/connectors-store:9.0.21@sha256:7eabff57fa2aed5ab36766706d50d473642b735cb5c9885d50ca858b88cfa08a
  - name: cp.icr.io/cp/wiotp/data-import-connector:3.0.91@sha256:300c9d3e89ee96d982764eaccc8a1be85d03bf635411ccfa7f8f2e1fac7a68cd
  - name: cp.icr.io/cp/wiotp/datapower-config:10.4.27@sha256:e1cfad323b70b67ee8209a51dd58ffdbe5718c37dcefd68c39cf56db6514c5c3
  - name: cp.icr.io/cp/wiotp/datapower:7.5.140@sha256:a55e8e65cecf9c8d379d0280f6a45edd725e04db5b212f58538d9d6951611c6a
  - name: cp.icr.io/cp/wiotp/deprovagent-actions:1.1.180@sha256:0f86c87da09d7c191441528bf1d0436da6fb51244334a52104bedb350b12e396
  - name: cp.icr.io/cp/wiotp/deprovagent-auth:2.3.179@sha256:37bf1a80329b0b1438a9e554aa18a635baaecb720dbce8137a6432fddedaf647
  - name: cp.icr.io/cp/wiotp/deprovagent-dm:2.1.176@sha256:f69e0b77e40ea894037cde65283184ad87ed92e7d2589746a66b2569648aaf5c
  - name: cp.icr.io/cp/wiotp/deprovagent-fpl:1.0.129@sha256:ca1e2aee370c55e46846c89723a27d3e788cb43cb55dcb600e25464804a8d0b1
  - name: cp.icr.io/cp/wiotp/deprovagent-guardian:3.1.176@sha256:8fd6c76a77ffcd0aee17544bc79c57eeab961d08ca1e0b91f9c0bdd33751ac49
  - name: cp.icr.io/cp/wiotp/deprovagent-orgmgmt:2.1.179@sha256:ea21780734100cb1daf7f2882867cfb4c36f9944d9f601bf614cd8d65d18ce05
  - name: cp.icr.io/cp/wiotp/deprovagent-provision:4.4.174@sha256:51db0c260e95586f5a78619f3535bb1d97bde0330a4094a94b913000fec7ca98
  - name: cp.icr.io/cp/wiotp/deprovagent-registry:2.2.171@sha256:4b00df108076d87049ca570917bd83652db233d0db3146e5bb29c0c5f8d04908
  - name: cp.icr.io/cp/wiotp/deprovagent-state:1.2.176@sha256:72cf5b33776712bf5bc025369a82e5573d83f626233c13c52da115f61119dfff
  - name: cp.icr.io/cp/wiotp/deprovagent-webui:1.2.179@sha256:aafeb95f23e11755472ed19dc81c4969c4a26bed00caec36e685c429068427b7
  - name: cp.icr.io/cp/wiotp/device-store:3.0.26@sha256:75626f81f04977d5ec961f16a44be34f32f20ed2a850d98a2feedf7bfce058cb
  - name: cp.icr.io/cp/wiotp/devicemgmt-server:4.0.26@sha256:b527a203b1f82abbe65ef22039c74195bbd436732a39e1c609c7571a39783725
  - name: cp.icr.io/cp/wiotp/entity-connector:2.0.88@sha256:3ea5f99e0796dc06b85f13fcf1a1611ce76157322be499bdb46300708c25df64
  - name: cp.icr.io/cp/wiotp/entity-manager:3.0.90@sha256:0ce32ddb5692c2f624564d175176f56ef1ed5b92789b24d0e3c465de88b93f82
  - name: cp.icr.io/cp/wiotp/functionsexecutor:2.0.55@sha256:dab98b98b3dc78c012684071f4d438b253a037c0e68e3369944b1bfdcc3ab872
  - name: cp.icr.io/cp/wiotp/graphite-exporter:2.1.217@sha256:f8dc85719ac368604881c8c490e2a7f7a87d8dd13ba82327b4a786ba22ce6528
  - name: cp.icr.io/cp/wiotp/historian-configuration-manager:8.0.16@sha256:1fff0030b483b3c9c737d4bec77c0eb74f54076f5e173d7aff06f75c403a82d3
  - name: cp.icr.io/cp/wiotp/historian-connector:9.0.17@sha256:232201c7e8b53c079753ec1e7bd9e4e4e03e37ed23d4d00acb99f4dfcf4a41a0
  - name: cp.icr.io/cp/wiotp/ibm-iot-actions:3.0.50@sha256:2539b92fb507cf204fd34c0be1b92fa16f4d944fcc8bf252692577c77706ac2c
  - name: cp.icr.io/cp/wiotp/ibm-iot-auth:8.0.59@sha256:3ebf34efd7829da6ef1c8598695b3e43e680824283c82e63e62d3b29860b5057
  - name: cp.icr.io/cp/wiotp/ibm-iot-datapower:7.5.140@sha256:27fab4792644cd29728bf49acf72726f665197097e492a6f6d0747949f379cf8
  - name: cp.icr.io/cp/wiotp/ibm-iot-devops:11.0.50@sha256:97b6eca6e529f7cde1461b5d1c0597e69564841670de2d92a3c74cd876fb5d84
  - name: cp.icr.io/cp/wiotp/ibm-iot-dm:3.0.56@sha256:c461208be061ec6445a83b22730e7df7e191e60cf72abd557a2041dce3b9386a
  - name: cp.icr.io/cp/wiotp/ibm-iot-dsc:7.0.62@sha256:4f9835ec2ea985b79068a4e9115abefa06540a3c065735a6ac051e620fd56020
  - name: cp.icr.io/cp/wiotp/ibm-iot-fpl:2.0.52@sha256:59f9fa6be518f6d363c80adf4eb462ea10b06cca007d031d5c0b6e8e383d5dce
  - name: cp.icr.io/cp/wiotp/ibm-iot-guardian:5.0.46@sha256:a26b64f1cc8e71e521969939917fd67a8330c621a9657d07295953534f332979
  - name: cp.icr.io/cp/wiotp/ibm-iot-mbgx:5.0.54@sha256:3a26e696d6217423ed609f390723a638e06ad2169ebda81be1f6ef85ffaca749
  - name: cp.icr.io/cp/wiotp/ibm-iot-mfgx:7.0.49@sha256:f34cf9e5686fa390514ee6b282a50590ba10d451941f51b5eaff3b1172f014f2
  - name: cp.icr.io/cp/wiotp/ibm-iot-monitor:3.0.52@sha256:13aa6a339b5183934d6ab7cc262db95161f4381d1af884c47095254e5f603eec
  - name: cp.icr.io/cp/wiotp/ibm-iot-orgmgmt:7.0.59@sha256:3f3e514f87b99674432a72ddd723d9e13a8f27f1185aeddcbc0eefe8e57133a5
  - name: cp.icr.io/cp/wiotp/ibm-iot-provision:11.0.51@sha256:264c7bdccb13db313a2306cd4ccea36e29ba43648f28bdafebd9513b2588ea97
  - name: cp.icr.io/cp/wiotp/ibm-iot-registry:9.1.37@sha256:b226fb9f7136d0bb41f3dcb073ec1842ea9af276e37df7c62364163662f23aa8
  - name: cp.icr.io/cp/wiotp/ibm-iot-state:6.0.62@sha256:568f8ca0830a637f1e54899b665dc4db20377c53c61f3d8d4faf803be47738af
  - name: cp.icr.io/cp/wiotp/ibm-iot-webui:7.0.55@sha256:f01efc6a54e323b63837974af9e8c5003faf773c69dff993b92d85f47b9f2356
  - name: cp.icr.io/cp/wiotp/ibm-iot-workspace:2.7.115@sha256:e41145e913557131106ba4b8245698a51bbcfd478b033c17b63948ff4b22dd36
  - name: cp.icr.io/cp/wiotp/ibm-mas-iot-primary-entity:9.1.8@sha256:8f93e5ce5139f0d80f7c29a97f630820b9321a8bb7aab6e0d911476bcb7a4a39
  - name: cp.icr.io/cp/wiotp/masuseragent:1.5.171@sha256:6c91720b8ea988c7decf98f4e784a62aa7a3dbf3b990655e424f930d4df9f471
  - name: cp.icr.io/cp/wiotp/messagegateway-server-configurator:1.6.137@sha256:f177e2089ed9f504208676d38532d9cd082cdd978b2842c3a581f31a78d566cb
  - name: cp.icr.io/cp/wiotp/messagegateway-server:1.6.137@sha256:66d77e12c11403212b4ac1e19a4edd6461b70b9d9f0868aa54211f68068a7708
  - name: cp.icr.io/cp/wiotp/messagesight-configurator:5.16.129@sha256:3d4117ae42f7e168fe169bb710c567ccc5dd652733342d03dcbc44e89b71ef85
  - name: cp.icr.io/cp/wiotp/messagesight:5.16.129@sha256:6aed9855f4277cefcffef2855fa74a3d40997f9b6567cd552536f578e084dbe6
  - name: cp.icr.io/cp/wiotp/monagent-iot:2.3.133@sha256:504d9fb378131ad06a2edb922e4258b7419a7a7c4e88e66534f0791f4ad0bebc
  - name: cp.icr.io/cp/wiotp/monagent-msserver:4.3.233@sha256:054f62e72508f7b2ff3387255aa046737b793e4e364b48f43a34c32f950b8286
  - name: cp.icr.io/cp/wiotp/monagent-org:2.1.242@sha256:2044c15bd8d142164bd26fc92123f2706f9a55aacf7f38938b62d209226d5d2d
  - name: cp.icr.io/cp/wiotp/mongomodel-actions:1.2.171@sha256:d4ca310ecbaccc4a671dafb6ea877d517ed6813bd528ff38547e7d630714112f
  - name: cp.icr.io/cp/wiotp/mongomodel-dm:1.3.176@sha256:cee3d2d9c8175c45db4c87a89b12e3fdf6344a7d86f5ecfde12a68520059e028
  - name: cp.icr.io/cp/wiotp/mongomodel-dsc:1.2.176@sha256:dae9fb1f4f6f7b4f4b62057c339259831d0f5ac17ea6e3ca16bd9ba1a481088a
  - name: cp.icr.io/cp/wiotp/mongomodel-guardian:1.3.173@sha256:02e6928ada4956d2f024540b1a35a56b37ae28210951f22bbaac871f3cfa2ba5
  - name: cp.icr.io/cp/wiotp/mongomodel-orgmgmt:2.0.169@sha256:e89b4e2fb2e6417ad5d61726160b9e64e0c749a7846ef26dd67e6e111f3e29fe
  - name: cp.icr.io/cp/wiotp/mongomodel-provision:2.5.160@sha256:abd8fa7253ac99e45933c3676153bf793640c11e4e526e7fba2079e4c8c4b513
  - name: cp.icr.io/cp/wiotp/mongomodel-registry:2.0.166@sha256:76dd6bef38cbca087b8ca98a52e9c173aec428f0eeb76e58ec1ef5a0af8ec5a4
  - name: cp.icr.io/cp/wiotp/mongomodel-state:1.2.167@sha256:3a8e38a0f8e0bf2f02a47d51c9ebb3e37c925f7b4d02678a172b595bf2380f8b
  - name: cp.icr.io/cp/wiotp/mongomodel-webui:2.3.176@sha256:5cae1835b5286e30599b5d0bf72cf12e17273bb32c5b7517273b244ed6d3e60b
  - name: cp.icr.io/cp/wiotp/mqtt-connector:3.0.80@sha256:65ff1878dafe7b3415b0f9d0065c9632dad00a807c4402922c1dbcaa2345485c
  - name: cp.icr.io/cp/wiotp/msproxy-monitor:9.0.105@sha256:36c37cccd7f1137bdcc488e97086d2c62ddbd808caabb2c9d491533f4ac1d13d
  - name: cp.icr.io/cp/wiotp/msproxy:9.0.105@sha256:c60c348a6ca6267647f8d68e73b39274654c6a988962700c12ddc41a2d1ade86
  - name: cp.icr.io/cp/wiotp/org-store:5.0.77@sha256:bb81b82c1b57dbb2c2566bef44a25c6d7ed98030f983a7c4d20d3f0b502f88b2
  - name: cp.icr.io/cp/wiotp/orgdeprovmgr:2.2.194@sha256:20526f057692c0b6bd7d8d8a52262167076c870bbc296bff7f57448c29e2f373
  - name: cp.icr.io/cp/wiotp/orgpoolmgr:3.1.252@sha256:f61e71079bac3a031871892318231ce8a20a34e84615e796d03f5481a3cca6d7
  - name: cp.icr.io/cp/wiotp/orgprovmgr:2.1.189@sha256:93c0642610238cdadb7001cdf7fe1b36920d2724104f006a1e24786b462b2b63
  - name: cp.icr.io/cp/wiotp/pipelinerouter:2.0.66@sha256:b49bd10626f1d7004b995c2e53535348064c01cc008fa4c5a1ede5589e33a9e4
  - name: cp.icr.io/cp/wiotp/provagent-guardian:2.1.182@sha256:f69d706c5dd263187853501131f392b2220fac1ef51f28081d595a3906cf48be
  - name: cp.icr.io/cp/wiotp/s2s-store:7.0.31@sha256:c0df61950d83ba662f7693259dcdbe9530b4e731ee5969444158b1fc784a09b5
  - name: cp.icr.io/cp/wiotp/sqlmodel-auth:1.1.125@sha256:6c83476ccd0dfa1a9f4c41c49591ec7514f9ae2be8076726fe4b728863235ced
  - name: cp.icr.io/cp/wiotp/sqlmodel-fpl:1.1.92@sha256:e693bd1ed1c2c6ccac0e00fbb3ec9bdd5f963214e3d436e2aa8b9815d0d181c2
  - name: cp.icr.io/cp/wiotp/sqlmodel-state:1.0.167@sha256:01b455e043416af462b5979c8da01318c7b07b8db76b1df1bc5799bde74bbec6
  - name: cp.icr.io/cp/wiotp/state-updater:3.0.39@sha256:90e9263bcd0ff9517ccb442721590a75499b6f9352c02c77ff2dd5f23f83a701
  - name: cp.icr.io/cp/wiotp/statsd:1.3.192@sha256:a0e7ac1caa712e99242bbeec57e11b1b0be2c17061d24b476464b5137dca7e4c
  - name: cp.icr.io/cp/wiotp/ui-dashboard:7.4.81@sha256:05ab6b129ba6e670e3fa7689683729f09e1f78e5a2514755b1fb323fa9118b8a
  - name: icr.io/cpopen/ibm-mas-iot-operator-bundle:9.1.8@sha256:2c7b6f1a4673af4583c7a6ef59379428d9d7582efae8879581a64b07af1212ac
  - name: icr.io/cpopen/ibm-mas-iot:9.1.8@sha256:db9ab436fa3c88225d3600be62a21dbee7e486dd06114e385d87e5b285d580c1
