kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  operators:
  - catalog: icr.io/cpopen/ibm-ads-operator-catalog:24.0.0-IF008@sha256:dd63cba90f4145f05a9aca4e8f6fe10134d4544f598c68fad6b486ed2742f80c
    packages:
    - name: ibm-ads-kn-operator
      channels:
      - name: v24.0
    full: true
  - catalog: icr.io/cpopen/ibm-cs-install-catalog:cd-20251202-1854@sha256:f24bad596f32cc6531420c8533419d6b7bc5c65da5578ab9ca6e55180cd72ac5
    packages:
    - name: ibm-common-service-operator
      channels:
      - name: v4.16
    - name: ibm-namespace-scope-operator
      channels:
      - name: v4.3
    - name: ibm-odlm
      channels:
      - name: v4.5
    full: true
  - catalog: icr.io/cpopen/ibm-events-operator-catalog:5.2.1@sha256:228ea92d69daa2350e151d1fe6b14e6fb56eadd0d3b5b5872178180747297687
    packages:
    - name: ibm-events-operator
      channels:
      - name: v5.2
    full: true
  - catalog: icr.io/cpopen/ibm-iam-operator-catalog:cd-20251202-1854@sha256:620c8985b5e6056082a5e0aa35a91e1de7aeb15145690a4683bd80a32b3e4fa6
    packages:
    - name: ibm-commonui-operator-app
      channels:
      - name: v4.12
    - name: ibm-iam-operator
      channels:
      - name: v4.15
    full: true
  additionalImages:
  - name: cp.icr.io/cp/cpd/edb-postgres-license-provider:2666@sha256:c2759e7125878a909f4ff69db60b5989757d829d313bef01041addf517ef3226
  - name: icr.io/cpopen/common-service-operator:4.16.0@sha256:5c06d9bfb234f914707b2cd0acc74b3c047194ea3c23d74c3400026a2a6aad70
  - name: icr.io/cpopen/cpfs/cpfs-oadp-plugins:4.14.2@sha256:8b879165754a931715a913dcb2a46c03fde883d84dd33c67094e3d8e3dde987a
  - name: icr.io/cpopen/cpfs/cpfs-utils:latest@sha256:f2d63751bb82b6cefa133ca879b4382765176abe99ff44ee726b6b4746e22a8f
  - name: icr.io/cpopen/cpfs/ibm-events-kafka-3.6.1:5.0.1@sha256:545b41cc6c044d6807bfeb7453a045e074a5670cfff9f5c311f4918946901fcb
  - name: icr.io/cpopen/cpfs/ibm-events-kafka-3.8.0:5.1.2@sha256:2754384c6936b36ffd64f89df751cbe47993f73dd700a184af35f412b3408d72
  - name: icr.io/cpopen/cpfs/ibm-im-db-migrator:4.15.0@sha256:891678a0cbf77af747d60641d5d3953f7abf048c05daa8e779e1c1cbd3a7d4dd
  - name: icr.io/cpopen/cpfs/must-gather:latest@sha256:1d81733db6c85dfd7104735d69dad1b5254678cbf47d59195eac6539e7d30f3e
  - name: icr.io/cpopen/edb/postgresql:13.22-5.30.0-cpfs@sha256:950bcd0cbafaad3d7286d08c26b7ff55b03b860ec4bb204ae9dbc8ea9178eb3b
  - name: icr.io/cpopen/edb/postgresql:14.19-5.30.0-cpfs@sha256:70789d893cfec43d0daa2f1e519df7b5aaca5e20952a22c0ba743b06af1c8ce7
  - name: icr.io/cpopen/edb/postgresql:15.14-5.30.0-cpfs@sha256:4fdcb1fad9ffa11d65a9f144a6280051fc9d3d92c36ee2e6d9af67458e39b39d
  - name: icr.io/cpopen/edb/postgresql:16.10-5.30.0-cpfs@sha256:c25a5aa73590c3140d6982749e627d2b665567809b28fec23eee90b47438f9cd
  - name: icr.io/cpopen/edb/postgresql:17.6-5.30.0-cpfs@sha256:b44d7d332140c5be49290c8cd62ad06451d4af439f44ed8edd0a11d5c009ce90
  - name: icr.io/cpopen/ibm-ads-operator-catalog:24.0.0-IF008@sha256:dd63cba90f4145f05a9aca4e8f6fe10134d4544f598c68fad6b486ed2742f80c
  - name: icr.io/cpopen/ibm-ads-operator:24.0.0-IF001@sha256:04a51dd336c951fa1b44ddeedccbf716dc9b4c0c5d2c0f6f40caea938660c9cd
  - name: icr.io/cpopen/ibm-ads-operator:24.0.0-IF002@sha256:23f8d359b157526de677368412238cc262c1ec055a1466846608afb54689b7f1
  - name: icr.io/cpopen/ibm-ads-operator:24.0.0-IF003@sha256:f39c4ae49d82d5ca9e28aaa5906319dad69df53723f01cba37eef157335d6a41
  - name: icr.io/cpopen/ibm-ads-operator:24.0.0-IF004@sha256:cff6c6006cf971d1e1af66253f2fc67c2b6a6bd432d05d158a58303ff9f132f3
  - name: icr.io/cpopen/ibm-ads-operator:24.0.0-IF005@sha256:1dc0f7a02ee3cfc1682335720f2b1a7fa50624f8d5a9e0708bca5f60d32e5985
  - name: icr.io/cpopen/ibm-ads-operator:24.0.0-IF006@sha256:cc277c75fc4529a6b9f41586b7fc900772311a55f855d0eb05d31f183f47e20f
  - name: icr.io/cpopen/ibm-ads-operator:24.0.0-IF007@sha256:885ec6bc3732756de4103bdfe16d049ee4d2a20505b295fe1ae08f0d81aa2ba7
  - name: icr.io/cpopen/ibm-ads-operator:24.0.0@sha256:2ec8e56b85f9759746bd1193b4417f534d1de98cab1e8a2bbec5323d9780265a
  - name: icr.io/cpopen/ibm-common-service-catalog:v4.16.0@sha256:e610fdff3e7cd44be877d9919c40cb00ce361f40882469e670c7c3358fdc6ac8
  - name: icr.io/cpopen/ibm-common-service-operator-bundle:4.16.0@sha256:44bfd04710c15d5d91191f3cedbf588ccc2f698b311142f9f696b4a85770fda3
  - name: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-bundle:2683@sha256:8195d24ea7aea9c228be5c9ea8ac36424bd47eb5baa74cb1010d87f46b1c8f0f
  - name: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-catalog:2683@sha256:796117e1fcc38863f24ace073441c5a6954230ae19df24af8937e2feacf4f5d6
  - name: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator:1.25.4@sha256:9f2bb52755577e2be132498f0c5958085ebee036fb6796849996ff0e12cc3c61
  - name: icr.io/cpopen/ibm-cs-install-catalog:cd-20251202-1854@sha256:f24bad596f32cc6531420c8533419d6b7bc5c65da5578ab9ca6e55180cd72ac5
  - name: icr.io/cpopen/ibm-events-operator-catalog:5.2.1@sha256:228ea92d69daa2350e151d1fe6b14e6fb56eadd0d3b5b5872178180747297687
  - name: icr.io/cpopen/ibm-events-operator:5.0.1@sha256:0fb78efb9e92dd0c2e52ca2488e6f1e7431e197f87e6994e15f7d621b90319f2
  - name: icr.io/cpopen/ibm-events-operator:5.1.2@sha256:46893c166cabdd8b3422a190e220ee2e34861e797aa068100ccf53da349e3fe7
  - name: icr.io/cpopen/ibm-iam-operator-catalog:cd-20251202-1854@sha256:620c8985b5e6056082a5e0aa35a91e1de7aeb15145690a4683bd80a32b3e4fa6
  - name: icr.io/cpopen/ibm-namespace-scope-operator-bundle:4.3.3@sha256:55b302473b484e7dbed548480ae58b31ee93d63c917616a0d01f25f2c514054e
  - name: icr.io/cpopen/ibm-namespace-scope-operator:4.3.3@sha256:b0dea1780969c7c6d0e67f606f00ca3e95bd3f5066e83d516daf7ac72c4f3d86
  - name: icr.io/cpopen/odlm:4.5.5@sha256:9999d1bf02f39c12387c4c9defe75bbbcf2527569be530ee5ac6dd1f7dbb74e4
  - name: icr.io/cpopen/operand-deployment-lifecycle-manager-bundle:4.5.5@sha256:bcc14bf22262bb2fcf13cff2ce5a1cd68e688c78f0b69bbe362c4df2fe8a364b
