kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/cos-logger-sidecar:5313@sha256:27dd0dc3f6969a8bcce597624eadf6a95d1743c9fd388c3497c4e899c13fc3e8
  - name: cp.icr.io/cp/cpd/spark-hb-control-plane:5.3.109642@sha256:0cd07d802a1c5bfbf11973a1ae5925f0661faa7e9a73b83a260c121ccc64714a
  - name: cp.icr.io/cp/cpd/spark-hb-cpd-miniconda-runtimes:3.4.4-v170-5.3.x@sha256:a86348dc4ee128c23cea82863fd4765bd77250233c3e1b5bf08af304a668a5e6
  - name: cp.icr.io/cp/cpd/spark-hb-cpd-miniconda-runtimes:3.5.4-v170-5.3.x@sha256:9d34a52a37546551048f428f19a8ab57dfcdbd8c9e737cff4282e2d9df9cea5f
  - name: cp.icr.io/cp/cpd/spark-hb-cpd-miniconda-runtimes:4.0.0-v170-5.3.x@sha256:a36635a291f9b58f1e563e2d6d109af3279f79a8e4612c5a61d578b59de9f51c
  - name: cp.icr.io/cp/cpd/spark-hb-cpd-miniforge-runtimes:3.4.4-v170-5.3.x@sha256:b0e7dab44248c636390686fb4bd79a3018a8438e07e01a751e479dfc7b4cde1f
  - name: cp.icr.io/cp/cpd/spark-hb-cpd-miniforge-runtimes:3.5.4-v170-5.3.x@sha256:289eb09eb9a74e8c2dca5d07b36aaf757243599b8e27589bf461754897bcb797
  - name: cp.icr.io/cp/cpd/spark-hb-cpd-miniforge-runtimes:4.0.0-v170-5.3.x@sha256:0ec5ceb771705d0426e505f9483606ecda97aa5c2691b0c618d1c053eaa7ee7e
  - name: cp.icr.io/cp/cpd/spark-hb-deployer-agent:5.3.10964@sha256:d67d791264cfc3f11557b386b70996b54972004744d67cc7051bad14b6dcdb38
  - name: cp.icr.io/cp/cpd/spark-hb-graphite-exporter:531-gmc2@sha256:31e38ed4225a0acc8b4d1f5f69a810b6efe8d8ea1020c150a9b2014c0c37ae5b
  - name: cp.icr.io/cp/cpd/spark-hb-helm-repo:5.3.10964@sha256:8b73dd3946880ba87373e5f66c317fd674c94ccbe73d420ec1a0709c5e327771
  - name: cp.icr.io/cp/cpd/spark-hb-instance-operator:5.3.10964@sha256:cbc52e9192317cfc2491f0baffda93a5546dcb1331d7268213ac36a4c93688bc
  - name: cp.icr.io/cp/cpd/spark-hb-nginx:5.3.10964@sha256:4675b64af07da5720eea227fa779b829ca124fba29f20728c27b180992d18703
  - name: cp.icr.io/cp/cpd/spark-hb-python:5.3.10964@sha256:f0881ec3738170abf90aada0989a8e473fbcc89f0b57f48c8a05a1b57464e498
  - name: cp.icr.io/cp/cpd/spark-hb-rsyslog-sidecar:5.3.10964@sha256:0ee6cf3a4f94267d10f6ac4f8f371219bdb86b29dc2f9cfaf8a3ced15ddfedc7
  - name: cp.icr.io/cp/cpd/spark-hb-truststore-util:5.3.10964@sha256:83a2d5fdfd35be28f8a4d7c08b0c4abb4ec6b0f9e120e4ad33577a1fda307cf8
  - name: cp.icr.io/cp/cpd/spark-hb-ui:5.3.10964@sha256:7c5b67bb5b7ac698ca8e2e0fce294639017311e588301af4b8d7586dd8c2b8ed
  - name: cp.icr.io/cp/cpd/spark-hb-wxd-cpd-miniforge-runtimes:3.4.4-v170-5.3.x@sha256:9b3eb94c731c04ae506573ff411992d3a393c4310645dfde04534ed67c4021c6
  - name: cp.icr.io/cp/cpd/spark-hb-wxd-cpd-miniforge-runtimes:3.5.4-v170-5.3.x@sha256:c10fa4a28e9f83aa9907728b8dd69441c43b20899a7e2c06384aeeaa674b0206
  - name: cp.icr.io/cp/cpd/spark-hb-wxd-cpd-miniforge-runtimes:4.0.0-v170-5.3.x@sha256:3bc264308840185a1e6cde41dd3aa2aa38a1bf5d9e138964817cc837e7eb7878
  - name: icr.io/cpopen/ibm-cpd-analyticsengine-dataplane-operator:5.3.1615-amd64@sha256:0d48a291621abd7368546d80fe63f13a7ae55d50e679b11a6241349dd198a4b7
  - name: icr.io/cpopen/ibm-cpd-analyticsengine-operator-bundle:5.3.1615@sha256:480e681c60132774de0a16238cca13b5e607125fbfa93cbb08b0df1ce08e7c84
  - name: icr.io/cpopen/ibm-cpd-analyticsengine-operator-catalog:5.3.1615@sha256:97dd5d52d3a7d8d124b7d66e33021102d45619f2c8a4654ec4d1913f685be295
  - name: icr.io/cpopen/ibm-cpd-analyticsengine-operator:5.3.1615@sha256:1d7d85fd3e052d0477966cf90cf42d0cc2603a9670ce1d77112f67f72c07c2d6
