kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/watson-gateway:v3.12.0@sha256:ea1e67a75e72a2a12a26dcd5a16f638c01690db58764d4bc0218bcaffaa1b734
  - name: cp.icr.io/cp/watson-provisioner:1.1.0@sha256:f7dcf458836560b1845e5cce0812b8d1fad63d1b506e390ec2bb47c95b9d9017
  - name: icr.io/cpopen/watson-gateway-operator-bundle:2.2.0@sha256:e09b26d3769859fb1b9a8b8814fd1b779484f3713ca8f4340bbefef15bce7f6a
  - name: icr.io/cpopen/watson-gateway-operator-catalog:2.2.0@sha256:97c5878fe7fef11de0f6131ea6fd70ff6fa4cb016b8d30b7f491e41952640483
  - name: icr.io/cpopen/watson-gateway-operator:2.2.0@sha256:1b9ace0a967fbf892cf5e86ae7d55f5e830f8703049597aba0ed52efad80da29
