kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/assist/assist-db-job:2.2.20@sha256:ba129fc948cccfe64f3cb6e6a67d533fc6b3253f36d0e41fc40e606d5fe8eb2f
  - name: cp.icr.io/cp/assist/assist-useragent:2.1.34@sha256:bb7bb05b22874254691370f74e123e2bf1b83c4b3cccb6e014bd430daf3a6ab6
  - name: cp.icr.io/cp/assist/ema-admin-console:2.15.7@sha256:29278d83f26808f1dc10877095e59a610026f57bbdba9d6831fdf9233be4d025
  - name: cp.icr.io/cp/assist/ema-api:2.49.17@sha256:d9d7c96dcd9af7117e1dfc2de75e4f5cf33af2237a70814e2389f7de1eb68a13
  - name: cp.icr.io/cp/assist/ema-common-util:2.1.33@sha256:c1e0c4dc12df24d889380d5eb5b623957d252b12e7979b37c58bdf46a52adab4
  - name: cp.icr.io/cp/assist/ema-haproxy:2.1.33@sha256:50858859db5ad48dfb643d6a33546dd237c5020fd201efebde1d0a7462cb947c
  - name: cp.icr.io/cp/assist/ema-monitor:2.2.24@sha256:1d940107882ffdaf83c01e240d6037a7c8233c7a87b7eac8709b2756e7c313d5
  - name: cp.icr.io/cp/assist/ema-multi-tenant:2.19.20@sha256:445588932421cafa61d06225e7563f5736543f2e3db02602d86d8827cf052fda
  - name: cp.icr.io/cp/assist/ema-pg-cronjob:2.1.28@sha256:fafab651786ad5d8d4c71461a140cfd1378e45dced81ed8f9b13136898030c8f
  - name: cp.icr.io/cp/assist/ema-redis:2.1.33@sha256:2f17e31883ad0fa476baf94f555556147d1ac94f8e27da9247f0368c6070eb53
  - name: cp.icr.io/cp/assist/ema-studio:2.12.8@sha256:b3b57916dc8af9210b832f15f6e71599190a543b3b851d6afe866867c05ac1ef
  - name: cp.icr.io/cp/assist/ema-technician:2.14.25@sha256:fc8889e780c27f7b81e1fb8378317fd25df602d05c7b1ae7a131b065e8f4efba
  - name: cp.icr.io/cp/assist/ibm-mas-assist-primary-entity:9.1.8@sha256:1326ba7b3d829c7d546eea93b0fcdd8d7fe8ed84243793bc1b5c5e26a2237265
  - name: cp.icr.io/cp/assist/ibm-mas-assist-ws:9.1.8@sha256:556c643a0039c9ca5ebee9a075975703f341e781777ef418c2813d9ec83f0f29
  - name: icr.io/cpopen/ibm-mas-assist-operator-bundle:9.1.8@sha256:7fac2177c5725b7088f121576641232d56c5fc32b60fa8f299fcfb0c80bc8ede
  - name: icr.io/cpopen/ibm-mas-assist:9.1.8@sha256:832b91f7891bac7d1caa5d1b29378efcd0b96177f98a97c90ccefa5f113b1fe3
