kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/olm-utils-premium-v4:5.3.1@sha256:1ab24a2e3a2c52fd6f0f2a2a5faf11459f1196b9d29b2034488718a6a605094b
  - name: icr.io/cpopen/ibm-software-hub-control-center-operator-bundle:5.4.0-28@sha256:7f397d33967f2f8074c63a72b0cf65e2eed6085cf6ea780f5fa8e09a1bc4bcd4
  - name: icr.io/cpopen/ibm-software-hub-control-center-operator-catalog:5.4.0-28@sha256:08933f7207138476f811c204339aa04e40b94d73ca7befd7b69a8e9a4c150d9f
  - name: icr.io/cpopen/ibm-software-hub-control-center-operator:5.4.0-28@sha256:bf8227d208bfaacb7d1aaa6a38f79e1498f4547b4a2f838b1c9d2bb5738849a3
