kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/optimizer/admin-ui:10.3.12-amd64@sha256:990843e79ce1db21a5b2d31956f3b8f276cd53b4765c16e9855e088298ded715
  - name: cp.icr.io/cp/optimizer/api:9.2.18-amd64@sha256:e205a42c05462908eb8b6c42f176a336b7f812bebc109266526412f62cb9cd5a
  - name: cp.icr.io/cp/optimizer/execution-service:9.2.18-amd64@sha256:e0abc6825d483fc494351c73622b9b334f6a0b0c5d97e165d3c4dd3abb64be3f
  - name: cp.icr.io/cp/optimizer/ibm-mas-optimizer-appstatus:9.1.9-amd64@sha256:3ce7e15bbcb3afc9d6d13697f0633790c12dafbd0775b4f4180d9420f7460ba0
  - name: cp.icr.io/cp/optimizer/ibm-mas-optimizer-primary-entity:9.1.9-amd64@sha256:c3483593e679fd0d68340757e14cb864b9d4564666481066af03c8c1551e953b
  - name: cp.icr.io/cp/optimizer/ibm-mas-optimizer-ws:9.1.9-amd64@sha256:e331130ab1a359ff99a9d58b930780cba01704b8d863f7473649d516ef5bcd4e
  - name: cp.icr.io/cp/optimizer/workspace-init:9.2.18-amd64@sha256:38da5c5f82e0470a9116be5a65e4d807ab34fba7a0e0240373c38d1404dd732d
  - name: icr.io/cpopen/ibm-mas-optimizer-operator-bundle:9.1.9-amd64@sha256:a468413cf73c14c0ef2de381d1874fb1c0f58cceec9771fea2ff48421812bc22
  - name: icr.io/cpopen/ibm-mas-optimizer-webhook:9.1.9-amd64@sha256:cc8c58cc425f36bc65426e20279b309ca541a04e75a200c37dfcf945865ad059
  - name: icr.io/cpopen/ibm-mas-optimizer:9.1.9-amd64@sha256:b40c9940d95117c02cb00ca859e6b99132cbdb6a88e71a68411b5fb6bf94caac
