kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-ssp-ps/ssp-ps-docker-image:6.2.0.3-iFix00-2026-01-19@sha256:16ea05e842e9836b9a4652a99c7468e50c69d3a9424205e86f16afb705053c59
