kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/lineage-scanner-agent:9.1.10@sha256:35baf9eeaf5e97f1c2d43c219338763857a7852a2a0c6994f7b41e8f747ea29b
  - name: cp.icr.io/cp/cpd/lineage-scanner-service:9.0.148-1@sha256:f4277fb7ffda6734afac5f7809b63d64630d0d30dcada56f3227fd987b896434
  - name: cp.icr.io/cp/cpd/lineage-scanner-worker:9.0.139-1@sha256:59ca80c5d379862e66f10da0afcad6e0eb566ff4ec02e0b7198c2243b7af53f7
  - name: cp.icr.io/cp/cpd/lineage-ui:5.3.1414@sha256:2baf523a91a3b7e947dc6c129835e7075796db39a57a5cce5afe5b8abf1b7400
  - name: icr.io/cpopen/edb/postgresql:16.11-5.31.0@sha256:b711c28ad678c53fae114a3b80b801979dd30cf4b7f6676db0db5c9987e377d3
  - name: icr.io/cpopen/ibm-cpd-datalineage-operator-bundle:v5.3.1054@sha256:6ec58dd4a667264eb5f3199052204a2dcebe46ec3cf7be9bed42145bacc78176
  - name: icr.io/cpopen/ibm-cpd-datalineage-operator-catalog:v5.3.1054@sha256:d18f8d7f6b4180c19a45398aa5a2701e68a5e9c5fc52712627c80aa7bafea9be
  - name: icr.io/cpopen/ibm-cpd-datalineage-operator:v5.3.1054@sha256:12a7c741949b1d4f5a2af4ce1860b70dcf1dbaf4cf9affd56e57e9e3e997dda1
