kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/assist/assist-db-job:2.2.20@sha256:ba129fc948cccfe64f3cb6e6a67d533fc6b3253f36d0e41fc40e606d5fe8eb2f
  - name: cp.icr.io/cp/assist/assist-useragent:2.1.34@sha256:bb7bb05b22874254691370f74e123e2bf1b83c4b3cccb6e014bd430daf3a6ab6
  - name: cp.icr.io/cp/assist/ema-admin-console:2.15.7@sha256:79791e7eeee8c52b009382d25648e1a6f7c9ec92f42a47f9b3f728293b80c941
  - name: cp.icr.io/cp/assist/ema-api:2.49.16@sha256:8e24c2f4f3701b5c78d6499fb5226d8a36ab94f68004a96409e216282fccae33
  - name: cp.icr.io/cp/assist/ema-common-util:2.1.33@sha256:c1e0c4dc12df24d889380d5eb5b623957d252b12e7979b37c58bdf46a52adab4
  - name: cp.icr.io/cp/assist/ema-haproxy:2.1.33@sha256:50858859db5ad48dfb643d6a33546dd237c5020fd201efebde1d0a7462cb947c
  - name: cp.icr.io/cp/assist/ema-monitor:2.2.24@sha256:1d940107882ffdaf83c01e240d6037a7c8233c7a87b7eac8709b2756e7c313d5
  - name: cp.icr.io/cp/assist/ema-multi-tenant:2.19.19@sha256:442d19a2743b37d07ff45752d01e695c3ecd80c5494e29c87006eea5c1d1d145
  - name: cp.icr.io/cp/assist/ema-pg-cronjob:2.1.28@sha256:fafab651786ad5d8d4c71461a140cfd1378e45dced81ed8f9b13136898030c8f
  - name: cp.icr.io/cp/assist/ema-redis:2.1.33@sha256:2f17e31883ad0fa476baf94f555556147d1ac94f8e27da9247f0368c6070eb53
  - name: cp.icr.io/cp/assist/ema-studio:2.12.8@sha256:b3b57916dc8af9210b832f15f6e71599190a543b3b851d6afe866867c05ac1ef
  - name: cp.icr.io/cp/assist/ema-technician:2.14.25@sha256:fc8889e780c27f7b81e1fb8378317fd25df602d05c7b1ae7a131b065e8f4efba
  - name: cp.icr.io/cp/assist/ibm-mas-assist-primary-entity:9.1.7@sha256:5de835ace749b3aff69e3bba3cfdcded0d3afeda4a5fa2cab9a1f287d3ee89ed
  - name: cp.icr.io/cp/assist/ibm-mas-assist-ws:9.1.7@sha256:44ecc39a2e3cb33ef12c6a802c77930fc58997510d9327ba8246b47f9b1ff975
  - name: icr.io/cpopen/ibm-mas-assist-operator-bundle:9.1.7@sha256:b3aa69eb2fa8dce2f74d9bef6ee05d4b6894da6b1ce4f1eb202338fe9ac92c14
  - name: icr.io/cpopen/ibm-mas-assist:9.1.7@sha256:2f6fee344836d30bcf266cd3ff9ce145211cb742404adccb7f2cb7d72cb15a4f
