kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-ssp-cm/ssp-cm-docker-image:6.1.0.3-iFix00-2026-01-19@sha256:ed42b631af1c3e6715bb567231bf42bb3f04e5b5f2ce45fccda61f2be35c6b1b
