kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cp4a/odm/dbserver:9.5.0.1-IF003@sha256:c17eb2cc208331c00531a4d9b9f7ba2f8cf955c6f3f13e7cfb6de974e6c16dd1
  - name: cp.icr.io/cp/cp4a/odm/odm-decisioncenter:9.5.0.1-IF003@sha256:931d3a5d06893c799947be756df2e0822811896e1fa181cca28021222fdf417d
  - name: cp.icr.io/cp/cp4a/odm/odm-decisionrunner:9.5.0.1-IF003@sha256:72c763197c76dd1597192720d2dd5fe4eb688ade6bc3c1dff9f886f6c4b3208f
  - name: cp.icr.io/cp/cp4a/odm/odm-decisionserverconsole:9.5.0.1-IF003@sha256:69f64965d86d441ce7046924e587e9622f668cdd20a400bb031965a8db6a8dac
  - name: cp.icr.io/cp/cp4a/odm/odm-decisionserverruntime:9.5.0.1-IF003@sha256:f0255dff036ccc60e6026236331a0afe24510cf5f30224c6a21670c6477c9380
