kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/ibm-dmc-addon-api:8.11.0-32@sha256:2a025c60e0ee6087f9f968776a1b7ba95a1555007f2f7607b3c9fed75f23e292
  - name: cp.icr.io/cp/cpd/ibm-dmc-addon-ui:8.11.0-32@sha256:7e54e094e33f4684a0ffdadc9784e53555977164af2d1185b5ec2d4ed60944d2
  - name: cp.icr.io/cp/cpd/ibm-dmc-admin:3.1.12-122@sha256:c52af3ad7c8d6a7708e28f411a852951397ab986567fd102a7a54a0f1123664e
  - name: cp.icr.io/cp/cpd/ibm-dmc-dbapi:3.1.12-122@sha256:2794cc59c133672ab0489ad179ceae2749aae42b26f5b69298100c44c92613dc
  - name: cp.icr.io/cp/cpd/ibm-dmc-explain:3.1.12-122@sha256:c5618a59aa71a7254e47a286281fdb967d6b89c6f9a826751d5b77dfe2866a4c
  - name: cp.icr.io/cp/cpd/ibm-dmc-job-scheduler:3.1.12-122@sha256:355b02b712bdf98176ecab6a33bd589bb518541f2525ab8e0e021f90dd5c108c
  - name: cp.icr.io/cp/cpd/ibm-dmc-monitor:3.1.12-122@sha256:3f04919126a95fe9f0341c8571f2a012abd36a58ade15991d2deacb99f1d929c
  - name: cp.icr.io/cp/cpd/ibm-dmc-nginx:3.1.12-122@sha256:2ca48340ee087ece39ee3a6ba397dc22bec77e6be84af644d78fe6b2d5f3930c
  - name: cp.icr.io/cp/cpd/ibm-dmc-registry-manager:3.1.12-122@sha256:674de7288861229c22243bb0a5c41506ae79c3979e8b8d6bf0aba83f94335cab
  - name: cp.icr.io/cp/cpd/ibm-dmc-runsql:3.1.12-122@sha256:a7f334f4bad9eab9502c0ebc5c45491726098c08a633cbdd179284178fd29621
  - name: icr.io/cpopen/ibm-dmc-operator-bundle:5.11.0-32@sha256:2a6a50a13cd741705e310634c0108de29d9077aa1ba6b0e0f701861c103c2280
  - name: icr.io/cpopen/ibm-dmc-operator-catalog:5.11.0-32@sha256:00de819d3205613a85dc8a4322227c5f11254936b89458889ef7a1ccd5bbd498
  - name: icr.io/cpopen/ibm-dmc-operator:5.11.0-32@sha256:9b963c666e8fbaab0eade2c522998f6d368627bef9cbc46cc416f7482d00b648
