kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: icr.io/cpopen/ibm-sls-operator-bundle:3.12.5-amd64@sha256:a6bf6b2176174b93eb7bcf6aff0302be1125cf272072f04ccfb84d33ee009b79
  - name: icr.io/cpopen/ibm-sls-operator-bundle:3.12.5-ppc64le@sha256:5d0f815fc50dca0c15a7c78cf8de8a615c7cec105c90ee002861857735d2f284
  - name: icr.io/cpopen/ibm-sls-operator-bundle:3.12.5-s390x@sha256:07aa9b497cae023a5b96f242deec8bc068d759c0642d39a8001dd314d4142bb0
  - name: icr.io/cpopen/ibm-sls/api-licensing:7.4.25-amd64@sha256:f82a8c97f42e19f0a7e29ebb2718841edd560c6d2e581e4984fdd9987e869dcb
  - name: icr.io/cpopen/ibm-sls/api-licensing:7.4.25-ppc64le@sha256:ff9d1b5d145e17d9be5f021c068b5c1842995561d71070c5aaf9bfd3520ce786
  - name: icr.io/cpopen/ibm-sls/api-licensing:7.4.25-s390x@sha256:bd6432f74c0d15797ec1de2dff5630ea005cb31ab51a8b9519e583fc27268ad5
  - name: icr.io/cpopen/ibm-sls:3.12.5-amd64@sha256:13ea3caee5c1003032d87e94c411c0daa5b5c87314aa4f70e41efca999fd29dd
  - name: icr.io/cpopen/ibm-sls:3.12.5-ppc64le@sha256:1cecb3db3bea38c09bda053403a1fc3f8399c468bfffc2067b28dcb86b2716da
  - name: icr.io/cpopen/ibm-sls:3.12.5-s390x@sha256:03f55877c5d07247bb94be0d3664851bed319d4436a394590f98a9ed650264d9
