kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/df/ceph:v4.17.19-4@sha256:e862b5b76da02e77c1d10eea017ea1927f56358a461d26bcf417fa8e571395e7
  - name: cp.icr.io/cp/df/cephcsi-rhel9:v4.17.19-4@sha256:4b80b5e982ee4f5199e4628e2911122513810e13f98778bb4225080b7d133af2
  - name: cp.icr.io/cp/df/mcg-core-rhel9:v4.17.19-4@sha256:7883d0eb013de3540ffea12fb17eaaeb2a48cf04d14310a8774e1d4c6fabf532
  - name: cp.icr.io/cp/df/ocs-client-console-rhel9:v4.17.19-4@sha256:6304df4b5ae07227fa60c5f71f99769d0c8875addc6a5cdd31f2209432fd3ee4
  - name: cp.icr.io/cp/df/ocs-metrics-exporter-rhel9:v4.17.19-4@sha256:dd59662e03b2f93ffe8ba6441e94f82058fb8ec98e4b611a2bab63cd8065da1b
  - name: cp.icr.io/cp/df/odf-console-rhel9:v4.17.19-4@sha256:36c1e5f49eb566bd8a2365af8f84e13b2ba10c76310a14f279b7e559762dea5f
  - name: cp.icr.io/cp/df/odf-cosi-sidecar-rhel9:v4.17.19-4@sha256:fcef6e368919d7e992f0ba0dd60743affd58ac10e801247f258c08d87d4b12db
  - name: cp.icr.io/cp/df/odf-csi-addons-sidecar-rhel9:v4.17.19-4@sha256:06002999d1086b1064ed2c8308b7ec372b90ec06ed393a990673e9f7fb118179
  - name: cp.icr.io/cp/df/odf-multicluster-console-rhel9:v4.17.19-4@sha256:eabc4f71b9e89fe6567baf3a79faf7d6692fed0d7b8ef217f890110ccc1c4d12
  - name: icr.io/cpopen/cephcsi-operator-bundle:v4.17.19-4@sha256:94442cfbb38a8c4ac1dbcc9e934090ee16fc9c1d6939e84808b2b4ce4e236448
  - name: icr.io/cpopen/cephcsi-operator:v4.17.19-4@sha256:a6e23f8e02456c1b584919096a264d43120fc86e1af505eab36a9d1f5ee39734
  - name: icr.io/cpopen/isf-data-foundation-catalog:v4.17.19-4@sha256:8b168e9df982b36dc78c59be91259967895cdc0aea8a98688a091ccb7a7fc9e2
  - name: icr.io/cpopen/mcg-operator-bundle:v4.17.19-4@sha256:d44ec97fc00f329587ef04b1ae5ef8a2592db3ad7fa8c7d816c2612f3891ede6
  - name: icr.io/cpopen/mcg-operator:v4.17.19-4@sha256:f833c1a0b32bec03fc14c4f4f0808b5cc162310520567a7bb25d495e05039862
  - name: icr.io/cpopen/ocs-client-operator-bundle:v4.17.19-4@sha256:6f48b5531f35b113545ae58b84c324970abc601686b2ebf635c86737c185d2e8
  - name: icr.io/cpopen/ocs-client-operator:v4.17.19-4@sha256:b38244e91a1accd4e6c90b7eaa25fb5a1cb701192766f24df7c566d683dcd49c
  - name: icr.io/cpopen/ocs-operator-bundle:v4.17.19-4@sha256:0d5b767e7dca0104257fe14f282fb02072fd8f789a73fe5f5a67fe156547698e
  - name: icr.io/cpopen/ocs-operator:v4.17.19-4@sha256:4800ac8f7c21fb1f279ad89e92d2b61793ae83205e7196531f0f8e38dfbe35cd
  - name: icr.io/cpopen/odf-csi-addons-operator-bundle:v4.17.19-4@sha256:11c4c38586503c0f272b8e71dc9ba7b033fc94ae3442792641b4d3eb5a125aa9
  - name: icr.io/cpopen/odf-csi-addons-operator:v4.17.19-4@sha256:20ed05b453cdfd28c6e8bdc0d864e96c9db48a28d3422241221fcb8e7e6ebdd8
  - name: icr.io/cpopen/odf-multicluster-operator-bundle:v4.17.19-4@sha256:d8527de668ef9665fe5c7409786ec540619aa4eb012195d292c78bbec9e52333
  - name: icr.io/cpopen/odf-multicluster-operator:v4.17.19-4@sha256:0c4bbddc088b70cb0728f5d4e3e3857b1e7c64ee6e4b3afb408cccec17c413c2
  - name: icr.io/cpopen/odf-must-gather:v4.17.19-4@sha256:25da3487f1c5d090fba9635d1b13fe871895842fbd21e295481e287e756a96c0
  - name: icr.io/cpopen/odf-operator-bundle:v4.17.19-4@sha256:8889ead2ae8bfe491080c24e406498ed9a8df4c43b2e41b3619b5c3b2c952e55
  - name: icr.io/cpopen/odf-operator:v4.17.19-4@sha256:4ddb4a2de73163364f786637ee2c758e2cb8209dcc363dc9b0201f011c8940e5
  - name: icr.io/cpopen/odf-prometheus-operator-bundle:v4.17.19-4@sha256:344fd1314fbd0bddf3bf0f5f71da5d2dbebe1337013c6e2cf3a5c478518ff472
  - name: icr.io/cpopen/odr-cluster-operator-bundle:v4.17.19-4@sha256:6a955ca17774b678f2bebde59edaec203242bd070c682abcf9db80ffe8ca9865
  - name: icr.io/cpopen/odr-hub-operator-bundle:v4.17.19-4@sha256:00575311f0a83a6a22befce318275a190151aefcebc351b71456ae10727fb81e
  - name: icr.io/cpopen/odr-operator:v4.17.19-4@sha256:31b7a4d414e7856230affc11d3ab42adeaa80492e15ca5696001311d060ca761
  - name: icr.io/cpopen/odr-recipe-operator-bundle:v4.17.19-4@sha256:265c14aca519e49ec2e8e6acf7c555a4da4408df87e2cf815a43bfd2451638ac
  - name: icr.io/cpopen/rook-ceph-operator-bundle:v4.17.19-4@sha256:dae049826ac1cc70c1fd552d1bda69c4eca31eeaed9e79a03b0e08803bc0fc69
  - name: icr.io/cpopen/rook-ceph-operator:v4.17.19-4@sha256:d85e2ca8c56b88415ef3a791fee09785899f022c8274db2f0eadace7ac8e366a
