kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/datadictionary/kitt-v3-graph-service:3.3.61@sha256:a14c82730362632d305eb115da73429e1101bea87b341da6af08fecb61e5af29
  - name: cp.icr.io/cp/datadictionary/kitt-v3-maximo-connector:3.3.61@sha256:96431b86feb4f6768156fa98ee5f82dc26775dc4547b6a5158b85f276dfbfed2
  - name: cp.icr.io/cp/datadictionary/kitt-v3-router:3.3.61@sha256:a1a2e91301510b0f0ac3ef555e19244b1c21578a6cfc7520896f997d0d5f29ff
  - name: cp.icr.io/cp/datadictionary/kitt-v3-series-store:3.3.61@sha256:1e094a45ba25252f638ec35e082154abe3836c628af2fb17268c9b70f25c6ecb
  - name: cp.icr.io/cp/datadictionary/kitt-v3-user-store:3.3.61@sha256:ee6191f9a9cb15056bc940a4fcd0acee37602f0169a1b4c392a62c4a8463529c
  - name: icr.io/cpopen/ibm-data-dictionary-operator-bundle:1.1.21@sha256:aa256bde673cd8cab474f6dc8bb12ef33c559b5f62416ce4a8778f5269f2ae7a
  - name: icr.io/cpopen/ibm-data-dictionary:1.1.21@sha256:0dfa667e26ec9b499c911d0ff94825cab411890b25c22c418f84c6aed8f202ad
