kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-ssp-engine/ssp-engine-docker-image:6.2.1.2-iFix00-2026-02-19@sha256:d37fecb78d71e8ddbfb3cb8a8ccba3afadb615abe1e4c23357c4295e858e2759
