kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0@sha256:db06cc4c084dd0253134f156dddaaf53ef1c3fb3cc809e5d81711baa4029ea4c
  - name: icr.io/cpopen/ibm-zcon-zosconnect-catalog:v1.1.0@sha256:758c81fec31807f7d526bccc1c6fdffa83b18d7b569af881f7818a4050ec7319
  - name: icr.io/cpopen/ibm-zcon-zosconnect-operator-bundle:v1.1.0@sha256:756783a0e7646351a261c5c5be0d5de28639dc2e2459df6d36f1babab6010db6
  - name: icr.io/cpopen/ibm-zcon-zosconnect-operator:v1.1.0@sha256:a13ba90674b600a76ad4fe02ef3dae360cbf6919c3ccb7ebb1e5f3697825194f
