kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cp4a/odm/dbserver:8.12.0.1-IF036@sha256:c09819f14082a242ddfee87c71645d3a83d9658b2d85420dc6fede86c014651c
  - name: cp.icr.io/cp/cp4a/odm/odm-decisioncenter:8.12.0.1-IF036@sha256:21fb7176434720475950f2cd68fe47cece310cb85c8a367d9a3059340da113fb
  - name: cp.icr.io/cp/cp4a/odm/odm-decisionrunner:8.12.0.1-IF036@sha256:24fcf309175d2aa91ce05dc2816299310e620d6d64d07651b5d2095c63cb0343
  - name: cp.icr.io/cp/cp4a/odm/odm-decisionserverconsole:8.12.0.1-IF036@sha256:e99f378e1f45c9f17232fd6fe0a6a479158a9c5dc8914e19668228ce7292f340
  - name: cp.icr.io/cp/cp4a/odm/odm-decisionserverruntime:8.12.0.1-IF036@sha256:193efe040483f8b17add7930960aa8f5c0719f2b76fac60c65440ce1af9fbcf2
