kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/mas/ltpakeys-generator:3.3.25-amd64@sha256:e8ad4e7c5c45993d33acfc52b2163425eb24dfba6bc9715229c486023fefbfd9
  - name: cp.icr.io/cp/omnio/djangomodel-edgeconfig:0.6.56@sha256:c9e1c8e6bb58791a41800b9cf70f3e283829136afc5acb07919b0d53750b7885
  - name: cp.icr.io/cp/omnio/ibm-iot-edgeconfig:1.2.54@sha256:52a739442f72789a87ebe866605a1ee885a932b1058ed4841d60031c39aff170
  - name: cp.icr.io/cp/omnio/omnio-configuration-ui:0.6.62@sha256:7cdc3978c7ac70cdd136ac4f422da1f73951147643565ed53984eafa7c7e37a0
  - name: cp.icr.io/cp/omnio/omnio-server:0.6.56@sha256:0b7f47ca506d197d27a2df84958584da92a52f0f8457d01e0f22912178e611e3
  - name: cp.icr.io/cp/omnio/sqlmodel-edgeconfig:0.6.56@sha256:a0c512ecea56cc6dcafbbbc5dd1b7335850d33248098624c6f99917201a1a452
  - name: cp.icr.io/cp/wiotp/action-mgr:3.0.88@sha256:cc357e994c464f1d7d576160262ea6f94c945d191b637547d2d3447c224f6fd9
  - name: cp.icr.io/cp/wiotp/api-actions:3.0.26@sha256:5f789eb350b160f2d63d618c817cd7977af7bdb9fcd1e71fd3bf9a41d6ee2ec2
  - name: cp.icr.io/cp/wiotp/api-authentication:4.0.30@sha256:13279efa3888d7c3f1f9dacd345104e38025d6aa74280199f497a212ebe976e7
  - name: cp.icr.io/cp/wiotp/api-authorization:7.0.25@sha256:799314f80418bce2c9d860cb0cbfd66fac8a746e9f682a67ea532a7c2f5f321e
  - name: cp.icr.io/cp/wiotp/api-connectors:5.0.21@sha256:94856ab4db0e8f57e63acbf65738eb48dcc9d5039c6396474cf8245ab2e3414e
  - name: cp.icr.io/cp/wiotp/api-dashboard:4.0.88@sha256:e055038938ac53758434c827af9209297b046acd01b9dbc388102034a41fb8ae
  - name: cp.icr.io/cp/wiotp/api-devicemgmt:4.0.21@sha256:ea4ac0b49aad18a8305a92408cd14d51d65fbf8624134156829db080b0f549da
  - name: cp.icr.io/cp/wiotp/api-devops:4.0.20@sha256:696091b239db9879f3d0503583a1d1c15e86737ac52a94b2d7310e449b7efda7
  - name: cp.icr.io/cp/wiotp/api-importconnectors:3.0.37@sha256:e984979e1ce1c5aed2badc2e37075ad7bf7748fdf80856feeb1392bccf63e984
  - name: cp.icr.io/cp/wiotp/api-mbgadmin:3.0.80@sha256:485164446c617d73fb56bc42eead449c124ea0d338ef9c17ff9a1020304b5518
  - name: cp.icr.io/cp/wiotp/api-messagesight:4.0.19@sha256:ad2c1625234e835fdd503be1ee28b6be55d2eabac06bb5842edab295e1e76f9f
  - name: cp.icr.io/cp/wiotp/api-org:9.0.20@sha256:e400910f0435a56501f95999a22cdbfb320f53cb78833fddcf183fdf93987d4e
  - name: cp.icr.io/cp/wiotp/api-organizations:11.0.22@sha256:3ce8040b27a1ccae268a0e47ade332c8200b75456dfb0a40ad02857bee14e1ee
  - name: cp.icr.io/cp/wiotp/api-pipeline:2.0.62@sha256:e344e13cc119f5c06fe42c0185b0ba60b75d5b16571a04a619b850dd5a88a6b1
  - name: cp.icr.io/cp/wiotp/api-resourcecontroller:4.0.77@sha256:586ff916afb0e6203f6fe228869808a11c370cd402ea52bf5a74e1658d7d4ce0
  - name: cp.icr.io/cp/wiotp/api-riskmgmt-secguardian:6.0.26@sha256:f6f90398002b67988b06aac418ec15eb33f25d9a5b043308a9a7ffbabaac8395
  - name: cp.icr.io/cp/wiotp/api-s2s:11.0.22@sha256:99fe95bc36a74307737f62e0628d62b690c5f5f66ddb5c16b5162e0c59eb785d
  - name: cp.icr.io/cp/wiotp/api-schemas:5.0.21@sha256:fd48bf65db2b14efc1479cf9a2bea9fd012a61ed06e754e932b1390c61e07080
  - name: cp.icr.io/cp/wiotp/api-state:6.0.24@sha256:375711793f0f52844a44cee90174e338e45864101c9236f669e39db9c200515d
  - name: cp.icr.io/cp/wiotp/api-status:3.4.187@sha256:2b809d168a408d9b846349e3073d353fd20316bdafacbd35222c65ed1991cb2d
  - name: cp.icr.io/cp/wiotp/auth-store:3.0.43@sha256:039d681c0907fccf793af393e6fd86d163f795b9cf3c64bac362dbc5e3d58c13
  - name: cp.icr.io/cp/wiotp/config-store:5.0.34@sha256:c3c22b0e15345eedd083cba3143536a347db90b5cc0a55665d656818b61e393d
  - name: cp.icr.io/cp/wiotp/connectors-store:9.0.20@sha256:8edd3738d5140afcf75e6db99dba8c2073d6fd49e5ef836f4f81872ee13de79c
  - name: cp.icr.io/cp/wiotp/data-import-connector:3.0.85@sha256:e10ce62213cbf7703b9e71fd1fe1f83198483c21eb025552a3608ac41137a25f
  - name: cp.icr.io/cp/wiotp/datapower-config:10.4.22@sha256:990260b07f09116a3568cfaec85faba49b4f4ca39363dd0686c4cf8f50cabfbf
  - name: cp.icr.io/cp/wiotp/datapower:7.5.135@sha256:abbe232c39d38b858ac490f06524535873cfa8a80b7ff3d818580c4ba0f52cab
  - name: cp.icr.io/cp/wiotp/deprovagent-actions:1.1.178@sha256:5ff2a3ccf934b7db80737ecf8ef7ab4909bce36a730900f3b884b9817dd1a787
  - name: cp.icr.io/cp/wiotp/deprovagent-auth:2.3.174@sha256:151bc200d030a5e3db59e5105985a9587750a98003a7ad0bf5a04942e99b58f8
  - name: cp.icr.io/cp/wiotp/deprovagent-dm:2.1.174@sha256:e520eaa773fa275cd57e874f684af125897178832266c768fa737f829f7cf30c
  - name: cp.icr.io/cp/wiotp/deprovagent-fpl:1.0.126@sha256:e0bd9336c6ba2fce9136e82b96ed281f756974214f459d23934cd091f6d7f9e0
  - name: cp.icr.io/cp/wiotp/deprovagent-guardian:3.1.174@sha256:4789ccb03d3aa20ea77691a70b14336a7a0e475a54c1827562911930e5be5ea7
  - name: cp.icr.io/cp/wiotp/deprovagent-orgmgmt:2.1.177@sha256:349545cb92adf2d474960798a07886b5a7d953eb520ed1a9d9b33c5e5e775234
  - name: cp.icr.io/cp/wiotp/deprovagent-provision:4.4.172@sha256:83758b945db771c5b812d12b3e409e1dfd841205da4b09e7d0c5d236a1d54e0d
  - name: cp.icr.io/cp/wiotp/deprovagent-registry:2.2.169@sha256:4aa1a6ecef73e0d9ee3d698b22ec449c4b9c47ae5c3e694680d8a641b430528c
  - name: cp.icr.io/cp/wiotp/deprovagent-state:1.2.173@sha256:464a1e295c8edbe77588a35987c77e247798cae7338e5b10be4fba44404860c9
  - name: cp.icr.io/cp/wiotp/deprovagent-webui:1.2.177@sha256:4e33a82b90acd81ac4fc2c3da85cb79d8e98697b96f5f584b53ca5f9f14027b9
  - name: cp.icr.io/cp/wiotp/device-store:3.0.26@sha256:75626f81f04977d5ec961f16a44be34f32f20ed2a850d98a2feedf7bfce058cb
  - name: cp.icr.io/cp/wiotp/devicemgmt-server:4.0.24@sha256:8606ac275e9d2be13d8de1818f823db99f365d85a1f40cf7c6dbb4a8dfb3e130
  - name: cp.icr.io/cp/wiotp/entity-connector:2.0.85@sha256:285f3158829c1699fd12f4237df57ac00d6056354c6779a9d261e52b4bf2c1a9
  - name: cp.icr.io/cp/wiotp/entity-manager:3.0.88@sha256:63b569193d19f1daeb6c5f50d4e7829e741cb024a6afda77fbec853da70bea9b
  - name: cp.icr.io/cp/wiotp/functionsexecutor:2.0.48@sha256:1e7be3256c4dd2d7bef470e9a26909b31119fd7fe9836206d447859b8961a0a9
  - name: cp.icr.io/cp/wiotp/graphite-exporter:2.1.213@sha256:7654e9ac971c57844a77a9aa1a48bf1d2c0cc1adaa19456f4bbb8f5e97c102a7
  - name: cp.icr.io/cp/wiotp/historian-configuration-manager:8.0.15@sha256:f9e63ccac08fd3af90073b593445b19cf8e9dec9a2eff40002c1305a1c95e946
  - name: cp.icr.io/cp/wiotp/historian-connector:9.0.16@sha256:b6e2be20b6129c0af5f030e6e1fc7b5017dbddd4a4090773b6a1d7facf87fe12
  - name: cp.icr.io/cp/wiotp/ibm-iot-actions:3.0.46@sha256:3f751831349f3c7c70901431d9d65a36dddb2af16bdf250eaba6b1dc1c6d8c9c
  - name: cp.icr.io/cp/wiotp/ibm-iot-auth:8.0.55@sha256:467b65005a2cbc252f9e67a4cd3203ad54722e50e4c9687779c14ee62eac2c96
  - name: cp.icr.io/cp/wiotp/ibm-iot-datapower:7.5.135@sha256:f9b2265a83dd5bdcbbae2ef133996c44a62bb9e56e8b05120ffacf51896521cd
  - name: cp.icr.io/cp/wiotp/ibm-iot-devops:11.0.47@sha256:c88c613f1a8cea9477e05e96d49497f8d5f7c193c43dbbbab0905a191f5f7484
  - name: cp.icr.io/cp/wiotp/ibm-iot-dm:3.0.52@sha256:f9a99d6e4f5ada9732b67393ef86190f01fd17b9c163fc271c718fd2d33407d5
  - name: cp.icr.io/cp/wiotp/ibm-iot-dsc:7.0.58@sha256:64b1cdc6ca245cfd25fe85c73b2a994dca5e2d33f833177f8d62a9526fbf09e6
  - name: cp.icr.io/cp/wiotp/ibm-iot-fpl:2.0.47@sha256:c6afd9140eb1d7e47e2e4aad985803a2ab9d0a3e2114f898345242e677c42277
  - name: cp.icr.io/cp/wiotp/ibm-iot-guardian:5.0.43@sha256:dd47873dbc95c71d24f59cab64a795620b360cf7671940c83ef0622d27ae1000
  - name: cp.icr.io/cp/wiotp/ibm-iot-mbgx:5.0.51@sha256:a2ce26b2013125cf9854058fa6c8142eabdc384f4c985327b886a48be95bbc5a
  - name: cp.icr.io/cp/wiotp/ibm-iot-mfgx:7.0.45@sha256:0c3d0f31b164d190db4a64647939a2065c953508fe5d27c489baf03cd4abcb7b
  - name: cp.icr.io/cp/wiotp/ibm-iot-monitor:3.0.47@sha256:bfcda866f41f26d05e06668891ddb762313fa6c447f616183cee63cf178d7246
  - name: cp.icr.io/cp/wiotp/ibm-iot-orgmgmt:7.0.54@sha256:16afc7b96f03f4e46d02d86234649b13e65a22799d2056a4959332b5bb4c27ed
  - name: cp.icr.io/cp/wiotp/ibm-iot-provision:11.0.48@sha256:24e6b07450d038ca47afd1dc15ec87d0adc466a1910474efc50633c8ee70d28e
  - name: cp.icr.io/cp/wiotp/ibm-iot-registry:9.1.33@sha256:02af4346d0fdbc7c2ae127e0361723c50ada10203cdc6e2278030e2237c23fc7
  - name: cp.icr.io/cp/wiotp/ibm-iot-state:6.0.57@sha256:3cae67f5565538d18b8f11193fe3644999eedd0f53dea8748e1895af5159e62e
  - name: cp.icr.io/cp/wiotp/ibm-iot-webui:7.0.51@sha256:bb4a302ff9c2ea4b582f9803798bed555a45248d8c46aab0a7476466ba9faf4c
  - name: cp.icr.io/cp/wiotp/ibm-iot-workspace:2.7.111@sha256:491c97b523d5d7e314baa523727ae96d2f9169f1f29b7553856cc3ac6a66802e
  - name: cp.icr.io/cp/wiotp/masuseragent:1.5.166@sha256:7ffe672d27f5891784f58e8f5f728f0c98ca777159cbbd45019ba58f0f564555
  - name: cp.icr.io/cp/wiotp/messagegateway-server-configurator:1.6.134@sha256:a31bef8e0a15a6da0a4ee419d0822229124de818cea22926f6b8c4c108a6ac67
  - name: cp.icr.io/cp/wiotp/messagegateway-server:1.6.134@sha256:849dc4cb2dc7a4647a8d38283b7d45c9d3f79c58f568ccdd60496b266607c136
  - name: cp.icr.io/cp/wiotp/messagesight-configurator:5.16.120@sha256:d16774a2898170a1d3e4fa7f2a24c23aa26431d095a0911c3ebc0f0e67f6ade4
  - name: cp.icr.io/cp/wiotp/messagesight:5.16.120@sha256:8f8c47b364c124c0c790479ab1e1c28c5d0d500718ab03d55641e3b1d294d85b
  - name: cp.icr.io/cp/wiotp/monagent-iot:2.3.128@sha256:1e600eac76f575ddd2a3a2e3bffd980d4a983d1f92697c128a59daff57d56d16
  - name: cp.icr.io/cp/wiotp/monagent-msserver:4.3.228@sha256:d78c102af06d84f6f90409c0ab565df297558f1dbfa3069abee72ffece360aa8
  - name: cp.icr.io/cp/wiotp/monagent-org:2.1.236@sha256:a3184bd8156e7d3244dccfe8620e95553384b994c42c9940d618fa1cc89dcf5d
  - name: cp.icr.io/cp/wiotp/mongomodel-actions:1.2.168@sha256:24ad44acffcb2ac247efab266bab5384bcfd2680887506af013ac1b60a4f8556
  - name: cp.icr.io/cp/wiotp/mongomodel-dm:1.3.172@sha256:16d1557b772360bb0fd43c0fe069785101a52e59976a8f828fd260c536c5cb20
  - name: cp.icr.io/cp/wiotp/mongomodel-dsc:1.2.172@sha256:3b0157bc0d87cb79ce8318f19103d2e939faf42d1e8b7ff86eb27b444ac0c398
  - name: cp.icr.io/cp/wiotp/mongomodel-guardian:1.3.169@sha256:9c35e6980e3add2f5a831cd90292c8b6127489423a9adb43cf63a9d16534057f
  - name: cp.icr.io/cp/wiotp/mongomodel-orgmgmt:2.0.166@sha256:fa90d6940c75ce10ff966235a260d58d0bf9f8931a52679d19e126884ada778e
  - name: cp.icr.io/cp/wiotp/mongomodel-provision:2.5.157@sha256:ea4de9a82d5e732c7b45168fce4fc73186b8b6b0e4bdac6d5f9fba37a67274a9
  - name: cp.icr.io/cp/wiotp/mongomodel-registry:2.0.163@sha256:89bf98d73365c6c24062a0b31a124025f30623a063a92726362b0f541fa320dc
  - name: cp.icr.io/cp/wiotp/mongomodel-state:1.2.164@sha256:3d518d57feb2bb070d39edd98c5b15087b5358d1e48bf21674aa9fb9ef258e2f
  - name: cp.icr.io/cp/wiotp/mongomodel-webui:2.3.172@sha256:86c4b7adc02cb9eb62193374863cd944c4a61c0380c8f6967c871a36afe9b987
  - name: cp.icr.io/cp/wiotp/mqtt-connector:3.0.76@sha256:8a30ed3c4f24d172939fcc970aa581bfe53fbd64c0fa4bbf484deaf20273dc85
  - name: cp.icr.io/cp/wiotp/msproxy-monitor:9.0.98@sha256:cb25316bc31cdf23aa955d0f28cfe16042de60cf2890355c3d7624e62cb5deb8
  - name: cp.icr.io/cp/wiotp/msproxy:9.0.98@sha256:9ecb77472f9f8f18ee1e9029224cc3221e518fb67fef32d80aed1d35a4877135
  - name: cp.icr.io/cp/wiotp/org-store:5.0.75@sha256:88398c94200e8d5887168aeeba4a517b1a6877690f9f18d1c5bae51b2165b4ee
  - name: cp.icr.io/cp/wiotp/orgdeprovmgr:2.2.190@sha256:cec453a45f9c35526e24283878f68c99c548bff26e9c71e7ceee6612fe8489a3
  - name: cp.icr.io/cp/wiotp/orgpoolmgr:3.1.248@sha256:6557006088481d47466fac531a9c80a65a2ade1c331308014be5cc0f7f067a88
  - name: cp.icr.io/cp/wiotp/orgprovmgr:2.1.187@sha256:adfc52145c82902437aa1af8dfc37239455824ae014b458a5cc6cb5a09c65476
  - name: cp.icr.io/cp/wiotp/pipelinerouter:2.0.60@sha256:4759e89354dcd885a2b1596102ba840e27bb1bdde8ad09e344f42caa422b3ac2
  - name: cp.icr.io/cp/wiotp/provagent-guardian:2.1.180@sha256:6f4b159f92741e5c417a5c51d99ccceb7cc41f2d33baac2021055934d277b035
  - name: cp.icr.io/cp/wiotp/s2s-store:7.0.30@sha256:9cd99cf439430a47c470fdf233b1489a06f36f84619fb64046b87c94fc44304f
  - name: cp.icr.io/cp/wiotp/sqlmodel-auth:1.1.125@sha256:6c83476ccd0dfa1a9f4c41c49591ec7514f9ae2be8076726fe4b728863235ced
  - name: cp.icr.io/cp/wiotp/sqlmodel-fpl:1.1.92@sha256:e693bd1ed1c2c6ccac0e00fbb3ec9bdd5f963214e3d436e2aa8b9815d0d181c2
  - name: cp.icr.io/cp/wiotp/sqlmodel-state:1.0.167@sha256:01b455e043416af462b5979c8da01318c7b07b8db76b1df1bc5799bde74bbec6
  - name: cp.icr.io/cp/wiotp/state-updater:3.0.37@sha256:3245438fb2e4daa75be6eae36184c279f670b9aff33ab08ea4f9195ff6eb661e
  - name: cp.icr.io/cp/wiotp/statsd:1.3.191@sha256:00845693aafd1345048163525bfd0c055ec75594f95162f084f7154982926647
  - name: cp.icr.io/cp/wiotp/ui-dashboard:7.4.80@sha256:511b632ca147f4e492ed8b06143cff82aea9feca8538fab57874f0873318f897
  - name: icr.io/cpopen/ibm-mas-iot-operator-bundle:8.8.26@sha256:d3f4a5d909ffbb2f82b46f18dbfbd5fbc0b69b66fe8e6ddc54d04149269f6b67
  - name: icr.io/cpopen/ibm-mas-iot:8.8.26@sha256:260579dadfdb8ac99dddc6a03bac8074a9a02df63feb1ab9f80a948215a142f9
  - name: icr.io/cpopen/ibm-mas/edgedatacollector:2.5.1@sha256:1c42afdcf6b691fd6f3d81bcc0902aafc793a3549781886d4a5b273b29ac5435
