kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-sfg/sfg-as4service:6.2.2.0_1@sha256:2b32a39461ed2b6fb331e7bf9054876989e7bb8ffeb7f09109cb89338a34127e
  - name: cp.icr.io/cp/ibm-sfg/sfg-customization:6.2.2.0_1@sha256:b83c5612f9080e23aecba507aed8bf5d6ac1c77d34f6d2fd17f7caeda752e1de
  - name: cp.icr.io/cp/ibm-sfg/sfg-dbsetup:6.2.2.0_1@sha256:318ca5f3af865c23b88b6c5622302ec84f24b8934faf8c0ed359952725c16464
  - name: cp.icr.io/cp/ibm-sfg/sfg-documentservice:6.2.2.0_1@sha256:3c970db71404ce5e9b21e822f9774089bb6831891fca93543489dcabf577d019
  - name: cp.icr.io/cp/ibm-sfg/sfg-identityservice:1.0.0.1@sha256:6c59efb98a4913f38b7de0bd75b2a8dbea5da7537a2b8ce964fb4df1e14fe504
  - name: cp.icr.io/cp/ibm-sfg/sfg-ps:6.2.2.0_1@sha256:0205cb7c7bb54de252ca76d1a09d254e0dcaf2ab8339ca864dda355b28a6860f
  - name: cp.icr.io/cp/ibm-sfg/sfg-purge:6.2.2.0_1@sha256:5b421aace31528863bbc1b949c685a7fd2748df9c302ff80e8e2c15d8a513382
  - name: cp.icr.io/cp/ibm-sfg/sfg-resources:6.2.2.0_1@sha256:fb94d20dbe721771e60c14b0862e10ad48540d275abe6ed86e985a047411b1c2
  - name: cp.icr.io/cp/ibm-sfg/sfg:6.2.2.0_1@sha256:c9b4c7e4457bc7d3b5c821ab601d6eb8df5b0c08b26451a6c36c8dcc3eab5996
  - name: cp.icr.io/cp/opencontent-common-utils:1.1.69@sha256:122ba7c754148d1a95a45a4a531fdf0a7ac90066cc965b8495d2301b93de96ab
