kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: icr.io/cpopen/ibm-cpd-mongodb-operator-bundle:1859@sha256:7c7f055db57dd048abe6fdf1190661c84eb48e99f94d07568966e97367df8959
  - name: icr.io/cpopen/ibm-cpd-mongodb-operator-catalog:1859@sha256:b1b297bc755154f93a377e16d67979e27d67fc03695c429f707630dc57bcb5d3
  - name: icr.io/cpopen/ibm-cpd-mongodb-operator:1859@sha256:3c0d332245d1ab59a277be842af24b15ebabfc66157eebca9391f0c2575c4a73
