kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cp4a/odm/dbserver:9.0.0.1-IF020@sha256:e9eb64fa58835b9210d93ae5438b4699a842826544b5bed33fb93ccd9ef82ec3
  - name: cp.icr.io/cp/cp4a/odm/odm-decisioncenter:9.0.0.1-IF020@sha256:0ca3e3ace20566bba76737b2778b26e9a725e4196fda86ed8c72d921e103c4bf
  - name: cp.icr.io/cp/cp4a/odm/odm-decisionrunner:9.0.0.1-IF020@sha256:58d0b6bb70fc83075d2e49cb91828395a9b54b08d8297448925a52839101955f
  - name: cp.icr.io/cp/cp4a/odm/odm-decisionserverconsole:9.0.0.1-IF020@sha256:5ba22668a50caa01d063a1f5ed2e74f7ee8c910463bf85453ac4ba29a1119a17
  - name: cp.icr.io/cp/cp4a/odm/odm-decisionserverruntime:9.0.0.1-IF020@sha256:8e5cde784714c714aa65bff081f4d456c20cba38f1e5ce1a1632c5739579a861
