kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/mas/ltpakeys-generator:3.3.25-amd64@sha256:317a4edd084825b3c927506640e929e4d5127ca95ce2ed7bf6fc84a5b2630e05
  - name: cp.icr.io/cp/omnio/djangomodel-edgeconfig:0.6.59@sha256:51542f515ea2e0215b3454c3cd7a75035e439c4a0e607ac08de09a059bcb815d
  - name: cp.icr.io/cp/omnio/ibm-iot-edgeconfig:1.2.56@sha256:d6e7757300fa99c6fe138f6c2412af57b5334998799b6413d0264889c28a8da3
  - name: cp.icr.io/cp/omnio/omnio-configuration-ui:0.6.62@sha256:7cdc3978c7ac70cdd136ac4f422da1f73951147643565ed53984eafa7c7e37a0
  - name: cp.icr.io/cp/omnio/omnio-server:0.6.59@sha256:0efbc43940b306a4bfbeb3ec7ece46de74fa5dd40ad8c73c5cd688781084cd08
  - name: cp.icr.io/cp/omnio/sqlmodel-edgeconfig:0.6.59@sha256:bc6d3b188c9d7892e89d7b6d6c3e393323a947bf93c1ced582f648c315dfb18f
  - name: cp.icr.io/cp/wiotp/action-mgr:3.0.89@sha256:b42e8d5ae5d70abf594e9443e2a2216c5a413e01442cf647ed12d6082024feea
  - name: cp.icr.io/cp/wiotp/api-actions:3.0.27@sha256:c791cd8551e78b666ab07c611f9d2756589c3604836f8a44deeb366610be12db
  - name: cp.icr.io/cp/wiotp/api-authentication:4.0.31@sha256:6b31383d96cf011b6c8322136ed2369c65bbb4fbf6640c9d17f1ab908afed103
  - name: cp.icr.io/cp/wiotp/api-authorization:7.0.26@sha256:d9112b062ab5ec8c0fc9504e9e194d88cce1fcbba38540f2115c2ea49bc33729
  - name: cp.icr.io/cp/wiotp/api-connectors:5.0.22@sha256:4c93de23a1aba718200a813715dc4a6450598a12c93caa007bcfed3204b1544d
  - name: cp.icr.io/cp/wiotp/api-dashboard:4.0.90@sha256:5c01d14ec0482b9f8b856802ac56c97c4e4f6cdc0a451c9e212bf00a89ab3475
  - name: cp.icr.io/cp/wiotp/api-devicemgmt:4.0.21@sha256:ea4ac0b49aad18a8305a92408cd14d51d65fbf8624134156829db080b0f549da
  - name: cp.icr.io/cp/wiotp/api-devops:4.0.21@sha256:d2b45f9b1600901654a4a5e150c4022f7af3914954a2d00b18779fa698f35222
  - name: cp.icr.io/cp/wiotp/api-importconnectors:3.0.38@sha256:8ab2ee173f4a619fea27264471d4bd49bdb0ad26f944315b777a8bdb69888321
  - name: cp.icr.io/cp/wiotp/api-mbgadmin:3.0.81@sha256:6948cbace09abacb82e16140e87f92b4e307d591b260807fc55493e7a1a07f7f
  - name: cp.icr.io/cp/wiotp/api-messagesight:4.0.20@sha256:913d390d9ec3a35ee77c784ba32075b6d31df4b895e797864c29a712b3f0695a
  - name: cp.icr.io/cp/wiotp/api-org:9.0.20@sha256:e400910f0435a56501f95999a22cdbfb320f53cb78833fddcf183fdf93987d4e
  - name: cp.icr.io/cp/wiotp/api-organizations:11.0.23@sha256:5b90b1b441d943bebb02c155b5aad1a4435e4a471c42739efbcd7fd0916ffc45
  - name: cp.icr.io/cp/wiotp/api-pipeline:2.0.64@sha256:c944efec09a56c800ba68389741531d3fa14c0109d167cec1aee14a1bee1efc9
  - name: cp.icr.io/cp/wiotp/api-resourcecontroller:4.0.77@sha256:586ff916afb0e6203f6fe228869808a11c370cd402ea52bf5a74e1658d7d4ce0
  - name: cp.icr.io/cp/wiotp/api-riskmgmt-secguardian:6.0.27@sha256:e8dfc755fecc5effeffc97a5fa17256f850501f9fe40f92912336dc249850085
  - name: cp.icr.io/cp/wiotp/api-s2s:11.0.23@sha256:9312b2006547a7af61b99f585c1f1900be264f560f994ad8a55338e88b75d7c8
  - name: cp.icr.io/cp/wiotp/api-schemas:5.0.22@sha256:f7cc6691fac1bd1bfd8b2e5710af8595914882b89b0bb3d740343b58877d46e9
  - name: cp.icr.io/cp/wiotp/api-state:6.0.25@sha256:81f2bcea13b891e236480d844eb037139b20af6a5caa4d12a1e42f0963a1ccfd
  - name: cp.icr.io/cp/wiotp/api-status:3.4.190@sha256:6b8bfabd5346a1a85140f2c3a7115e364efb692bb9b9fe34363e8444a35d28d8
  - name: cp.icr.io/cp/wiotp/auth-store:3.0.44@sha256:c5eaef7b9ba3fc02d2f77517342b5d5d9d708692273fa25b1bcbd6e395483363
  - name: cp.icr.io/cp/wiotp/config-store:5.0.35@sha256:b059b076106f08397c4e3ea3307790aa0bbf377590953b25d82286a2eb8d77d5
  - name: cp.icr.io/cp/wiotp/connectors-store:9.0.21@sha256:7eabff57fa2aed5ab36766706d50d473642b735cb5c9885d50ca858b88cfa08a
  - name: cp.icr.io/cp/wiotp/data-import-connector:3.0.89@sha256:01e077c41a41a8aaa8a0993f37c40cbbf8e1860d6114fe8e4274714e00dbe60c
  - name: cp.icr.io/cp/wiotp/datapower-config:10.4.25@sha256:7cab6fc01a9ee5a2f8d9ebe6ae1fc4f660cf2860a5d46f1fc9e50aa9b6ee9335
  - name: cp.icr.io/cp/wiotp/datapower:7.5.138@sha256:a425640752461d9877166e0c892760080c4d93290b67217f3e2c465f34b81a6d
  - name: cp.icr.io/cp/wiotp/deprovagent-actions:1.1.178@sha256:5ff2a3ccf934b7db80737ecf8ef7ab4909bce36a730900f3b884b9817dd1a787
  - name: cp.icr.io/cp/wiotp/deprovagent-auth:2.3.179@sha256:37bf1a80329b0b1438a9e554aa18a635baaecb720dbce8137a6432fddedaf647
  - name: cp.icr.io/cp/wiotp/deprovagent-dm:2.1.174@sha256:e520eaa773fa275cd57e874f684af125897178832266c768fa737f829f7cf30c
  - name: cp.icr.io/cp/wiotp/deprovagent-fpl:1.0.129@sha256:ca1e2aee370c55e46846c89723a27d3e788cb43cb55dcb600e25464804a8d0b1
  - name: cp.icr.io/cp/wiotp/deprovagent-guardian:3.1.174@sha256:4789ccb03d3aa20ea77691a70b14336a7a0e475a54c1827562911930e5be5ea7
  - name: cp.icr.io/cp/wiotp/deprovagent-orgmgmt:2.1.177@sha256:349545cb92adf2d474960798a07886b5a7d953eb520ed1a9d9b33c5e5e775234
  - name: cp.icr.io/cp/wiotp/deprovagent-provision:4.4.172@sha256:83758b945db771c5b812d12b3e409e1dfd841205da4b09e7d0c5d236a1d54e0d
  - name: cp.icr.io/cp/wiotp/deprovagent-registry:2.2.169@sha256:4aa1a6ecef73e0d9ee3d698b22ec449c4b9c47ae5c3e694680d8a641b430528c
  - name: cp.icr.io/cp/wiotp/deprovagent-state:1.2.176@sha256:72cf5b33776712bf5bc025369a82e5573d83f626233c13c52da115f61119dfff
  - name: cp.icr.io/cp/wiotp/deprovagent-webui:1.2.177@sha256:4e33a82b90acd81ac4fc2c3da85cb79d8e98697b96f5f584b53ca5f9f14027b9
  - name: cp.icr.io/cp/wiotp/device-store:3.0.26@sha256:75626f81f04977d5ec961f16a44be34f32f20ed2a850d98a2feedf7bfce058cb
  - name: cp.icr.io/cp/wiotp/devicemgmt-server:4.0.26@sha256:b527a203b1f82abbe65ef22039c74195bbd436732a39e1c609c7571a39783725
  - name: cp.icr.io/cp/wiotp/entity-connector:2.0.87@sha256:c519099e782beeb6a6b5acb2c99a8e4c03ca3bf696b93635caebb7dec7fb1225
  - name: cp.icr.io/cp/wiotp/entity-manager:3.0.89@sha256:48d1d8f2768d797fc34f7cd891a4b149eed69f582a86df1dd1ba65b1afe3a42f
  - name: cp.icr.io/cp/wiotp/functionsexecutor:2.0.53@sha256:6b30577b11d1676d606f82835957ac9a646f488373c0aeac0defb07d1199d877
  - name: cp.icr.io/cp/wiotp/graphite-exporter:2.1.214@sha256:70721b4ec75f8bbcb299019ba1b8acacac791abd8fd60eaa6d8ef65376f1783a
  - name: cp.icr.io/cp/wiotp/historian-configuration-manager:8.0.16@sha256:1fff0030b483b3c9c737d4bec77c0eb74f54076f5e173d7aff06f75c403a82d3
  - name: cp.icr.io/cp/wiotp/historian-connector:9.0.17@sha256:232201c7e8b53c079753ec1e7bd9e4e4e03e37ed23d4d00acb99f4dfcf4a41a0
  - name: cp.icr.io/cp/wiotp/ibm-iot-actions:3.0.47@sha256:ae1855bb2649007505fdeed3298e8943753ec71fb98f261faee3db144d6a8991
  - name: cp.icr.io/cp/wiotp/ibm-iot-auth:8.0.57@sha256:01e448b4c9a5bc5262de2b7fbffd63d48d50f0d632539d32c4a5a0bab1c930d8
  - name: cp.icr.io/cp/wiotp/ibm-iot-datapower:7.5.138@sha256:d4fac0f7cee563d338a251a66495f7d08c21bf8a13d8ee9f9023ba9a0a7aee28
  - name: cp.icr.io/cp/wiotp/ibm-iot-devops:11.0.48@sha256:714d379bf5bc66e340c8d9c5136fc217738de84c3e542e17236ec6e9e0ac5854
  - name: cp.icr.io/cp/wiotp/ibm-iot-dm:3.0.53@sha256:efcf3e73e012d20e14342243ad2cd334dd006565ee9592e3df9ebf6cdd28d0ec
  - name: cp.icr.io/cp/wiotp/ibm-iot-dsc:7.0.59@sha256:21a1ceafe3f442d6a0737bc7801540c70dcd92838310ecbe2443eef12282c3e5
  - name: cp.icr.io/cp/wiotp/ibm-iot-fpl:2.0.48@sha256:8f272cd18bd7bb95735db02689ecf78cb5f3098dded2191b8a1497f42df20ab7
  - name: cp.icr.io/cp/wiotp/ibm-iot-guardian:5.0.44@sha256:df1d4c3bcf2d26ce415418439d4aab745be3858b0f9afe9fc68f1f3ead2ed098
  - name: cp.icr.io/cp/wiotp/ibm-iot-mbgx:5.0.52@sha256:c592c9271370bbdbdf9747dc637aa2e3c732162cc9586221a67e27f8a78a354e
  - name: cp.icr.io/cp/wiotp/ibm-iot-mfgx:7.0.46@sha256:958ed5feaa30992983180ab673962f4e16bf2776c212d2cf406e9704c1e095f6
  - name: cp.icr.io/cp/wiotp/ibm-iot-monitor:3.0.48@sha256:f4792ec71c817660170c4fa69ef1363b19c1547d587031f47c5f751a621ef9ee
  - name: cp.icr.io/cp/wiotp/ibm-iot-orgmgmt:7.0.56@sha256:1c8fe8005ee8a1caea854674a9206f6be8365d3383c465e9d3821db43941bc46
  - name: cp.icr.io/cp/wiotp/ibm-iot-provision:11.0.49@sha256:b6603663ad4a118ed6c9ac05a06b17c1ddf510278083169d482265eec6a88714
  - name: cp.icr.io/cp/wiotp/ibm-iot-registry:9.1.34@sha256:89510562859fe042a9d3b530113962016a224d0a7021460de211e6250186bd18
  - name: cp.icr.io/cp/wiotp/ibm-iot-state:6.0.59@sha256:79eb7a1c54a41891411b1e8831266358633bd0d7a2417820f3a4a16abb6969fa
  - name: cp.icr.io/cp/wiotp/ibm-iot-webui:7.0.52@sha256:deba17b21895fab4b4dd7067705497e8a294828a95b660d45d6f708356999513
  - name: cp.icr.io/cp/wiotp/ibm-iot-workspace:2.7.114@sha256:354f3497dec9560e31603250aef312148e66bacf2480b7fff38eb8b31f73c49d
  - name: cp.icr.io/cp/wiotp/masuseragent:1.5.169@sha256:6bb214823f0661d89a9ab2455badb95f33c7e1524cc6ad7bd7bb25080cfaa741
  - name: cp.icr.io/cp/wiotp/messagegateway-server-configurator:1.6.137@sha256:f177e2089ed9f504208676d38532d9cd082cdd978b2842c3a581f31a78d566cb
  - name: cp.icr.io/cp/wiotp/messagegateway-server:1.6.137@sha256:66d77e12c11403212b4ac1e19a4edd6461b70b9d9f0868aa54211f68068a7708
  - name: cp.icr.io/cp/wiotp/messagesight-configurator:5.16.124@sha256:bf08d79c6b9142d1310d825ba862eb7b1aa4eb2ce472e24e62a5dd31d40bc8b7
  - name: cp.icr.io/cp/wiotp/messagesight:5.16.124@sha256:9ed2763dfb48f4c2be0bb1fb04aee10954a86e70a6bd36761fab579be77c4f28
  - name: cp.icr.io/cp/wiotp/monagent-iot:2.3.132@sha256:64317d261552c4265f9fc31a8c8a0237724c9f3eb44ecbfe6fcb261b2e8b64ae
  - name: cp.icr.io/cp/wiotp/monagent-msserver:4.3.230@sha256:63c2745285d47a7937c556ac079052af22977470bd20929ddef9429c3b3cd14e
  - name: cp.icr.io/cp/wiotp/monagent-org:2.1.240@sha256:088efaa4d1626e6db8a6ed7fa3c7e2aa08e505d2d0abb4f885bcdb66c9fde15c
  - name: cp.icr.io/cp/wiotp/mongomodel-actions:1.2.170@sha256:6bff46f589cec547075c65bbbe10eaa5445321bf3f097b2a732b4e6b458c4201
  - name: cp.icr.io/cp/wiotp/mongomodel-dm:1.3.174@sha256:2dedbb6b6028ed2f235f695b652aaa804f4c4792da0eda2f2a2a96c90f29b3e3
  - name: cp.icr.io/cp/wiotp/mongomodel-dsc:1.2.174@sha256:f3f0097574b1b49f60204264914dae75d8b5572232330d323ab453763e5418a4
  - name: cp.icr.io/cp/wiotp/mongomodel-guardian:1.3.171@sha256:31b4ac596140845e9934c27c0522868e498e703e67aa7cc50e2193b62f9bbc69
  - name: cp.icr.io/cp/wiotp/mongomodel-orgmgmt:2.0.168@sha256:1ccadd0b5844b58661e5a5f8206093b8f6b34552f9255a85f97e8bc4089f332e
  - name: cp.icr.io/cp/wiotp/mongomodel-provision:2.5.159@sha256:5c6c2bf1c7741ccad4ab4cd28fe19e06b1a18780cf3df7bd5c07805ac4c672b1
  - name: cp.icr.io/cp/wiotp/mongomodel-registry:2.0.165@sha256:959b6e0bbeebc61bff1659c8e3a91179e011e408ba6405612a83d0ed27a7690b
  - name: cp.icr.io/cp/wiotp/mongomodel-state:1.2.165@sha256:dfeba2266ff99c51573e53046c17bb33725cbc994c0e55f21a8e3b7bc1186511
  - name: cp.icr.io/cp/wiotp/mongomodel-webui:2.3.174@sha256:634de422ecd5f4d22deaf55d3d1b4a570384e3ef86988ccb601833737833438d
  - name: cp.icr.io/cp/wiotp/mqtt-connector:3.0.78@sha256:7b4774735d97b06f52eb811ba8497023f00f9a3c807c1fb52fee89e16f1354ed
  - name: cp.icr.io/cp/wiotp/msproxy-monitor:9.0.102@sha256:ab652df688bd9ff79e4ade3f200ab0ece03340988cf463c15809b76a48ad6bbe
  - name: cp.icr.io/cp/wiotp/msproxy:9.0.102@sha256:18d89fb0e027a89cf23cb0773d8ca36c0541fbebdd144571d1130de5457061c6
  - name: cp.icr.io/cp/wiotp/org-store:5.0.76@sha256:12ede40288bf336fccb3372dc69fc40242207cb24be27bdc1939f49d50055950
  - name: cp.icr.io/cp/wiotp/orgdeprovmgr:2.2.192@sha256:f18d492ed88b2814687ec421be82a745db5e4b97e17aba6e7a1465e34d969a6d
  - name: cp.icr.io/cp/wiotp/orgpoolmgr:3.1.250@sha256:2bf0755aa13dcf5b1cf6b79ece1f177e41371133cf613d108212559cf4c61fef
  - name: cp.icr.io/cp/wiotp/orgprovmgr:2.1.189@sha256:93c0642610238cdadb7001cdf7fe1b36920d2724104f006a1e24786b462b2b63
  - name: cp.icr.io/cp/wiotp/pipelinerouter:2.0.63@sha256:988f365848ebe10a140c041107bc812ad47ff59a7e31c2de2ee3242c05ac1d52
  - name: cp.icr.io/cp/wiotp/provagent-guardian:2.1.180@sha256:6f4b159f92741e5c417a5c51d99ccceb7cc41f2d33baac2021055934d277b035
  - name: cp.icr.io/cp/wiotp/s2s-store:7.0.31@sha256:c0df61950d83ba662f7693259dcdbe9530b4e731ee5969444158b1fc784a09b5
  - name: cp.icr.io/cp/wiotp/sqlmodel-auth:1.1.125@sha256:6c83476ccd0dfa1a9f4c41c49591ec7514f9ae2be8076726fe4b728863235ced
  - name: cp.icr.io/cp/wiotp/sqlmodel-fpl:1.1.92@sha256:e693bd1ed1c2c6ccac0e00fbb3ec9bdd5f963214e3d436e2aa8b9815d0d181c2
  - name: cp.icr.io/cp/wiotp/sqlmodel-state:1.0.167@sha256:01b455e043416af462b5979c8da01318c7b07b8db76b1df1bc5799bde74bbec6
  - name: cp.icr.io/cp/wiotp/state-updater:3.0.38@sha256:2e76639137d50cb049a4523e06e18cf4089f0e5707ca2998d66101ddc0616812
  - name: cp.icr.io/cp/wiotp/statsd:1.3.191@sha256:00845693aafd1345048163525bfd0c055ec75594f95162f084f7154982926647
  - name: cp.icr.io/cp/wiotp/ui-dashboard:7.4.81@sha256:05ab6b129ba6e670e3fa7689683729f09e1f78e5a2514755b1fb323fa9118b8a
  - name: icr.io/cpopen/ibm-mas-iot-operator-bundle:8.8.27@sha256:53fd3ae7452004780347ea17b6db97c8cb30bf80a22ecbc5d2afca820f1c0973
  - name: icr.io/cpopen/ibm-mas-iot:8.8.27@sha256:6651166287c9234894c2801ed17da314f0b82d103aeeb214357c52b1af3ea538
  - name: icr.io/cpopen/ibm-mas/edgedatacollector:2.5.1@sha256:1c42afdcf6b691fd6f3d81bcc0902aafc793a3549781886d4a5b273b29ac5435
