kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/ibm-wca-z-code-explanation-model-00000:2.8.10@sha256:eca4f28886cc694cd44007a32f1aa1baada9a3d00de50cda732c760508c03c5c
  - name: cp.icr.io/cp/cpd/ibm-wca-z-code-explanation-model-00001:2.8.10@sha256:e1e321c418c22a5cc800ad475691eeff482c16b28e6c0fdbdd430c9c9096f23d
  - name: cp.icr.io/cp/cpd/ibm-wca-z-code-explanation-model-00002:2.8.10@sha256:b30e15b93a29f72e79ee90d2746cb2425895896026ecfb65cc09e4c9fe453c4e
  - name: cp.icr.io/cp/cpd/ibm-wca-z-code-explanation-model-00003:2.8.10@sha256:c2874620d4be4629e16af5435359d8aa3b057fccd5883d4896f73f857652477e
  - name: cp.icr.io/cp/cpd/ibm-wca-z-code-explanation-model-00004:2.8.10@sha256:9c9fe6f41ca0c8264ec14ab174d20a8b291ba827ae0d1cb24e652f1642602b0c
  - name: cp.icr.io/cp/cpd/ibm-wca-z-code-explanation:2.8.10@sha256:67567c037ebbe1d648e8af49aac3a327428bec58185ff2c12c231463b4df3c2f
  - name: cp.icr.io/cp/cpd/ibm-wca-z-model-gateway:1.0.140@sha256:ba6ea04609bac3d8882d7ab83d821b3518b7613a2199d97bc694710f2aec70fc
  - name: icr.io/cpopen/ibm-wca-z-code-explanation-catalog:2.8.10@sha256:df58dcb4dc79e2f60989f2c1996a09e3254624d813108122c1e87d028bc4a542
  - name: icr.io/cpopen/ibm-wca-z-code-explanation-operator-bundle:2.8.10@sha256:365aca3b72f5267988aaf41a36ac4a95418bb8db7bf6b5bae1dbbd3021de52e2
  - name: icr.io/cpopen/ibm-wca-z-code-explanation-operator:2.8.10@sha256:ae2d5b56196c51639cfa2a8ae85c4be57523d3f0fc857980fcd63cd794cbf7ea
