kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-cdws/cdws:6.3.0.17_iFix00-2026-02-06@sha256:fa541ced3b8ff9af8b5aeeaaa277ca5c0b3270236345eba2141cb34e621bbfd3
