kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/edb-postgres-license-provider:2705@sha256:f0e427cefc7cdb09cc63af1dc5d4e8f55c264eec111ffd193b6ee701370e1970
  - name: icr.io/cpopen/edb/postgresql:13.23-5.31.0@sha256:353d13d874d60f7dff5dba2b080e8b127d54f3d71f9c5421f3895d737a604d41
  - name: icr.io/cpopen/edb/postgresql:14.20-5.31.0@sha256:5b9e17fa0f210e78622e965d4da7f79c20b99cf8db507451e5453dd4c3dab8b7
  - name: icr.io/cpopen/edb/postgresql:15.15-5.31.0@sha256:425de739fb88db833881eb0c1c9db7408059bec5b5f45830c92e5de4b4ebbddc
  - name: icr.io/cpopen/edb/postgresql:16.11-5.31.0@sha256:b711c28ad678c53fae114a3b80b801979dd30cf4b7f6676db0db5c9987e377d3
  - name: icr.io/cpopen/edb/postgresql:17.7-5.31.0@sha256:4becaff092407bf0c4a55b921c1ff8a9f2e4cb2b53c339eea41269ee38a21f12
  - name: icr.io/cpopen/edb/postgresql:18.1-5.31.0@sha256:022b2d0beb9ae959ddd7c06038a4369f935fc07edc9cd288bc019d81b6ef1a49
  - name: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-bundle:2713@sha256:8bfb39870221d966b4e6223924c548e384453627698152dad071465ef15491d9
  - name: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-catalog:2713@sha256:af4ac35100a8b93b36a9cb31c9cdf40fb190a0d78d29e4d5408b0d867a100a42
  - name: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator:1.25.5@sha256:913927a53944946b25eea43a973be0a4524ed6b9735f2173440327338c1cb9de
