source: ibm-streams-security/ibm_cloud_pak/manifest.yaml
description: IBM Streams Security Service
images:
  - image: wcp-ibm-streams-docker-local.artifactory.swg-devops.com/streams_build/streams-security-el7
