source: ibm-workload-automation-bundle/case/ibm-workload-automation/case.yaml
description: "IBM Workload Automation Container for Cloudpak"
images:
  - image: cp/ibm-workload-automation-agent-dynamic
  - image: cp/ibm-workload-automation-console
  - image: cp/ibm-workload-automation-operator
  - image: cp/ibm-workload-automation-server
