source: ibm-websphere-automation-bundle/case/ibm-websphere-automation/case.yaml
description: "IBM WebSphere Automation helps ensure the security and compliance of WebSphere environments by allowing administrators to easily see all of the unresolved security vulnerabilities that affect either the WebSphere Application Servers or the Java virtual machines in their purview."
images:
  - image: cp/ai/ibm-ai-wmltraining-controller
  - image: cp/ai/ibm-ai-wmltraining-init-sidecar
  - image: cp/ai/ibm-ai-wmltraining-proxy-controller
  - image: cp/ai/ibm-ai-wmltraining-sidecar
  - image: cp/ai/model-mesh
  - image: cp/ai/model-serving-runtime-adapter
  - image: cp/ai/msp-ml-server
  - image: cp/ai/seldonio-mlserver
  - image: cp/ai/triton-inference-server
  - image: cp/ai/wmlserving-controller
  - image: cp/iaf-ai-pipeline-ctrl
  - image: cp/iaf-ai-pipeline-step
  - image: cp/iaf-apicurio-registry
  - image: cp/iaf-elasticsearch
  - image: cp/iaf-elasticsearch-metrics-exporter
  - image: cp/iaf-elasticsearch-proxy
  - image: cp/iaf-eventprocessing-proxy
  - image: cp/iaf-flink
  - image: cp/iaf-health-service
  - image: cp/iaf-ui-customization
  - image: cp/opencontent-etcd-3
  - image: cp/websphere-automation-api-selfsecure
  - image: cp/websphere-automation-api-usagemetering
  - image: cp/websphere-automation-core-runbook-manager
  - image: cp/websphere-automation-core-runbook-runner
  - image: cp/websphere-automation-cve-monitor
  - image: cp/websphere-automation-healing-analysis-manager
  - image: cp/websphere-automation-healing-analysis-runner
  - image: cp/websphere-automation-healing-investigation-manager
  - image: cp/websphere-automation-healing-rest
  - image: cp/websphere-automation-healing-webhooks-rest
  - image: cp/websphere-automation-mongo
  - image: cp/websphere-automation-selfsecure-ui
  - image: cp/websphere-automation-server-registration-processor
  - image: cp/websphere-automation-ui
  - image: cp/websphere-automation-vulnerability-notifier
  - image: cp/websphere-automation-vulnerability-scanner
  - image: ibmcom/iaf-ai-operator
  - image: ibmcom/iaf-ai-operator-bundle
  - image: ibmcom/iaf-base-operator
  - image: ibmcom/iaf-base-operator-bundle
  - image: ibmcom/iaf-core-operator
  - image: ibmcom/iaf-core-operator-bundle
  - image: ibmcom/iaf-elastic-operator
  - image: ibmcom/iaf-elastic-operator-bundle
  - image: ibmcom/iaf-eventprocessing-operator
  - image: ibmcom/iaf-eventprocessing-operator-bundle
  - image: ibmcom/iaf-flink-operator
  - image: ibmcom/iaf-flink-operator-bundle
  - image: ibmcom/ibm-automation-foundation-core-catalog
  - image: ibmcom/ibm-common-service-catalog
  - image: ibmcom/ibm-cp-automation-foundation-catalog
  - image: icr.io/cpopen/iaf-ai-operator
  - image: icr.io/cpopen/iaf-ai-operator-bundle
  - image: icr.io/cpopen/iaf-base-operator
  - image: icr.io/cpopen/iaf-base-operator-bundle
  - image: icr.io/cpopen/iaf-core-operator
  - image: icr.io/cpopen/iaf-core-operator-bundle
  - image: icr.io/cpopen/iaf-elastic-operator
  - image: icr.io/cpopen/iaf-elastic-operator-bundle
  - image: icr.io/cpopen/iaf-eventprocessing-operator
  - image: icr.io/cpopen/iaf-eventprocessing-operator-bundle
  - image: icr.io/cpopen/iaf-flink-operator
  - image: icr.io/cpopen/iaf-flink-operator-bundle
  - image: icr.io/cpopen/ibm-ai-wmlserving-operator
  - image: icr.io/cpopen/ibm-ai-wmlserving-operator-bundle
  - image: icr.io/cpopen/ibm-ai-wmlserving-operator-catalog
  - image: icr.io/cpopen/ibm-ai-wmltraining-operator
  - image: icr.io/cpopen/ibm-ai-wmltraining-operator-bundle
  - image: icr.io/cpopen/ibm-ai-wmltraining-operator-catalog
  - image: icr.io/cpopen/ibm-automation-foundation-core-catalog
  - image: icr.io/cpopen/ibm-common-service-catalog
  - image: icr.io/cpopen/ibm-cp-automation-foundation-catalog
  - image: icr.io/cpopen/ibm-etcd-operator-bundle
  - image: icr.io/cpopen/ibm-etcd-operator-catalog
  - image: icr.io/cpopen/opencontent-etcd-operator
  - image: icr.io/cpopen/websphere-automation-operator
  - image: icr.io/cpopen/websphere-automation-operator-bundle
  - image: icr.io/cpopen/websphere-automation-operator-catalog
  - image: quay.io/opencloudio/alertmanager
  - image: quay.io/opencloudio/audit-garbage-collector
  - image: quay.io/opencloudio/audit-policy-controller
  - image: quay.io/opencloudio/audit-syslog-service
  - image: quay.io/opencloudio/collectd-exporter
  - image: quay.io/opencloudio/common-service-operator
  - image: quay.io/opencloudio/common-web-ui
  - image: quay.io/opencloudio/configmap-reload
  - image: quay.io/opencloudio/cp4d-tiller
  - image: quay.io/opencloudio/cs-mongodb-br
  - image: quay.io/opencloudio/dashboard-controller
  - image: quay.io/opencloudio/default-http-backend
  - image: quay.io/opencloudio/fluentd
  - image: quay.io/opencloudio/grafana
  - image: quay.io/opencloudio/grafana-ocpthanos-proxy
  - image: quay.io/opencloudio/iam-policy-administration
  - image: quay.io/opencloudio/iam-policy-controller
  - image: quay.io/opencloudio/iam-policy-decision
  - image: quay.io/opencloudio/ibm-auditlogging-operator
  - image: quay.io/opencloudio/ibm-auditlogging-operator-bundle
  - image: quay.io/opencloudio/ibm-cert-manager-operator
  - image: quay.io/opencloudio/ibm-cert-manager-operator-bundle
  - image: quay.io/opencloudio/ibm-common-service-operator-bundle
  - image: quay.io/opencloudio/ibm-commonui-operator
  - image: quay.io/opencloudio/ibm-commonui-operator-bundle
  - image: quay.io/opencloudio/ibm-crossplane-bedrock-shim-config
  - image: quay.io/opencloudio/ibm-crossplane-operator
  - image: quay.io/opencloudio/ibm-crossplane-operator-bundle
  - image: quay.io/opencloudio/ibm-cs-upgrade-to3.4
  - image: quay.io/opencloudio/ibm-cs-webhook
  - image: quay.io/opencloudio/ibm-dashboard-data-collector
  - image: quay.io/opencloudio/ibm-events-kafka-2.6.0
  - image: quay.io/opencloudio/ibm-events-kafka-2.6.1
  - image: quay.io/opencloudio/ibm-events-kafka-2.7.0
  - image: quay.io/opencloudio/ibm-events-operator
  - image: quay.io/opencloudio/ibm-events-operator-bundle
  - image: quay.io/opencloudio/ibm-healthcheck-operator
  - image: quay.io/opencloudio/ibm-healthcheck-operator-bundle
  - image: quay.io/opencloudio/ibm-iam-operator
  - image: quay.io/opencloudio/ibm-iam-operator-bundle
  - image: quay.io/opencloudio/ibm-ingress-nginx-operator
  - image: quay.io/opencloudio/ibm-ingress-nginx-operator-bundle
  - image: quay.io/opencloudio/ibm-license-service-reporter
  - image: quay.io/opencloudio/ibm-license-service-reporter-ui
  - image: quay.io/opencloudio/ibm-licensing
  - image: quay.io/opencloudio/ibm-licensing-operator
  - image: quay.io/opencloudio/ibm-licensing-operator-bundle
  - image: quay.io/opencloudio/ibm-licensing-usage
  - image: quay.io/opencloudio/ibm-management-ingress-operator
  - image: quay.io/opencloudio/ibm-management-ingress-operator-bundle
  - image: quay.io/opencloudio/ibm-mongodb
  - image: quay.io/opencloudio/ibm-mongodb-exporter
  - image: quay.io/opencloudio/ibm-mongodb-install
  - image: quay.io/opencloudio/ibm-mongodb-operator
  - image: quay.io/opencloudio/ibm-mongodb-operator-bundle
  - image: quay.io/opencloudio/ibm-monitoring-exporters-operator
  - image: quay.io/opencloudio/ibm-monitoring-exporters-operator-bundle
  - image: quay.io/opencloudio/ibm-monitoring-grafana-operator
  - image: quay.io/opencloudio/ibm-monitoring-grafana-operator-bundle
  - image: quay.io/opencloudio/ibm-monitoring-prometheusext-operator
  - image: quay.io/opencloudio/ibm-monitoring-prometheus-operator-ext-bundle
  - image: quay.io/opencloudio/ibm-namespace-scope-operator
  - image: quay.io/opencloudio/ibm-namespace-scope-operator-bundle
  - image: quay.io/opencloudio/ibm-namespace-scope-operator-restricted-bundle
  - image: quay.io/opencloudio/ibm-platform-api-operator
  - image: quay.io/opencloudio/ibm-platform-api-operator-bundle
  - image: quay.io/opencloudio/ibm-postgresql
  - image: quay.io/opencloudio/ibm-secretshare-operator
  - image: quay.io/opencloudio/ibm-zen-cpp-operator
  - image: quay.io/opencloudio/ibm-zen-cpp-operator-bundle
  - image: quay.io/opencloudio/ibm-zen-operator
  - image: quay.io/opencloudio/ibm-zen-operator-bundle
  - image: quay.io/opencloudio/icp4data-nginx-repo
  - image: quay.io/opencloudio/icp-audit-service
  - image: quay.io/opencloudio/icp-cert-manager-acmesolver
  - image: quay.io/opencloudio/icp-cert-manager-cainjector
  - image: quay.io/opencloudio/icp-cert-manager-controller
  - image: quay.io/opencloudio/icp-cert-manager-webhook
  - image: quay.io/opencloudio/icp-configmap-watcher
  - image: quay.io/opencloudio/icpd-requisite
  - image: quay.io/opencloudio/icp-iam-onboarding
  - image: quay.io/opencloudio/icp-identity-manager
  - image: quay.io/opencloudio/icp-identity-provider
  - image: quay.io/opencloudio/icp-initcontainer
  - image: quay.io/opencloudio/icp-management-ingress
  - image: quay.io/opencloudio/icp-memcached
  - image: quay.io/opencloudio/icp-oidcclient-watcher
  - image: quay.io/opencloudio/icp-platform-api
  - image: quay.io/opencloudio/icp-platform-auth
  - image: quay.io/opencloudio/icp-platform-header
  - image: quay.io/opencloudio/icp-secret-watcher
  - image: quay.io/opencloudio/influxdb
  - image: quay.io/opencloudio/kubectl
  - image: quay.io/opencloudio/kube-state-metrics
  - image: quay.io/opencloudio/must-gather
  - image: quay.io/opencloudio/must-gather-service
  - image: quay.io/opencloudio/nginx-ingress-controller
  - image: quay.io/opencloudio/node-exporter
  - image: quay.io/opencloudio/odlm
  - image: quay.io/opencloudio/operand-deployment-lifecycle-manager-bundle
  - image: quay.io/opencloudio/privatecloud-usermgmt
  - image: quay.io/opencloudio/prometheus
  - image: quay.io/opencloudio/prometheus-config-reloader
  - image: quay.io/opencloudio/prometheus-controller
  - image: quay.io/opencloudio/prometheus-operator
  - image: quay.io/opencloudio/system-healthcheck-service
  - image: quay.io/opencloudio/zen-audit
  - image: quay.io/opencloudio/zen-core
  - image: quay.io/opencloudio/zen-core-api
  - image: quay.io/opencloudio/zen-data-sorcerer
  - image: quay.io/opencloudio/zen-iam-config
  - image: quay.io/opencloudio/zen-influxdb-relay
  - image: quay.io/opencloudio/zen-metastoredb
  - image: quay.io/opencloudio/zen-watchdog
