source: ibm-cp4a-case-bundle/case/ibm-cp-automation/case.yaml
description: "A CASE for an operator which deploys cp4a"
images:
  - image: cp/cp4a/aae/dba-etcd
  - image: cp/cp4a/aae/dba-keytool-initcontainer
  - image: cp/cp4a/aae/solution-server
  - image: cp/cp4a/aae/solution-server-helmjob-db
  - image: cp/cp4a/adw/adw-designer
  - image: cp/cp4a/adw/adw-init
  - image: cp/cp4a/adw/adw-management
  - image: cp/cp4a/adw/adw-runtime
  - image: cp/cp4a/adw/adw-setup
  - image: cp/cp4a/adw/mongo
  - image: cp/cp4a/adw/verdaccio
  - image: cp/cp4a/baca/backend
  - image: cp/cp4a/baca/extraction
  - image: cp/cp4a/baca/mongo
  - image: cp/cp4a/baca/mongoha
  - image: cp/cp4a/baca/processing
  - image: cp/cp4a/baca/rabbitmq
  - image: cp/cp4a/baca/redis
  - image: cp/cp4a/baca/spfrontend
  - image: cp/cp4a/bai/bai-admin
  - image: cp/cp4a/bai/bai-adw
  - image: cp/cp4a/bai/bai-bawadv
  - image: cp/cp4a/bai/bai-bpmn
  - image: cp/cp4a/bai/bai-content
  - image: cp/cp4a/bai/bai-elasticsearch
  - image: cp/cp4a/bai/bai-flink
  - image: cp/cp4a/bai/bai-flink-zookeeper
  - image: cp/cp4a/bai/bai-icm
  - image: cp/cp4a/bai/bai-ingestion
  - image: cp/cp4a/bai/bai-init
  - image: cp/cp4a/bai/bai-kibana
  - image: cp/cp4a/bai/bai-odm
  - image: cp/cp4a/bai/bai-setup
  - image: cp/cp4a/ban/navigator
  - image: cp/cp4a/ban/navigator-sso
  - image: cp/cp4a/bas/bastudio
  - image: cp/cp4a/bas/dba-dbcompatibility-initcontainer
  - image: cp/cp4a/bas/dba-etcd
  - image: cp/cp4a/bas/dba-keytool-initcontainer
  - image: cp/cp4a/bas/dba-keytool-jobcontainer
  - image: cp/cp4a/bas/dba-umsregistration-initjob
  - image: cp/cp4a/bas/jms
  - image: cp/cp4a/bas/solution-server
  - image: cp/cp4a/bas/solution-server-helmjob-db
  - image: cp/cp4a/fncm/cmis
  - image: cp/cp4a/fncm/cpe
  - image: cp/cp4a/fncm/crs
  - image: cp/cp4a/fncm/css
  - image: cp/cp4a/fncm/extshare
  - image: cp/cp4a/fncm/graphql
  - image: cp/cp4a/fncm/taskmgr
  - image: cp/cp4a/iaws/baw-jms-server
  - image: cp/cp4a/iaws/dba-dbcompatibility-initcontainer
  - image: cp/cp4a/iaws/dba-keytool-initcontainer
  - image: cp/cp4a/iaws/dba-keytool-jobcontainer
  - image: cp/cp4a/iaws/dba-umsregistration-initjob
  - image: cp/cp4a/iaws/iaws-ibm-workplace
  - image: cp/cp4a/iaws/iaws-ps
  - image: cp/cp4a/iaws/iaws-ps-content-integration
  - image: cp/cp4a/iaws/iaws-psdb-handling
  - image: cp/cp4a/iaws/iaws-server
  - image: cp/cp4a/iaws/iaws-server-dbhandling
  - image: cp/cp4a/iaws/jms
  - image: cp/cp4a/iaws/pfs
  - image: cp/cp4a/iaws/pfs-bpd-database-init-prod
  - image: cp/cp4a/iaws/pfs-elasticsearch-prod
  - image: cp/cp4a/iaws/pfs-init-prod
  - image: cp/cp4a/iaws/pfs-nginx-prod
  - image: cp/cp4a/icp4a-operator
  - image: cp/cp4a/odm/dbserver
  - image: cp/cp4a/odm/odm-decisioncenter
  - image: cp/cp4a/odm/odm-decisionrunner
  - image: cp/cp4a/odm/odm-decisionserverconsole
  - image: cp/cp4a/odm/odm-decisionserverruntime
  - image: cp/cp4a/ums/dba-keytool-initcontainer
  - image: cp/cp4a/ums/dba-keytool-jobcontainer
  - image: cp/cp4a/ums/ums
