source: ibm-cp4a-case-cp4bav2120-bundle/case/ibm-cp-automation/case.yaml
description: "Cloud Pak for Business Automation delivers a robust, end-to-end solution for business automation needs within the clients enterprise. In the current competitive marketplace, digital companies use software automation to achieve higher revenue per employee than their traditional counterparts."
images:
  - image: cp/ai/ibm-ai-wmltraining-controller
  - image: cp/ai/ibm-ai-wmltraining-init-sidecar
  - image: cp/ai/ibm-ai-wmltraining-proxy-controller
  - image: cp/ai/ibm-ai-wmltraining-sidecar
  - image: cp/ai/model-mesh
  - image: cp/ai/model-serving-runtime-adapter
  - image: cp/ai/msp-ml-server
  - image: cp/ai/seldonio-mlserver
  - image: cp/ai/triton-inference-server
  - image: cp/ai/wmlserving-controller
  - image: cp/cp4a/aae/dba-dbcompatibility-initcontainer
  - image: cp/cp4a/aae/dba-etcd
  - image: cp/cp4a/aae/dba-keytool-initcontainer
  - image: cp/cp4a/aae/dba-umsregistration-initjob
  - image: cp/cp4a/aae/solution-server
  - image: cp/cp4a/aae/solution-server-helmjob-db
  - image: cp/cp4a/ads/ads-build
  - image: cp/cp4a/ads/ads-credentials
  - image: cp/cp4a/ads/ads-download
  - image: cp/cp4a/ads/ads-front
  - image: cp/cp4a/ads/ads-gitservice
  - image: cp/cp4a/ads/ads-parsing
  - image: cp/cp4a/ads/ads-restapi
  - image: cp/cp4a/ads/ads-rrintegration
  - image: cp/cp4a/ads/ads-run
  - image: cp/cp4a/ads/ads-runtime
  - image: cp/cp4a/ads/dba-keytool-initcontainer
  - image: cp/cp4a/ads/dba-keytool-jobcontainer
  - image: cp/cp4a/ads/dba-umsregistration-initjob
  - image: cp/cp4a/ads/mongo
  - image: cp/cp4a/adw/adw-designer
  - image: cp/cp4a/adw/adw-init
  - image: cp/cp4a/adw/adw-management
  - image: cp/cp4a/adw/adw-runtime
  - image: cp/cp4a/adw/adw-setup
  - image: cp/cp4a/adw/mongo
  - image: cp/cp4a/adw/verdaccio
  - image: cp/cp4a/baca/backend
  - image: cp/cp4a/baca/extraction
  - image: cp/cp4a/baca/mongo
  - image: cp/cp4a/baca/mongoha
  - image: cp/cp4a/baca/processing
  - image: cp/cp4a/baca/rabbitmq
  - image: cp/cp4a/baca/redis
  - image: cp/cp4a/baca/spfrontend
  - image: cp/cp4a/bai/bai-admin
  - image: cp/cp4a/bai/bai-adw
  - image: cp/cp4a/bai/bai-bawadv
  - image: cp/cp4a/bai/bai-bpmn
  - image: cp/cp4a/bai/bai-content
  - image: cp/cp4a/bai/bai-elasticsearch
  - image: cp/cp4a/bai/bai-event-forwarder
  - image: cp/cp4a/bai/bai-flink
  - image: cp/cp4a/bai/bai-flink-taskmanager
  - image: cp/cp4a/bai/bai-flink-zookeeper
  - image: cp/cp4a/bai/bai-icm
  - image: cp/cp4a/bai/bai-ingestion
  - image: cp/cp4a/bai/bai-init
  - image: cp/cp4a/bai/bai-kibana
  - image: cp/cp4a/bai/bai-management
  - image: cp/cp4a/bai/bai-management-backend
  - image: cp/cp4a/bai/bai-monitoring-app
  - image: cp/cp4a/bai/bai-nlq-core
  - image: cp/cp4a/bai/bai-nlq-deployment
  - image: cp/cp4a/bai/bai_nlq_ontology
  - image: cp/cp4a/bai/bai-nlq-ontology
  - image: cp/cp4a/bai/bai-nlq-runtime
  - image: cp/cp4a/bai/bai-odm
  - image: cp/cp4a/bai/bai-setup
  - image: cp/cp4a/bai/bai-verdi-idw-server
  - image: cp/cp4a/bai/bai-verdi-nlq-operator
  - image: cp/cp4a/bai/bai-verdi-operator
  - image: cp/cp4a/bai/bai-verdi-seeder-tech-preview
  - image: cp/cp4a/bai/bai-verdi-webclient
  - image: cp/cp4a/bai/dba-keytool-initcontainer
  - image: cp/cp4a/bai/dba-umsregistration-initjob
  - image: cp/cp4a/ban/navigator
  - image: cp/cp4a/ban/navigator-sso
  - image: cp/cp4a/bas/bastudio
  - image: cp/cp4a/bas/dba-dbcompatibility-initcontainer
  - image: cp/cp4a/bas/dba-etcd
  - image: cp/cp4a/bas/dba-keytool-initcontainer
  - image: cp/cp4a/bas/dba-keytool-jobcontainer
  - image: cp/cp4a/bas/dba-umsregistration-initjob
  - image: cp/cp4a/bas/jms
  - image: cp/cp4a/bas/solution-server
  - image: cp/cp4a/bas/solution-server-helmjob-db
  - image: cp/cp4a/bas/workflow-authoring
  - image: cp/cp4a/baw/bui-task-prioritization
  - image: cp/cp4a/baw/dba-dbcompatibility-initcontainer
  - image: cp/cp4a/baw/dba-keytool-initcontainer
  - image: cp/cp4a/baw/dba-keytool-jobcontainer
  - image: cp/cp4a/baw/dba-umsregistration-initjob
  - image: cp/cp4a/baw/iaws-ibm-workplace
  - image: cp/cp4a/baw/iaws-ps-content-integration
  - image: cp/cp4a/baw/jms
  - image: cp/cp4a/baw/pfs-bpd-database-init-prod
  - image: cp/cp4a/baw/pfs-elasticsearch-prod
  - image: cp/cp4a/baw/pfs-init-prod
  - image: cp/cp4a/baw/pfs-nginx-prod
  - image: cp/cp4a/baw/pfs-prod
  - image: cp/cp4a/baw/toolkit-installer
  - image: cp/cp4a/baw/workflow-server
  - image: cp/cp4a/baw/workflow-server-case-initialization
  - image: cp/cp4a/baw/workflow-server-dbhandling
  - image: cp/cp4a/baw/workforce-insights
  - image: cp/cp4a/demo/alpine
  - image: cp/cp4a/demo/busybox
  - image: cp/cp4a/demo/gitea
  - image: cp/cp4a/demo/openldap
  - image: cp/cp4a/demo/phpldapadmin
  - image: cp/cp4a/fncm/cmis
  - image: cp/cp4a/fncm/cpe
  - image: cp/cp4a/fncm/crs
  - image: cp/cp4a/fncm/css
  - image: cp/cp4a/fncm/css-if002
  - image: cp/cp4a/fncm/extshare
  - image: cp/cp4a/fncm/graphql
  - image: cp/cp4a/fncm/taskmgr
  - image: cp/cp4a/iadp/backend
  - image: cp/cp4a/iadp/cdra
  - image: cp/cp4a/iadp/cds
  - image: cp/cp4a/iadp/cpds
  - image: cp/cp4a/iadp/dba-keytool-initcontainer
  - image: cp/cp4a/iadp/deep_learning
  - image: cp/cp4a/iadp/extraction
  - image: cp/cp4a/iadp/gitgateway
  - image: cp/cp4a/iadp/mongo
  - image: cp/cp4a/iadp/natural_language_extractor
  - image: cp/cp4a/iadp/processing
  - image: cp/cp4a/iadp/rabbitmq
  - image: cp/cp4a/iadp/redis
  - image: cp/cp4a/iadp/viewone
  - image: cp/cp4a/ibm-cp-automation-catalog
  - image: cp/cp4a/iccsap/iccsap
  - image: cp/cp4a/icp4a-operator
  - image: cp/cp4a/ier/ier
  - image: cp/cp4a/odm/dba-keytool-initcontainer
  - image: cp/cp4a/odm/dbserver
  - image: cp/cp4a/odm/odm-decisioncenter
  - image: cp/cp4a/odm/odm-decisionrunner
  - image: cp/cp4a/odm/odm-decisionserverconsole
  - image: cp/cp4a/odm/odm-decisionserverruntime
  - image: cp/cp4a/ums/dba-keytool-initcontainer
  - image: cp/cp4a/ums/dba-keytool-jobcontainer
  - image: cp/cp4a/ums/dba-ums-secret-initcontainer
  - image: cp/cp4a/ums/ums
  - image: cp/db2u
  - image: cp/db2u.auxiliary.auth
  - image: cp/db2u.bigsql.mariadb
  - image: cp/db2u.graph
  - image: cp/db2u.hurricane
  - image: cp/db2u.instdb
  - image: cp/db2u.rest
  - image: cp/db2u.tools
  - image: cp/etcd
  - image: cp/iaf-ai-pipeline-ctrl
  - image: cp/iaf-ai-pipeline-step
  - image: cp/iaf-apicurio-registry
  - image: cp/iaf-elasticsearch
  - image: cp/iaf-elasticsearch-metrics-exporter
  - image: cp/iaf-elasticsearch-proxy
  - image: cp/iaf-eventprocessing-proxy
  - image: cp/iaf-flink
  - image: cp/iaf-health-service
  - image: cp/iaf-ui-customization
  - image: cp/ibm-cloud-databases-redis-operator
  - image: cp/ibm-eventstreams-admin
  - image: cp/ibm-eventstreams-admin-ui
  - image: cp/ibm-eventstreams-apicurio-registry
  - image: cp/ibm-eventstreams-jmxtrans
  - image: cp/ibm-eventstreams-kafka
  - image: cp/ibm-eventstreams-metrics-collector
  - image: cp/ibm-eventstreams-rest-producer
  - image: cp/ibm-eventstreams-schema-proxy
  - image: cp/ibm-eventstreams-schema-registry
  - image: cp/ibm-eventstreams-schema-registry-avro
  - image: cp/ibm-eventstreams-session-store
  - image: cp/ibm-mqadvanced-server
  - image: cp/ibm-mqadvanced-server-integration
  - image: cp/ibm-rpa-abbyy
  - image: cp/ibm-rpa-antivirus-api
  - image: cp/ibm-rpa-antivirus-scanner
  - image: cp/ibm-rpa-api
  - image: cp/ibm-rpa-minimal
  - image: cp/ibm-rpa-ui
  - image: cp/icp4i/od/icp4i-od-agent
  - image: cp/icp4i/od/icp4i-od-collector
  - image: cp/opencontent-etcd-3
  - image: cp/processmining-analytics
  - image: cp/processmining-bpa
  - image: cp/processmining-connectors
  - image: cp/processmining-discovery
  - image: cp/processmining-dr
  - image: cp/processmining-mongo
  - image: cp/processmining-mysql
  - image: cp/processmining-nginx
  - image: cp/processmining-ssl
  - image: cp/processmining-tm-nginx
  - image: cp/processmining-tm-taskbuilder
  - image: cp/processmining-tm-taskprocessor
  - image: cp/processmining-tm-webapp
  - image: cp/processmining-usermanagement
  - image: cp/redis-db-5.0.5
  - image: cp/redis-db-5.0.9
  - image: cp/redis-mgmt-5.0.5
  - image: cp/redis-mgmt-5.0.9
  - image: cp/redis-proxy-5.0.5
  - image: cp/redis-proxy-5.0.9
  - image: cp/redis-proxylog-5.0.5
  - image: cp/redis-proxylog-5.0.9
  - image: ibmcom/db2u-operator
  - image: ibmcom/iaf-ai-operator
  - image: ibmcom/iaf-ai-operator-bundle
  - image: ibmcom/iaf-base-operator
  - image: ibmcom/iaf-base-operator-bundle
  - image: ibmcom/iaf-core-operator
  - image: ibmcom/iaf-core-operator-bundle
  - image: ibmcom/iaf-elastic-operator
  - image: ibmcom/iaf-elastic-operator-bundle
  - image: ibmcom/iaf-eventprocessing-operator
  - image: ibmcom/iaf-eventprocessing-operator-bundle
  - image: ibmcom/iaf-flink-operator
  - image: ibmcom/iaf-flink-operator-bundle
  - image: ibmcom/ibm-automation-foundation-core-catalog
  - image: ibmcom/ibm-cloud-databases-redis-operator
  - image: ibmcom/ibm-cloud-databases-redis-operator-bundle
  - image: ibmcom/ibm-common-service-catalog
  - image: ibmcom/ibm-cp-automation-foundation-catalog
  - image: ibmcom/ibm-db2uoperator-bundle
  - image: ibmcom/ibm-db2uoperator-catalog
  - image: ibmcom/ibm-eventstreams-catalog
  - image: ibmcom/ibm-eventstreams-operator
  - image: ibmcom/ibm-eventstreams-operator-bundle
  - image: ibmcom/ibm-eventstreams-operator-init
  - image: ibmcom/ibm-mq-operator
  - image: ibmcom/ibm-mq-operator-bundle
  - image: ibmcom/ibm-mq-operator-catalog
  - image: ibmcom/icp4a-operator-bundle
  - image: ibmcom/mq
  - image: ibmcom/processmining-operator
  - image: ibmcom/processmining-operator-bundle
  - image: ibmcom/processmining-operator-catalog
  - image: icr.io/cpopen/iaf-ai-operator
  - image: icr.io/cpopen/iaf-ai-operator-bundle
  - image: icr.io/cpopen/iaf-base-operator
  - image: icr.io/cpopen/iaf-base-operator-bundle
  - image: icr.io/cpopen/iaf-core-operator
  - image: icr.io/cpopen/iaf-core-operator-bundle
  - image: icr.io/cpopen/iaf-elastic-operator
  - image: icr.io/cpopen/iaf-elastic-operator-bundle
  - image: icr.io/cpopen/iaf-eventprocessing-operator
  - image: icr.io/cpopen/iaf-eventprocessing-operator-bundle
  - image: icr.io/cpopen/iaf-flink-operator
  - image: icr.io/cpopen/iaf-flink-operator-bundle
  - image: icr.io/cpopen/ibm-ai-wmlserving-operator
  - image: icr.io/cpopen/ibm-ai-wmlserving-operator-bundle
  - image: icr.io/cpopen/ibm-ai-wmlserving-operator-catalog
  - image: icr.io/cpopen/ibm-ai-wmltraining-operator
  - image: icr.io/cpopen/ibm-ai-wmltraining-operator-bundle
  - image: icr.io/cpopen/ibm-ai-wmltraining-operator-catalog
  - image: icr.io/cpopen/ibm-automation-foundation-core-catalog
  - image: icr.io/cpopen/ibm-cloud-databases-redis-catalog
  - image: icr.io/cpopen/ibm-cloud-databases-redis-operator
  - image: icr.io/cpopen/ibm-cloud-databases-redis-operator-bundle
  - image: icr.io/cpopen/ibm-common-service-catalog
  - image: icr.io/cpopen/ibm-cp-automation-foundation-catalog
  - image: icr.io/cpopen/ibm-etcd-operator-bundle
  - image: icr.io/cpopen/ibm-etcd-operator-catalog
  - image: icr.io/cpopen/ibm-mq-operator
  - image: icr.io/cpopen/ibm-mq-operator-bundle
  - image: icr.io/cpopen/ibm-mq-operator-catalog
  - image: icr.io/cpopen/ibm-rpa-operator
  - image: icr.io/cpopen/ibm-rpa-operator-bundle
  - image: icr.io/cpopen/ibm-rpa-operator-catalog
  - image: icr.io/cpopen/icp4a-operator-bundle
  - image: icr.io/cpopen/opencontent-etcd-operator
  - image: icr.io/cpopen/processmining-operator
  - image: icr.io/cpopen/processmining-operator-bundle
  - image: icr.io/cpopen/processmining-operator-catalog
  - image: quay.io/opencloudio/alertmanager
  - image: quay.io/opencloudio/audit-garbage-collector
  - image: quay.io/opencloudio/audit-policy-controller
  - image: quay.io/opencloudio/audit-syslog-service
  - image: quay.io/opencloudio/collectd-exporter
  - image: quay.io/opencloudio/common-service-operator
  - image: quay.io/opencloudio/common-web-ui
  - image: quay.io/opencloudio/configmap-reload
  - image: quay.io/opencloudio/cp4d-tiller
  - image: quay.io/opencloudio/cs-mongodb-br
  - image: quay.io/opencloudio/dashboard-controller
  - image: quay.io/opencloudio/default-http-backend
  - image: quay.io/opencloudio/fluentd
  - image: quay.io/opencloudio/grafana
  - image: quay.io/opencloudio/grafana-ocpthanos-proxy
  - image: quay.io/opencloudio/iam-policy-administration
  - image: quay.io/opencloudio/iam-policy-controller
  - image: quay.io/opencloudio/iam-policy-decision
  - image: quay.io/opencloudio/ibm-auditlogging-operator
  - image: quay.io/opencloudio/ibm-auditlogging-operator-bundle
  - image: quay.io/opencloudio/ibm-cert-manager-operator
  - image: quay.io/opencloudio/ibm-cert-manager-operator-bundle
  - image: quay.io/opencloudio/ibm-common-service-operator-bundle
  - image: quay.io/opencloudio/ibm-commonui-operator
  - image: quay.io/opencloudio/ibm-commonui-operator-bundle
  - image: quay.io/opencloudio/ibm-crossplane-bedrock-shim-config
  - image: quay.io/opencloudio/ibm-crossplane-operator
  - image: quay.io/opencloudio/ibm-crossplane-operator-bundle
  - image: quay.io/opencloudio/ibm-cs-upgrade-to3.4
  - image: quay.io/opencloudio/ibm-cs-webhook
  - image: quay.io/opencloudio/ibm-dashboard-data-collector
  - image: quay.io/opencloudio/ibm-events-kafka-2.6.0
  - image: quay.io/opencloudio/ibm-events-kafka-2.6.1
  - image: quay.io/opencloudio/ibm-events-kafka-2.7.0
  - image: quay.io/opencloudio/ibm-events-operator
  - image: quay.io/opencloudio/ibm-events-operator-bundle
  - image: quay.io/opencloudio/ibm-healthcheck-operator
  - image: quay.io/opencloudio/ibm-healthcheck-operator-bundle
  - image: quay.io/opencloudio/ibm-iam-operator
  - image: quay.io/opencloudio/ibm-iam-operator-bundle
  - image: quay.io/opencloudio/ibm-iam-policy-operator-bundle
  - image: quay.io/opencloudio/ibm-ingress-nginx-operator
  - image: quay.io/opencloudio/ibm-ingress-nginx-operator-bundle
  - image: quay.io/opencloudio/ibm-license-service-reporter
  - image: quay.io/opencloudio/ibm-license-service-reporter-ui
  - image: quay.io/opencloudio/ibm-licensing
  - image: quay.io/opencloudio/ibm-licensing-operator
  - image: quay.io/opencloudio/ibm-licensing-operator-bundle
  - image: quay.io/opencloudio/ibm-licensing-usage
  - image: quay.io/opencloudio/ibm-management-ingress-operator
  - image: quay.io/opencloudio/ibm-management-ingress-operator-bundle
  - image: quay.io/opencloudio/ibm-mongodb
  - image: quay.io/opencloudio/ibm-mongodb-exporter
  - image: quay.io/opencloudio/ibm-mongodb-install
  - image: quay.io/opencloudio/ibm-mongodb-operator
  - image: quay.io/opencloudio/ibm-mongodb-operator-bundle
  - image: quay.io/opencloudio/ibm-monitoring-exporters-operator
  - image: quay.io/opencloudio/ibm-monitoring-exporters-operator-bundle
  - image: quay.io/opencloudio/ibm-monitoring-grafana-operator
  - image: quay.io/opencloudio/ibm-monitoring-grafana-operator-bundle
  - image: quay.io/opencloudio/ibm-monitoring-prometheusext-operator
  - image: quay.io/opencloudio/ibm-monitoring-prometheus-operator-ext-bundle
  - image: quay.io/opencloudio/ibm-namespace-scope-operator
  - image: quay.io/opencloudio/ibm-namespace-scope-operator-bundle
  - image: quay.io/opencloudio/ibm-namespace-scope-operator-restricted-bundle
  - image: quay.io/opencloudio/ibm-platform-api-operator
  - image: quay.io/opencloudio/ibm-platform-api-operator-bundle
  - image: quay.io/opencloudio/ibm-postgresql
  - image: quay.io/opencloudio/ibm-secretshare-operator
  - image: quay.io/opencloudio/ibm-zen-operator
  - image: quay.io/opencloudio/ibm-zen-operator-bundle
  - image: quay.io/opencloudio/icp4data-nginx-repo
  - image: quay.io/opencloudio/icp-audit-service
  - image: quay.io/opencloudio/icp-cert-manager-acmesolver
  - image: quay.io/opencloudio/icp-cert-manager-cainjector
  - image: quay.io/opencloudio/icp-cert-manager-controller
  - image: quay.io/opencloudio/icp-cert-manager-webhook
  - image: quay.io/opencloudio/icp-configmap-watcher
  - image: quay.io/opencloudio/icpd-requisite
  - image: quay.io/opencloudio/icp-iam-onboarding
  - image: quay.io/opencloudio/icp-identity-manager
  - image: quay.io/opencloudio/icp-identity-provider
  - image: quay.io/opencloudio/icp-initcontainer
  - image: quay.io/opencloudio/icp-management-ingress
  - image: quay.io/opencloudio/icp-memcached
  - image: quay.io/opencloudio/icp-oidcclient-watcher
  - image: quay.io/opencloudio/icp-platform-api
  - image: quay.io/opencloudio/icp-platform-auth
  - image: quay.io/opencloudio/icp-platform-header
  - image: quay.io/opencloudio/icp-secret-watcher
  - image: quay.io/opencloudio/influxdb
  - image: quay.io/opencloudio/kubectl
  - image: quay.io/opencloudio/kube-state-metrics
  - image: quay.io/opencloudio/must-gather
  - image: quay.io/opencloudio/must-gather-service
  - image: quay.io/opencloudio/nginx-ingress-controller
  - image: quay.io/opencloudio/node-exporter
  - image: quay.io/opencloudio/odlm
  - image: quay.io/opencloudio/operand-deployment-lifecycle-manager-bundle
  - image: quay.io/opencloudio/privatecloud-usermgmt
  - image: quay.io/opencloudio/prometheus
  - image: quay.io/opencloudio/prometheus-config-reloader
  - image: quay.io/opencloudio/prometheus-controller
  - image: quay.io/opencloudio/prometheus-operator
  - image: quay.io/opencloudio/system-healthcheck-service
  - image: quay.io/opencloudio/zen-audit
  - image: quay.io/opencloudio/zen-core
  - image: quay.io/opencloudio/zen-core-api
  - image: quay.io/opencloudio/zen-data-sorcerer
  - image: quay.io/opencloudio/zen-iam-config
  - image: quay.io/opencloudio/zen-metastoredb
  - image: quay.io/opencloudio/zen-watchdog
