source: ibm-cp-applications-bundle/case/ibm-cp-applications/case.yaml
description: "Move from monolithic to microservices with DevOps methodologies and modernization toolkits"
images:
  - image: cp/es-operator
  - image: cp/icpa/accel4team-command-line-services
  - image: cp/icpa/accel4team-rest-services
  - image: cp/icpa/che-devfile-registry
  - image: cp/icpa/icpa-aft-console
  - image: cp/icpa/icpa-aft-console-appsody
  - image: cp/icpa/icpa-app-nav-apis
  - image: cp/icpa/icpa-app-nav-cmds
  - image: cp/icpa/icpa-app-nav-controller
  - image: cp/icpa/icpa-app-nav-init
  - image: cp/icpa/icpa-app-nav-inv
  - image: cp/icpa/icpa-app-nav-operator
  - image: cp/icpa/icpa-app-nav-ui
  - image: cp/icpa/icpa-app-nav-was-controller
  - image: cp/icpa/icpa-installer
  - image: cp/icpa/icpa-landing
  - image: cp/icpa/icpa-mediator-operator
  - image: cp/icpa/icpa-operator-registry
  - image: cp/icpa/icpa-security-signing-manager
  - image: cp/icpa/icpa-teams-operator
  - image: cp/icpa/sb-checkin-handler
  - image: cp/icpa/sb-gitops-handler
  - image: cp/icpa/sb-init-handler
  - image: cp/icpa/sb-run-manager
  - image: cp/icpa/sb-ui
  - image: cp/icpa/transadv-db
  - image: cp/icpa/transadv-operator
  - image: cp/icpa/transadv-server
  - image: cp/icpa/transadv-ui
  - image: cp/icp-foundation/alertmanager
  - image: cp/icp-foundation/audit-policy-controller
  - image: cp/icp-foundation/collectd-exporter
  - image: cp/icp-foundation/common-web-ui
  - image: cp/icp-foundation/configmap-reload
  - image: cp/icp-foundation/curl
  - image: cp/icp-foundation/dashboard-controller
  - image: cp/icp-foundation/default-http-backend
  - image: cp/icp-foundation/elasticsearch-exporter
  - image: cp/icp-foundation/fluentd
  - image: cp/icp-foundation/grafana
  - image: cp/icp-foundation/iam-policy-administration
  - image: cp/icp-foundation/iam-policy-controller
  - image: cp/icp-foundation/iam-policy-decision
  - image: cp/icp-foundation/ibm-licensing
  - image: cp/icp-foundation/ibm-mongodb
  - image: cp/icp-foundation/ibm-mongodb-exporter
  - image: cp/icp-foundation/ibm-mongodb-install
  - image: cp/icp-foundation/ibm-mt-acct-enforcer
  - image: cp/icp-foundation/ibmservices-operator
  - image: cp/icp-foundation/icp-audit-service
  - image: cp/icp-foundation/icp-catalog-ui
  - image: cp/icp-foundation/icp-cert-manager-acmesolver
  - image: cp/icp-foundation/icp-cert-manager-cainjector
  - image: cp/icp-foundation/icp-cert-manager-controller
  - image: cp/icp-foundation/icp-cert-manager-webhook
  - image: cp/icp-foundation/icp-cert-policy-controller
  - image: cp/icp-foundation/icp-configmap-watcher
  - image: cp/icp-foundation/icp-elasticsearch-oss
  - image: cp/icp-foundation/icp-filebeat-oss
  - image: cp/icp-foundation/icp-helm-api
  - image: cp/icp-foundation/icp-helm-repo
  - image: cp/icp-foundation/icp-helm-rudder
  - image: cp/icp-foundation/icp-iam-onboarding
  - image: cp/icp-foundation/icp-identity-manager
  - image: cp/icp-foundation/icp-identity-provider
  - image: cp/icp-foundation/icp-inception
  - image: cp/icp-foundation/icp-initcontainer
  - image: cp/icp-foundation/icp-kibana-oss
  - image: cp/icp-foundation/icp-logstash-oss
  - image: cp/icp-foundation/icp-management-ingress
  - image: cp/icp-foundation/icp-memcached
  - image: cp/icp-foundation/icp-oidcclient-watcher
  - image: cp/icp-foundation/icp-platform-api
  - image: cp/icp-foundation/icp-platform-auth
  - image: cp/icp-foundation/icp-platform-header
  - image: cp/icp-foundation/icp-secret-watcher
  - image: cp/icp-foundation/indices-cleaner
  - image: cp/icp-foundation/kubectl
  - image: cp/icp-foundation/kube-state-metrics
  - image: cp/icp-foundation/logging-pki-init
  - image: cp/icp-foundation/logstash-liveness-probe
  - image: cp/icp-foundation/mcm-kui-proxy
  - image: cp/icp-foundation/metering-data-manager
  - image: cp/icp-foundation/metering-mcmui
  - image: cp/icp-foundation/metering-ui
  - image: cp/icp-foundation/nginx-ingress-controller
  - image: cp/icp-foundation/node-exporter
  - image: cp/icp-foundation/prometheus
  - image: cp/icp-foundation/prometheus-config-reloader
  - image: cp/icp-foundation/prometheus-controller
  - image: cp/icp-foundation/prometheus-operator
  - image: cp/icp-foundation/system-healthcheck-service
  - image: cp/icp-foundation/tiller
  - image: cp/mf-operator
  - image: cp/mfpf-analytics
  - image: cp/mfpf-analytics-recvr
  - image: cp/mfpf-appcenter
  - image: cp/mfpf-dbinit
  - image: cp/mfpf-elasticsearch
  - image: cp/mfpf-liveupdate
  - image: cp/mfpf-push
  - image: cp/mfpf-server
  - image: ibmcom/busybox
  - image: ibmcom/ibm-common-service-catalog
  - image: ibmcom/opencontent-common-utils
  - image: ibmcom/transformation-advisor-operator
  - image: ibmcom/transformation-advisor-operator-bundle
  - image: ibmcom/transformation-advisor-operator-catalog
  - image: icp4apps/pipelines-utils
  - image: icp4apps/scanner
  - image: icr.io/cpopen/common-service-operator
  - image: icr.io/cpopen/cpfs/audit-garbage-collector
  - image: icr.io/cpopen/cpfs/audit-policy-controller
  - image: icr.io/cpopen/cpfs/audit-syslog-service
  - image: icr.io/cpopen/cpfs/common-web-ui
  - image: icr.io/cpopen/cpfs/dashboard-controller
  - image: icr.io/cpopen/cpfs/default-http-backend
  - image: icr.io/cpopen/cpfs/fluentd
  - image: icr.io/cpopen/cpfs/grafana
  - image: icr.io/cpopen/cpfs/grafana-ocpthanos-proxy
  - image: icr.io/cpopen/cpfs/iam-policy-administration
  - image: icr.io/cpopen/cpfs/iam-policy-controller
  - image: icr.io/cpopen/cpfs/iam-policy-decision
  - image: icr.io/cpopen/cpfs/ibm-crossplane-bedrock-shim-config
  - image: icr.io/cpopen/cpfs/ibm-cs-webhook
  - image: icr.io/cpopen/cpfs/ibm-events-kafka-3.0.0
  - image: icr.io/cpopen/cpfs/ibm-events-kafka-3.1.0
  - image: icr.io/cpopen/cpfs/ibm-events-kafka-3.2.0
  - image: icr.io/cpopen/cpfs/ibm-license-service-reporter
  - image: icr.io/cpopen/cpfs/ibm-license-service-reporter-ui
  - image: icr.io/cpopen/cpfs/ibm-licensing
  - image: icr.io/cpopen/cpfs/ibm-licensing-usage
  - image: icr.io/cpopen/cpfs/ibm-mongodb
  - image: icr.io/cpopen/cpfs/ibm-mongodb-exporter
  - image: icr.io/cpopen/cpfs/ibm-mongodb-install
  - image: icr.io/cpopen/cpfs/ibm-postgresql
  - image: icr.io/cpopen/cpfs/ibm-secretshare-operator
  - image: icr.io/cpopen/cpfs/icp4data-nginx-repo
  - image: icr.io/cpopen/cpfs/icp-cert-manager-acmesolver
  - image: icr.io/cpopen/cpfs/icp-cert-manager-cainjector
  - image: icr.io/cpopen/cpfs/icp-cert-manager-controller
  - image: icr.io/cpopen/cpfs/icp-cert-manager-webhook
  - image: icr.io/cpopen/cpfs/icp-configmap-watcher
  - image: icr.io/cpopen/cpfs/icpd-requisite
  - image: icr.io/cpopen/cpfs/icp-iam-onboarding
  - image: icr.io/cpopen/cpfs/icp-identity-manager
  - image: icr.io/cpopen/cpfs/icp-identity-provider
  - image: icr.io/cpopen/cpfs/icp-initcontainer
  - image: icr.io/cpopen/cpfs/icp-management-ingress
  - image: icr.io/cpopen/cpfs/icp-memcached
  - image: icr.io/cpopen/cpfs/icp-oidcclient-watcher
  - image: icr.io/cpopen/cpfs/icp-platform-api
  - image: icr.io/cpopen/cpfs/icp-platform-auth
  - image: icr.io/cpopen/cpfs/icp-secret-watcher
  - image: icr.io/cpopen/cpfs/influxdb
  - image: icr.io/cpopen/cpfs/kubectl
  - image: icr.io/cpopen/cpfs/must-gather
  - image: icr.io/cpopen/cpfs/must-gather-service
  - image: icr.io/cpopen/cpfs/nginx-ingress-controller
  - image: icr.io/cpopen/cpfs/privatecloud-usermgmt
  - image: icr.io/cpopen/cpfs/system-healthcheck-service
  - image: icr.io/cpopen/cpfs/zen-audit
  - image: icr.io/cpopen/cpfs/zen-core
  - image: icr.io/cpopen/cpfs/zen-core-api
  - image: icr.io/cpopen/cpfs/zen-data-sorcerer
  - image: icr.io/cpopen/cpfs/zen-iam-config
  - image: icr.io/cpopen/cpfs/zen-influxdb-relay
  - image: icr.io/cpopen/cpfs/zen-metastoredb
  - image: icr.io/cpopen/cpfs/zen-watchdog
  - image: icr.io/cpopen/ibm-auditlogging-operator
  - image: icr.io/cpopen/ibm-auditlogging-operator-bundle
  - image: icr.io/cpopen/ibm-cert-manager-operator
  - image: icr.io/cpopen/ibm-cert-manager-operator-bundle
  - image: icr.io/cpopen/ibm-common-service-catalog
  - image: icr.io/cpopen/ibm-common-service-operator-bundle
  - image: icr.io/cpopen/ibm-commonui-operator
  - image: icr.io/cpopen/ibm-commonui-operator-bundle
  - image: icr.io/cpopen/ibm-crossplane-operator
  - image: icr.io/cpopen/ibm-crossplane-operator-bundle
  - image: icr.io/cpopen/ibm-crossplane-provider-ibm-cloud-operator
  - image: icr.io/cpopen/ibm-crossplane-provider-ibm-cloud-operator-bundle
  - image: icr.io/cpopen/ibm-crossplane-provider-kubernetes-operator
  - image: icr.io/cpopen/ibm-crossplane-provider-kubernetes-operator-bundle
  - image: icr.io/cpopen/ibm-events-operator
  - image: icr.io/cpopen/ibm-events-operator-bundle
  - image: icr.io/cpopen/ibm-healthcheck-operator
  - image: icr.io/cpopen/ibm-healthcheck-operator-bundle
  - image: icr.io/cpopen/ibm-iam-operator
  - image: icr.io/cpopen/ibm-iam-operator-bundle
  - image: icr.io/cpopen/ibm-ingress-nginx-operator
  - image: icr.io/cpopen/ibm-ingress-nginx-operator-bundle
  - image: icr.io/cpopen/ibm-licensing-operator
  - image: icr.io/cpopen/ibm-licensing-operator-bundle
  - image: icr.io/cpopen/ibm-management-ingress-operator
  - image: icr.io/cpopen/ibm-management-ingress-operator-bundle
  - image: icr.io/cpopen/ibm-mongodb-operator
  - image: icr.io/cpopen/ibm-mongodb-operator-bundle
  - image: icr.io/cpopen/ibm-monitoring-grafana-operator
  - image: icr.io/cpopen/ibm-monitoring-grafana-operator-bundle
  - image: icr.io/cpopen/ibm-namespace-scope-operator
  - image: icr.io/cpopen/ibm-namespace-scope-operator-bundle
  - image: icr.io/cpopen/ibm-namespace-scope-operator-restricted-bundle
  - image: icr.io/cpopen/ibm-platform-api-operator
  - image: icr.io/cpopen/ibm-platform-api-operator-bundle
  - image: icr.io/cpopen/ibm-zen-cpp-operator
  - image: icr.io/cpopen/ibm-zen-cpp-operator-bundle
  - image: icr.io/cpopen/ibm-zen-operator
  - image: icr.io/cpopen/ibm-zen-operator-bundle
  - image: icr.io/cpopen/odlm
  - image: icr.io/cpopen/operand-deployment-lifecycle-manager-bundle
  - image: kabanero/kabanero-utils
  - image: kabanero/scanner
  - image: maiwj/kubernetes-python-client
  - image: quay.io/opencloudio/alertmanager
  - image: quay.io/opencloudio/audit-garbage-collector
  - image: quay.io/opencloudio/audit-policy-controller
  - image: quay.io/opencloudio/audit-syslog-service
  - image: quay.io/opencloudio/collectd-exporter
  - image: quay.io/opencloudio/common-service-operator
  - image: quay.io/opencloudio/common-web-ui
  - image: quay.io/opencloudio/configmap-reload
  - image: quay.io/opencloudio/cp4d-tiller
  - image: quay.io/opencloudio/cs-mongodb-br
  - image: quay.io/opencloudio/curl
  - image: quay.io/opencloudio/dashboard-controller
  - image: quay.io/opencloudio/default-http-backend
  - image: quay.io/opencloudio/fluentd
  - image: quay.io/opencloudio/grafana
  - image: quay.io/opencloudio/grafana-ocpthanos-proxy
  - image: quay.io/opencloudio/iam-policy-administration
  - image: quay.io/opencloudio/iam-policy-controller
  - image: quay.io/opencloudio/iam-policy-decision
  - image: quay.io/opencloudio/ibm-auditlogging-operator
  - image: quay.io/opencloudio/ibm-auditlogging-operator-bundle
  - image: quay.io/opencloudio/ibm-catalog-ui-operator
  - image: quay.io/opencloudio/ibm-catalog-ui-operator-bundle
  - image: quay.io/opencloudio/ibm-cert-manager-operator
  - image: quay.io/opencloudio/ibm-cert-manager-operator-bundle
  - image: quay.io/opencloudio/ibm-common-service-catalog
  - image: quay.io/opencloudio/ibm-common-service-operator-bundle
  - image: quay.io/opencloudio/ibm-commonui-operator
  - image: quay.io/opencloudio/ibm-commonui-operator-bundle
  - image: quay.io/opencloudio/ibm-crossplane-bedrock-shim-config
  - image: quay.io/opencloudio/ibm-crossplane-operator
  - image: quay.io/opencloudio/ibm-crossplane-operator-bundle
  - image: quay.io/opencloudio/ibm-crossplane-provider-ibm-cloud-operator
  - image: quay.io/opencloudio/ibm-crossplane-provider-ibm-cloud-operator-bundle
  - image: quay.io/opencloudio/ibm-crossplane-provider-kubernetes-operator
  - image: quay.io/opencloudio/ibm-crossplane-provider-kubernetes-operator-bundle
  - image: quay.io/opencloudio/ibm-cs-upgrade-to3.4
  - image: quay.io/opencloudio/ibm-cs-webhook
  - image: quay.io/opencloudio/ibm-dashboard-data-collector
  - image: quay.io/opencloudio/ibm-elastic-stack-operator
  - image: quay.io/opencloudio/ibm-elastic-stack-operator-bundle
  - image: quay.io/opencloudio/ibm-events-kafka-2.6.0
  - image: quay.io/opencloudio/ibm-events-kafka-2.6.1
  - image: quay.io/opencloudio/ibm-events-kafka-2.7.0
  - image: quay.io/opencloudio/ibm-events-operator
  - image: quay.io/opencloudio/ibm-events-operator-bundle
  - image: quay.io/opencloudio/ibm-healthcheck-operator
  - image: quay.io/opencloudio/ibm-healthcheck-operator-bundle
  - image: quay.io/opencloudio/ibm-helm-api-operator
  - image: quay.io/opencloudio/ibm-helm-api-operator-bundle
  - image: quay.io/opencloudio/ibm-helm-repo-operator
  - image: quay.io/opencloudio/ibm-helm-repo-operator-bundle
  - image: quay.io/opencloudio/ibm-iam-operator
  - image: quay.io/opencloudio/ibm-iam-operator-bundle
  - image: quay.io/opencloudio/ibm-iam-policy-operator-bundle
  - image: quay.io/opencloudio/ibm-ingress-nginx-operator
  - image: quay.io/opencloudio/ibm-ingress-nginx-operator-bundle
  - image: quay.io/opencloudio/ibm-license-service-reporter
  - image: quay.io/opencloudio/ibm-license-service-reporter-ui
  - image: quay.io/opencloudio/ibm-licensing
  - image: quay.io/opencloudio/ibm-licensing-operator
  - image: quay.io/opencloudio/ibm-licensing-operator-bundle
  - image: quay.io/opencloudio/ibm-licensing-usage
  - image: quay.io/opencloudio/ibm-management-ingress-operator
  - image: quay.io/opencloudio/ibm-management-ingress-operator-bundle
  - image: quay.io/opencloudio/ibm-metering-operator
  - image: quay.io/opencloudio/ibm-metering-operator-bundle
  - image: quay.io/opencloudio/ibm-mongodb
  - image: quay.io/opencloudio/ibm-mongodb-exporter
  - image: quay.io/opencloudio/ibm-mongodb-install
  - image: quay.io/opencloudio/ibm-mongodb-operator
  - image: quay.io/opencloudio/ibm-mongodb-operator-bundle
  - image: quay.io/opencloudio/ibm-monitoring-exporters-operator
  - image: quay.io/opencloudio/ibm-monitoring-exporters-operator-bundle
  - image: quay.io/opencloudio/ibm-monitoring-grafana-operator
  - image: quay.io/opencloudio/ibm-monitoring-grafana-operator-bundle
  - image: quay.io/opencloudio/ibm-monitoring-prometheusext-operator
  - image: quay.io/opencloudio/ibm-monitoring-prometheus-operator-ext-bundle
  - image: quay.io/opencloudio/ibm-namespace-scope-operator
  - image: quay.io/opencloudio/ibm-namespace-scope-operator-bundle
  - image: quay.io/opencloudio/ibm-namespace-scope-operator-restricted-bundle
  - image: quay.io/opencloudio/ibm-platform-api-operator
  - image: quay.io/opencloudio/ibm-platform-api-operator-bundle
  - image: quay.io/opencloudio/ibm-postgresql
  - image: quay.io/opencloudio/ibm-secretshare-operator
  - image: quay.io/opencloudio/ibm-zen-cpp-operator
  - image: quay.io/opencloudio/ibm-zen-cpp-operator-bundle
  - image: quay.io/opencloudio/ibm-zen-operator
  - image: quay.io/opencloudio/ibm-zen-operator-bundle
  - image: quay.io/opencloudio/icp4data-nginx-repo
  - image: quay.io/opencloudio/icp-audit-service
  - image: quay.io/opencloudio/icp-catalog-ui
  - image: quay.io/opencloudio/icp-cert-manager-acmesolver
  - image: quay.io/opencloudio/icp-cert-manager-cainjector
  - image: quay.io/opencloudio/icp-cert-manager-controller
  - image: quay.io/opencloudio/icp-cert-manager-webhook
  - image: quay.io/opencloudio/icp-configmap-watcher
  - image: quay.io/opencloudio/icpd-requisite
  - image: quay.io/opencloudio/icp-elasticsearch-oss
  - image: quay.io/opencloudio/icp-filebeat-oss
  - image: quay.io/opencloudio/icp-helm-api
  - image: quay.io/opencloudio/icp-helm-repo
  - image: quay.io/opencloudio/icp-helm-rudder
  - image: quay.io/opencloudio/icp-iam-onboarding
  - image: quay.io/opencloudio/icp-identity-manager
  - image: quay.io/opencloudio/icp-identity-provider
  - image: quay.io/opencloudio/icp-initcontainer
  - image: quay.io/opencloudio/icp-kibana-oss
  - image: quay.io/opencloudio/icp-logstash-oss
  - image: quay.io/opencloudio/icp-management-ingress
  - image: quay.io/opencloudio/icp-memcached
  - image: quay.io/opencloudio/icp-oidcclient-watcher
  - image: quay.io/opencloudio/icp-platform-api
  - image: quay.io/opencloudio/icp-platform-auth
  - image: quay.io/opencloudio/icp-platform-header
  - image: quay.io/opencloudio/icp-secret-watcher
  - image: quay.io/opencloudio/indices-cleaner
  - image: quay.io/opencloudio/influxdb
  - image: quay.io/opencloudio/kubectl
  - image: quay.io/opencloudio/kube-state-metrics
  - image: quay.io/opencloudio/logging-pki-init
  - image: quay.io/opencloudio/metering-data-manager
  - image: quay.io/opencloudio/metering-mcmui
  - image: quay.io/opencloudio/metering-report
  - image: quay.io/opencloudio/metering-ui
  - image: quay.io/opencloudio/must-gather
  - image: quay.io/opencloudio/must-gather-service
  - image: quay.io/opencloudio/nginx-ingress-controller
  - image: quay.io/opencloudio/node-exporter
  - image: quay.io/opencloudio/odlm
  - image: quay.io/opencloudio/operand-deployment-lifecycle-manager-bundle
  - image: quay.io/opencloudio/privatecloud-usermgmt
  - image: quay.io/opencloudio/prometheus
  - image: quay.io/opencloudio/prometheus-config-reloader
  - image: quay.io/opencloudio/prometheus-controller
  - image: quay.io/opencloudio/prometheus-operator
  - image: quay.io/opencloudio/system-healthcheck-service
  - image: quay.io/opencloudio/tiller
  - image: quay.io/opencloudio/zen-audit
  - image: quay.io/opencloudio/zen-core
  - image: quay.io/opencloudio/zen-core-api
  - image: quay.io/opencloudio/zen-data-sorcerer
  - image: quay.io/opencloudio/zen-iam-config
  - image: quay.io/opencloudio/zen-influxdb-relay
  - image: quay.io/opencloudio/zen-metastoredb
  - image: quay.io/opencloudio/zen-watchdog
  - image: quay.io/openshift/origin-oauth-proxy
  - image: quay.io/redhat-developer/gitops-cli
