kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/optimizer/admin-ui:10.4.14-amd64@sha256:85a7562e7740c466135c15d4ac6c4b4008fed409d6bceb09c4567ba7c7ec395f
  - name: cp.icr.io/cp/optimizer/api:9.3.25-amd64@sha256:51042bd3fe237646b57b10f77443bfa597f10621f9f4dfe4bb4e2b67e3ab1376
  - name: cp.icr.io/cp/optimizer/execution-service:9.3.25-amd64@sha256:6f085fcd989c4944767d0c4869587869d35155e8d27868ea639caec025f610ec
  - name: cp.icr.io/cp/optimizer/ibm-mas-optimizer-appstatus:9.2.0-pre.stable_9869-amd64@sha256:4bd4a36d666c14078e78f1bacbd441bc45c7d5fe934de870285c2ca0e9fec7f0
  - name: cp.icr.io/cp/optimizer/ibm-mas-optimizer-primary-entity:9.2.0-pre.stable_9869-amd64@sha256:b06215baf2817d43509cc6940826e90d8bf94d2e0681812a0f368e7222910cc5
  - name: cp.icr.io/cp/optimizer/ibm-mas-optimizer-ws:9.2.0-pre.stable_9869-amd64@sha256:8c63a395a51dff9369c9b52c20ebea943ebc2140910959377fee5a3a1839686c
  - name: cp.icr.io/cp/optimizer/workspace-init:9.3.25-amd64@sha256:739e6f9f7584d7da09878665e2c1f850f8cd32d8d07d114d170455e312b9a5bd
  - name: icr.io/cpopen/ibm-mas-optimizer-operator-bundle:9.2.0-pre.stable_9869-amd64@sha256:0b657ec004b54e1c9a1a93047c661443b1d7296add75fe6d39a6bc59237ef6b7
  - name: icr.io/cpopen/ibm-mas-optimizer-webhook:9.2.0-pre.stable_9869-amd64@sha256:951262ebaf9cb71f1354c10fe415ffff523e71e45350c01acf9de9616c81df80
  - name: icr.io/cpopen/ibm-mas-optimizer:9.2.0-pre.stable_9869-amd64@sha256:cbcf9382e9f738db6decf420d41b726fea8589a4abc4a7923b9be5fd70818551
