kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-ssp-engine/ssp-engine-docker-image:6.1.0.3-iFix00-2026-01-19@sha256:0516c96af0840a7d912b762018d3abdb1b89359ef6f583e644f82501eac04d4a
