kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/aibroker/aibroker:1.2.9@sha256:7121df483e418a9a124b7749b9b034dbcaf85fd2222c3f3878f9d134e90caca7
  - name: cp.icr.io/cp/aibroker/controller:1.0.16@sha256:1193cc4ca314ce779b84cd20d96d8d14327f627ef142c14cf09867e3b89a84ac
  - name: cp.icr.io/cp/aibroker/maximo-fmea-common:1.0.1@sha256:5a82678cf2e931d738fcf89366e14f04032ce352914bfff2e7b9b7638c0b9dd2
  - name: cp.icr.io/cp/aibroker/maximo-fmea-common:1.0.2@sha256:a2f62ed64cb3389bc4c2bf28825231529b8d15f0020d624dd8fc31465285dcbd
  - name: cp.icr.io/cp/aibroker/maximo-fmea-common:1.0.3@sha256:4974f445cafebfddfad9eda58132c47116c7a273ff790d196eaae21d4cbe9df9
  - name: cp.icr.io/cp/aibroker/maximo-fmea-predictor:1.0.1@sha256:fa58563099695188fe3a3da4e6749fd8b42131f1e0612347c0c276d7ff466052
  - name: cp.icr.io/cp/aibroker/maximo-fmea-predictor:1.0.2@sha256:55514468444a5e037c286f96f767e7446c1f4eb91b901f6448165786e81863ab
  - name: cp.icr.io/cp/aibroker/maximo-fmea-predictor:1.0.3@sha256:24c4243def414ffce499ab84fd9de8b26ca0ba0ea6eaa9cbf01c6d88fd073b8b
  - name: cp.icr.io/cp/aibroker/maximo-mcc-common:1.1.1@sha256:592ae7598470d7959678e232c53d9caf04499e5ce163805114ebbdb7c4d1d32c
  - name: cp.icr.io/cp/aibroker/maximo-mcc-common:1.1.2@sha256:c4a42c255c6399a302c2e103422da5b5cc042db03f79fb96901a7f7f1137109b
  - name: cp.icr.io/cp/aibroker/maximo-mcc-common:1.1.3@sha256:070d0fbee370cf156444c9b581d5f7b2c33d9ba1f1930d5f23af0f1b73ad15a5
  - name: cp.icr.io/cp/aibroker/maximo-mcc-common:1.1.4@sha256:28ce7d098df18f3c06424a95ec6134326f75226988d013bd32a5f0e17e50fd04
  - name: cp.icr.io/cp/aibroker/maximo-mcc-predictor:1.1.1@sha256:5275a46a7284ffc6f265d8b9b97b0ed65ac65182172a0794b913bbf9e9c4f825
  - name: cp.icr.io/cp/aibroker/maximo-mcc-predictor:1.1.2@sha256:7ac6c8c581f854b5d98f213adaebcadd72b563de8c33e0657a48132e9dd21652
  - name: cp.icr.io/cp/aibroker/maximo-mcc-predictor:1.1.3@sha256:9d5b2b5258f5a57065a0314a5639f67ad63be89072120de551ed85dadadb8970
  - name: cp.icr.io/cp/aibroker/maximo-mcc-predictor:1.1.4@sha256:c9321002c05e2824d6ff6042a584dc01abf12dfd69d093696a02486e2eff09c8
  - name: cp.icr.io/cp/aibroker/maximo-mcc-train:1.1.1@sha256:06dc90fe732b612cd8749a603843d684bac3958149eb566c95ce6b27572ae6b5
  - name: cp.icr.io/cp/aibroker/maximo-mcc-train:1.1.2@sha256:bdab34506efc8d4f2c5a42153a70e4d0d02c2d5163e37e33756f9b83ab8536ef
  - name: cp.icr.io/cp/aibroker/maximo-mcc-train:1.1.3@sha256:acf5f157f9697ffabf22a390a6d85523e1f00e38f9c5eceed588c72444cff4bb
  - name: cp.icr.io/cp/aibroker/maximo-mcc-train:1.1.4@sha256:6810d687b7bb124546ac020406a6d33a4271612318974b66d2e5011d156384f7
  - name: cp.icr.io/cp/aibroker/maximo-nl2oslc-common:1.0.2@sha256:31c81dcb1c1840714dd40a1d0415bba4597746f410040498250434136e895c27
  - name: cp.icr.io/cp/aibroker/maximo-nl2oslc-common:1.0.4@sha256:e7aba1a9808b0a4a36f216f1c7d1eb26c370fa15843e27b33df2d324c1f1d86b
  - name: cp.icr.io/cp/aibroker/maximo-nl2oslc-common:1.0.5@sha256:71b82875877eb13c082ba696bed991e4f7037b50a4139acec774eeadce5fc0ad
  - name: cp.icr.io/cp/aibroker/maximo-nl2oslc-predictor:1.0.2@sha256:f12b7d4b7b4b2ff0533fc3619ff7cb3cb4eb9eb344fd7efd019dea1d349ed4aa
  - name: cp.icr.io/cp/aibroker/maximo-nl2oslc-predictor:1.0.4@sha256:0b351d0c9c2c67ed3ed75c99ce2955f53329ab3cea9ff61632aa1533459f473e
  - name: cp.icr.io/cp/aibroker/maximo-nl2oslc-predictor:1.0.5@sha256:ae586c24f27765bbe39c765654549853739174c4f72b4354fc6cba1266e3a4bd
  - name: cp.icr.io/cp/aibroker/maximo-pcc-common:1.2.1@sha256:db437e56885f91fa7e75cfc0ad830a101267af3cffbe9d806a1d1bef75a391ff
  - name: cp.icr.io/cp/aibroker/maximo-pcc-common:1.2.2@sha256:1f2a85bf715f272a3c853ed6c909fb6187cd1f21c407307e04689fddfc182eec
  - name: cp.icr.io/cp/aibroker/maximo-pcc-common:1.2.3@sha256:b8f7ed551e92c31dc684a14ef4f53bb96c9d855e9799b3496277722ae372af96
  - name: cp.icr.io/cp/aibroker/maximo-pcc-common:1.2.4@sha256:91423646e287b5fd01198fab25c3e0242b13792c508033d2bb11e26ea130232e
  - name: cp.icr.io/cp/aibroker/maximo-pcc-predictor:1.2.4@sha256:d23cd7d98a2c39044b38812a0c88de9e63c7b416d9615f446523594d71e7afa7
  - name: cp.icr.io/cp/aibroker/maximo-pcc-pretrained:1.2.1@sha256:3466c4066ebfca280e79f9df18f138f670a20f3b65cb35806d911fd5a9e05cbc
  - name: cp.icr.io/cp/aibroker/maximo-pcc-pretrained:1.2.2@sha256:616bf423dead48b87f776f43966f80710943b71f81aa36857be7abfaf71e506d
  - name: cp.icr.io/cp/aibroker/maximo-pcc-pretrained:1.2.3@sha256:97efb3088c843803d1d6827aa73fbae0b06fc09f40895d69f3c615a1a9d11612
  - name: cp.icr.io/cp/aibroker/maximo-pcc-pretrained:1.2.4@sha256:2c833ae7e6068f23fbca1164102c6245d7b2d2617fb86a54a0114ccc27c04f5f
  - name: cp.icr.io/cp/aibroker/maximo-pcc-train:1.2.1@sha256:47a2a9479fa63fe5e815af2b531ff308ead2962be6a4faafcd03cbcb84270b1b
  - name: cp.icr.io/cp/aibroker/maximo-pcc-train:1.2.2@sha256:7e29cfd51bcbb131fb826f38a0c9ff77c6f006e3618ba0838cf141898b82c7d0
  - name: cp.icr.io/cp/aibroker/maximo-pcc-train:1.2.3@sha256:3dd75eb0d5db3c01844b849f4be4b07e4510500e5c61cc9dd8d68b2db4fe9ca9
  - name: cp.icr.io/cp/aibroker/maximo-pcc-train:1.2.4@sha256:50ddf316288110bc9b7ef39933e476b7995422a327e3935461396ad12fe180ce
  - name: cp.icr.io/cp/aibroker/maximo-similarity-common:1.0.1@sha256:ae43e38008ce5086151a97825d379345a1be1af5b1b8446e19fe767e7f83b52e
  - name: cp.icr.io/cp/aibroker/maximo-similarity-common:1.0.2@sha256:3e1310480367660710138920bc92f05cf37c1c9eff8f2335144141a686ea61ea
  - name: cp.icr.io/cp/aibroker/maximo-similarity-predictor:1.0.1@sha256:62727a8c59617f576decb368aa550e248c02a76d1add4b203e98d8b0640b72e4
  - name: cp.icr.io/cp/aibroker/maximo-similarity-predictor:1.0.2@sha256:f1e07f38c5d95e645ad33659c9ebd95b6d52df9c16bc336691a3fd98829746ed
  - name: cp.icr.io/cp/aibroker/maximo-similarity-train:1.0.1@sha256:22b2e499254a49f3b4b387100c1492b77ee1d985677f4cd31a62fde6fc2b6a7c
  - name: cp.icr.io/cp/aibroker/maximo-similarity-train:1.0.2@sha256:23985840e5c5afe87314acc6dc3b0498ce643bc7acd30bec4038e04ee9bc5e94
  - name: cp.icr.io/cp/aibroker/s3:1.0.4@sha256:ae384da4fef9467c8a6c6d80c431e71c46a0334d865b0ce92b5eade9ecf31c0f
  - name: cp.icr.io/cp/aibroker/store:1.0.17@sha256:c0543d14eafe96ecbc9f5d8bad843f9ec2efc5b1c5072630ff02ae42d2534540
  - name: cp.icr.io/cp/aibroker/watcher:1.0.6@sha256:3f53007c095a138f4d4f50a7e3764f5013112ee3e6edee3a07059c1a119f0d45
  - name: cp.icr.io/cp/aiservice/ibm-aiservice-tenant:9.1.11@sha256:668243650c087bb0f022d9088b915d61731379af97fe06d38bd39a6c884c00a4
  - name: icr.io/cpopen/ibm-aiservice-operator-bundle:9.1.11@sha256:c38051429e5bfad8c2d639d22f22181fa978b94b50c55f906c101c81f2eb42b1
  - name: icr.io/cpopen/ibm-aiservice:9.1.11@sha256:ddcdbdede6d0888309e1fedb5ee1dab9128e2da8a338f5bf0e0edc381c9e3e2f
