kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/mas/kubectl:5.0.20@sha256:61bc875d64a472380e690ea485300b35c0491aaf68368664831a2a8db8161bbe
  - name: cp.icr.io/cp/predict/explainability:1.7.12@sha256:e3578ea0c0616a0bf62714c1da1d933df35a53c7b805f17cedc74307cce20fba
  - name: cp.icr.io/cp/predict/ibm-mas-predict-ws:8.9.15@sha256:6dc4e066a5dc064b837af86b16891f711ec57162a28f4bca7c4a584f2a60ada7
  - name: cp.icr.io/cp/predict/mat-service:1.5.3@sha256:82b8c8d7e6fd4fb05d50513fe9141217264aba6fa20dce1fb9a3af12b2153080
  - name: cp.icr.io/cp/predict/predict-api:5.9.19@sha256:f54ded752cd809dd678e19f0bb7545e40bf5fa71179624b9291271ff0d0eef91
  - name: icr.io/cpopen/ibm-mas-predict-operator-bundle:8.9.15@sha256:dbfe1036dfde3c223999d3ea464cb894232e166f16f7cb02b30aae81adbfcc68
  - name: icr.io/cpopen/ibm-mas-predict:8.9.15@sha256:effe5e3117449a05f95f055d2c34c04767569bf7a7eca3c9106fa7436cca387c
