kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: icr.io/cpopen/ibmcloud-object-storage-driver:1.9.6@sha256:4b5258bc8b9a13d743e15b6919a1570b7d307d4deb4d3f62c24fae9e52737348
  - name: icr.io/cpopen/ibmcloud-object-storage-plugin:1.9.6@sha256:f64d8b083357b4faa8dfaa8532c434d7dff2ac4624fa430b68b3e328dccaccda
