kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/appc/ace-kube-mcp-prod:13.0.6.2-r1-20260218-102906@sha256:0c75110fb13e98393cb4835b7a21ef15865c130152146b130ebf6f39600c26f4
  - name: cp.icr.io/cp/appc/ace-langgraph-agents-prod:13.0.6.2-r1-20260224-165852@sha256:1d459b46f4c5ad44411d267ed9ac9c98f4b96da26f4361771322aa5856fa1941
  - name: cp.icr.io/cp/appc/ace-mcp-prod:13.0.6.2-r1-20260218-102816@sha256:90424b2edd14b6e9db1a6a740b262ed9010b3aad3b0d7b8c2c4177ddb8bab576
  - name: cp.icr.io/cp/appc/ace-server-prod:13.0.6.2-r1-20260224-175720@sha256:defa024ee65d52b6d54bcabafaa8d8e58bdf34fed802bb2fbfa20796809f6053
  - name: cp.icr.io/cp/appc/acecc-content-server-prod:13.0.6.2-r1-20260222-011707@sha256:d421f65a60eba0a6ae2a930e09661231fcfc78ff3fdbcd23291e6c9f06e4a682
  - name: cp.icr.io/cp/appc/acecc-couchdb3-prod:13.0.6.2-r1-20260218-020011@sha256:01ead5030e75ae81f816afbaa8786d83c05974b4951485ec8a8a85fe8c76f4a6
  - name: cp.icr.io/cp/appc/acecc-dashboard-prod:13.0.6.2-r1-20260224-092234@sha256:c84b0cad82ff3a3bb91b5625176d81db38589d961c4d7983ea371a4874856257
  - name: cp.icr.io/cp/appc/acecc-designer-ui-prod:13.0.6.2-r1-20260218-022414@sha256:365d5f6c2be726fbabcdc05f9ef2649083acf04639fa7dff1d5c0439f385226d
  - name: cp.icr.io/cp/appc/acecc-designerflows-prod:13.0.6.2-r1-20260224-122412@sha256:af2ed749f4daac8068fb7c1e22c69677d1ad4d8f73255826da803e577d841f32
  - name: cp.icr.io/cp/appc/acecc-ecp-prod:13.0.6.2-r1-20260217-030029@sha256:4a43132ad40546862724ea2850370578b0d779298233baee29b06b2fc31616f0
  - name: cp.icr.io/cp/appc/acecc-mapping-assist-prod:13.0.6.2-r1-20260218-040013@sha256:e8769a73cfcadc3fe6910d4c00ecaa6a1325b0f8e167ba8e880abbd41d0c94a1
  - name: cp.icr.io/cp/appc/acecc-proxy-prod:13.0.6.2-r1-20260218-021210@sha256:ca63b44335b99a45778ae9db1cd9110e8ed43d37ec6d404b0ff71eeb204f9fd3
  - name: cp.icr.io/cp/appc/acecc-velero-plugin-prod:13.0.6.2-r1-20260218-030243@sha256:2985f3bda7a1672070f741810ad9dc4d7c880ad99738a4779e20875daacf59c8
  - name: icr.io/cpopen/appconnect-operator-bundle:12.21.0-20260225-095940@sha256:2dde5be793a2faa40177cfc45b8af7d413c5e0837ca34357adf9ec32fc5f70db
  - name: icr.io/cpopen/appconnect-operator-catalog:12.21.0-20260225-095940@sha256:e85b0bc75be49ce3cc367ccd25e76a2c8e1c4214519f6e96a0d318461489490b
  - name: icr.io/cpopen/appconnect-operator:12.21.0-20260225-095940@sha256:d8636f2f558ced3c085cbe635a8d47e9e587407e2f7bf5aaf453340a500f3600
