kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/go-proxy:v0.1.0-222.11079fa821fc-wxai@sha256:40a813ac28371037c7cb3753295d61f70eeeb7742cf629d30c2753874497b03a
  - name: cp.icr.io/cp/ibm-redis-cp-haproxy:1.3.0@sha256:3a0bb5ff85021008d759ff9f1e929c09c88030e5b60fa062be322990c0f55d20
  - name: cp.icr.io/cp/ibm-redis-cp-operand:1.3.0@sha256:ced717712afe438da9229bf4fd8b09e294671e96d3702446b0e99cff6f0f3b60
  - name: icr.io/cpopen/ibm-cpd-model-gateway-operator:12.1.0-20260209.201226@sha256:d8d65bb98689c930c867d84c2aed22b38ad8c2e2773c6bf385357bca2d4c1525
  - name: icr.io/cpopen/ibm-redis-cp-operator-bundle:1.3.0@sha256:bbe57e78b1e6e6a5b45bc3f3442a4c17ca4d04aeba6196d441c2e908da310d0c
  - name: icr.io/cpopen/ibm-redis-cp-operator-catalog:1.3.0@sha256:00223a7a97a63d51c6fdf3bae1dcd6abe7c4509abb6f47f13a96ae8532412441
  - name: icr.io/cpopen/ibm-redis-cp-operator:1.3.0@sha256:3ed0ec48c181ac76797999505e2f78ee4b26d58c78c8361516297b275b4b4e1c
