kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/go-proxy:v0.1.0-222.11079fa821fc-wxai@sha256:40a813ac28371037c7cb3753295d61f70eeeb7742cf629d30c2753874497b03a
  - name: icr.io/cpopen/ibm-cpd-model-gateway-operator:12.1.0-20260209.201226@sha256:d8d65bb98689c930c867d84c2aed22b38ad8c2e2773c6bf385357bca2d4c1525
