kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/zen-database-core:5.3.1-3673-amd64@sha256:0349b16e4d5ad4662d5ec32b86dfb754fed2742d68735c26ccf849072aa281a6
  - name: cp.icr.io/cp/cpd/zen-database-core:5.3.1-3673-ppc64le@sha256:719669d4afb2b2ace48794a03d80519d493c33b72978e8ff0128a8ebec235198
  - name: cp.icr.io/cp/cpd/zen-database-core:5.3.1-3673-s390x@sha256:b6c0928a017cad696cede1019a66a69fb1475225fe99d6a5d96c31a305b71e5e
  - name: cp.icr.io/cp/cpd/zen-databases:5.3.1-3673-amd64@sha256:4f9b1344058b92b0c182810ccc9d5fed549652450bc1687da1d9baf3920e8450
  - name: cp.icr.io/cp/cpd/zen-databases:5.3.1-3673-ppc64le@sha256:dd19bb3c80618d540a1a4ed8f344ff314879d616ccee128bc3b55489a65fd7f5
  - name: cp.icr.io/cp/cpd/zen-databases:5.3.1-3673-s390x@sha256:4c4c3a4a400c236e1fc37f19311c7fce86777f942a4b21eb30875d8eea69d009
  - name: icr.io/cpopen/ibm-db2oltp-cp4d-operator-bundle:5.3.1-4966@sha256:402deea363bf7f248be03f4b145cfc63194cfcca4f26baa312af6c678d484cb7
  - name: icr.io/cpopen/ibm-db2oltp-cp4d-operator-catalog:5.3.1-4966@sha256:5ae262a5f7e211f0d18fc974d711abb28d003ff6e6928389da03887bdce77ccd
  - name: icr.io/cpopen/ibm-db2oltp-cp4d-operator:5.3.1-4966@sha256:e4d6810dba58ece8b7dca30d046286fd26cae897c3454a9bea31bcf62152af80
