kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-ssp-cm/ssp-cm-docker-image:6.2.0.3-iFix00-2026-01-19@sha256:3b662740a45dceeb05fd6cdec43dc37fe570bbdef74867b5435035d31c521388
