kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-seas/seas-docker-image:6.1.0.4-iFix00-2026-01-19@sha256:23c5686b45ef156320e481d1937e428f0174598f67012cd2dd024712bd1574de
