kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/openpages-cpd-addon-translations:9.1.3.1-730@sha256:9b9d34ad12d732366539b82c285911702697e99586b46b5eb132486976449531
  - name: cp.icr.io/cp/cpd/openpages-cpd-cognos-service:9.1.3.1-730@sha256:ea930a64d2a2bd88e8d282a620612279987154c8374086b5bd3a609c9ffc676d
  - name: cp.icr.io/cp/cpd/openpages-cpd-opapp:9.1.3.1-730@sha256:77a27dc0ef19ca7cb26185ad8021d2c81d1d5714f80aeffd74f45f8d7742df3c
  - name: cp.icr.io/cp/cpd/openpages-cpd-opappaudit:9.1.3.1-730@sha256:512963b50ca328cedbd9d2b1be23489d37d29f609c8e6ab49710f476194defab
  - name: cp.icr.io/cp/cpd/openpages-cpd-opsearch:9.1.3.1-730@sha256:9b5858fb7f14eb07f3fd893b2bc0b52f14452e36440de394185ada8f44e1bcb1
  - name: cp.icr.io/cp/cpd/openpages-cpd-provisioner-oracle:9.1.3.1-730@sha256:d237d7b586ef3cb7b7bc50828e01ca61f7c8d4ef70c08b00613f73a563b9dbe9
  - name: cp.icr.io/cp/cpd/openpages-cpd-provisioner:9.1.3.1-730@sha256:406b4c0479e2da083adf0486a1d195af7e0aa7c45971065b8177211e1712e0a1
  - name: cp.icr.io/cp/cpd/openpages-cpd-user-sync:9.1.3.1-730@sha256:24965db77e9f0353984e915928582505c83b88ee9bfd15a7b1104af2121a5c61
  - name: icr.io/cpopen/ibm-cpd-openpages-operator-bundle:9.1.3.1-730@sha256:93b8a2a733bca186f94a391527623157a7a5daf2062791125948758cc1d61e84
  - name: icr.io/cpopen/ibm-cpd-openpages-operator-catalog:9.1.3.1-730@sha256:be9595715635981b815344e9c7ef627f46fd3db0458da5135a0e6b7fdfc725a6
  - name: icr.io/cpopen/ibm-cpd-openpages-operator:9.1.3.1-730@sha256:a70aff9a17a66685a44673eea1ab4f0c6d67eb48d6ef3cf73f30c8d7eb025e94
