kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/informix-api:10.1.0-0000-x86_64@sha256:5f39c3b019571be49b973e8f6615151f02701b3bd67152bf45fb102109a6f4fa
  - name: cp.icr.io/cp/cpd/informix-cm:10.1.0-0000-x86_64@sha256:dcb37480c4b719b0a1a43823aaa3d68db2543d8d15059912324f393c68219340
  - name: cp.icr.io/cp/cpd/informix-edition-aee:10.1.0-0000-x86_64@sha256:5dad78f916ebf395c72dc30b7380e6eed907648ce30aadc0a2ad71c779862a47
  - name: cp.icr.io/cp/cpd/informix-edition-de:10.1.0-0000-x86_64@sha256:4c7b694019bbda81671aaa42607759c7599643dac405a9156453775c0c683d09
  - name: cp.icr.io/cp/cpd/informix-edition-ee:10.1.0-0000-x86_64@sha256:4fb32dc11d748e139333a7efc71d4c111435eeda122a7401d3c083dc432472b0
  - name: cp.icr.io/cp/cpd/informix-edition-we:10.1.0-0000-x86_64@sha256:a5c32174493603707e0b295c6753e3d9e1cb9ab53289bbe6f2c2ba58cbadabc7
  - name: cp.icr.io/cp/cpd/informix-eng:10.1.0-0000-x86_64@sha256:237d8f086e97504b6423977259d4c634d6696beafb640d052a690da84055d6b6
  - name: cp.icr.io/cp/cpd/informix-hq:10.1.0-0000-x86_64@sha256:ff50eb2567e3f4d241e7fb6769e46b128a8ff143d19ab502a1c53a2e9259c4b8
  - name: cp.icr.io/cp/cpd/informix-wl:10.1.0-0000-x86_64@sha256:8f949a1b39e5bcaac53ac55fe52802c6a0c71cf83e672d02b6c6f91372cd4571
  - name: icr.io/cpopen/ibm-informix-operator-bundle:10.1.0-0000-x86_64@sha256:a1f80f50ae47bc2ea8cc94be868cdb6bc5551aaa06ebd0ff27d93ec0bf8976bf
  - name: icr.io/cpopen/ibm-informix-operator:10.1.0-0000-x86_64@sha256:45230d4c5fb3d430be66eff290a5cbc83995085a1e21bd3e726870d182aadc98
