# Default values for ez-helm-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  dockerRegistryPrefix: ""
  requisiteImage: guardium_external_s-tap
  requisiteTag: cpd-3.5-deploy-11.2.2-38
  editor: "cpd-editor-sa"
  cloudpakVersion: "3.5.0"

estap:
  version: "11.2.0"
