kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/facilities/datainit:9.1.6@sha256:1ebd8d123aef1d981de3289e664f1ce9fadfa3462bf1bf009824f46aef677be9
  - name: cp.icr.io/cp/facilities/ibm-mas-facilities-ws:9.1.7@sha256:7d03c0ad9ef5bc2aa67413bff891df3dd2784427a0103d9ad78cc57dfe23bbdf
  - name: cp.icr.io/cp/facilities/platform:9.1.7@sha256:e856aff18f5a107352de30893ba46ac8d016be4a01a3d798cb4dfb706e9f0c86
  - name: cp.icr.io/cp/facilities/usersyncagent:1.0.2@sha256:7980b168503581e8cdbdb52d4d7f113fa7807baf9926ebec4b514fb62684625a
  - name: icr.io/cpopen/ibm-mas-facilities-operator-bundle:9.1.7@sha256:78f3fd420ce806cc80d95ef422ec46c1eb20b3f53290934bf9e099b792deae79
  - name: icr.io/cpopen/ibm-mas-facilities:9.1.7@sha256:3230abc220ddfacc3e0bc238ec58cb92d23281226e5f23bef771bffa147a64a6
