kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/ibm-wca-z-code-generation:1.25.93@sha256:624ebf76cd8a0f9f0b4c6b0f81f3bdc89d26fac743aea8714c124428129b487a
  - name: cp.icr.io/cp/cpd/ibm-wca-z-model-gateway:1.0.141@sha256:564d11b427ed1e2d8ccf9115db83a1e78ad62204237256ab5fe9a7f28fb58955
  - name: icr.io/cpopen/ibm-wca-z-code-generation-catalog:1.1.1@sha256:3db6d0fcfb024cacfaa08a2d5ded9026a70d3dff2e270fea327fd9a31c302195
  - name: icr.io/cpopen/ibm-wca-z-code-generation-operator-bundle:1.1.1@sha256:8e2ffae7877d6df55d4233681367c0afd796995f702bfa32972f76e2afbeebf7
  - name: icr.io/cpopen/ibm-wca-z-code-generation-operator:1.1.1@sha256:145f263efa9d8d68bb160fca7b570082d12ef570c4ec793049155a7a315a8a9d
