kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/edb-postgres-license-provider:2686@sha256:bd60720f4a317cae809f1bc345e1582b7f9caadf28c0aede9b370c64cf521bf4
  - name: icr.io/cpopen/common-service-operator:4.17.0@sha256:c7e5c395eee7a2fb206001e9e64c618b721229652497b6f219031e7bba9ea7c2
  - name: icr.io/cpopen/cpfs/cpfs-oadp-plugins:latest@sha256:fef318c13b669d66559119ec6cf3815277be454dd940d4fcd17e1aca6a7338aa
  - name: icr.io/cpopen/cpfs/cpfs-utils:latest@sha256:0e233871278ff2e61d9fa779fab6828f643bc852cbc4aef62aac8c65329232be
  - name: icr.io/cpopen/cpfs/must-gather:latest@sha256:306c6a0f7370164a2b0fb533128a24a9ade48321ef20b4e0218a4cb9c2a4e2fd
  - name: icr.io/cpopen/edb/postgresql:13.23-5.31.0-cpfs@sha256:353d13d874d60f7dff5dba2b080e8b127d54f3d71f9c5421f3895d737a604d41
  - name: icr.io/cpopen/edb/postgresql:14.20-5.31.0-cpfs@sha256:5b9e17fa0f210e78622e965d4da7f79c20b99cf8db507451e5453dd4c3dab8b7
  - name: icr.io/cpopen/edb/postgresql:15.15-5.31.0-cpfs@sha256:425de739fb88db833881eb0c1c9db7408059bec5b5f45830c92e5de4b4ebbddc
  - name: icr.io/cpopen/edb/postgresql:16.11-5.31.0-cpfs@sha256:b711c28ad678c53fae114a3b80b801979dd30cf4b7f6676db0db5c9987e377d3
  - name: icr.io/cpopen/edb/postgresql:17.7-5.31.0-cpfs@sha256:4becaff092407bf0c4a55b921c1ff8a9f2e4cb2b53c339eea41269ee38a21f12
  - name: icr.io/cpopen/edb/postgresql:18.1-5.31.0-cpfs@sha256:022b2d0beb9ae959ddd7c06038a4369f935fc07edc9cd288bc019d81b6ef1a49
  - name: icr.io/cpopen/ibm-common-service-catalog:v4.17.0@sha256:de97dd2a35b4c58da9b7ad5d89976d7a4184541e2e0a78a1c71e441a0105ce6e
  - name: icr.io/cpopen/ibm-common-service-operator-bundle:4.17.0@sha256:92ce68100f512f92cd09e3a515b34a845d3218d05c68830caf72e671806c9acd
  - name: icr.io/cpopen/ibm-namespace-scope-operator-bundle:4.3.4@sha256:f972e1ba9d168dc0fc01b34b0de43c846499b100e4f0342e4d8268c57658b90c
  - name: icr.io/cpopen/ibm-namespace-scope-operator:4.3.4@sha256:fd38c61ca39b7819fb42c5da8cc6e8b36abb5552bd9163d6051b0f9db8776904
  - name: icr.io/cpopen/odlm:4.5.6@sha256:b7b114bbb707a2f8e12cdbe699a0eab40624e7f26d733072a7f0875e662ceab9
  - name: icr.io/cpopen/operand-deployment-lifecycle-manager-bundle:4.5.6@sha256:053240d08dc4301c52bf094820a368a863eed21e34f50c8413c7d1710a64c1c4
