kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/aibroker/aibroker:1.3.1@sha256:d399c00d6e9179710ad9ec4aef74afa5a479b953859fb50226bd6bd7d3975ebe
  - name: cp.icr.io/cp/aibroker/controller:1.0.16@sha256:1193cc4ca314ce779b84cd20d96d8d14327f627ef142c14cf09867e3b89a84ac
  - name: cp.icr.io/cp/aibroker/maximo-fmea-common:1.1.0@sha256:b3fbc838a80ad09f1276a4c21c1b0dd510d37547938799a44d9f13dbf8bdede1
  - name: cp.icr.io/cp/aibroker/maximo-fmea-common:1.2.0@sha256:23cc2a97f1b4879d175e261b469f48602c3621f04068c4b80cef3a221fc3cff6
  - name: cp.icr.io/cp/aibroker/maximo-fmea-predictor:1.1.0@sha256:ac2bee7a6324661b1a11c636d1a162d4c5db0db62d4d6443ace14134e03554f3
  - name: cp.icr.io/cp/aibroker/maximo-fmea-predictor:1.2.0@sha256:04be937f55c45d3ed73c08e066a432feeeab845430bb7d97172ecf967ecd4bf8
  - name: cp.icr.io/cp/aibroker/maximo-insights-common:1.0.0@sha256:73ba12f587600fe2405ee095f52afe927233d5cc9e4569b9216e57b112ab866f
  - name: cp.icr.io/cp/aibroker/maximo-insights-predictor:1.0.0@sha256:a314905363f761e91d9133767a2cf92c786c7bb0e4b5cec812151b5fee608f28
  - name: cp.icr.io/cp/aibroker/maximo-mcc-common:1.3.0@sha256:3e863af62725e666eef0ca2b685cfc90d1676395ff596887d852d167498b4fb7
  - name: cp.icr.io/cp/aibroker/maximo-mcc-common:1.4.0@sha256:c4d51d816ea3b180e9cf12508e9e2a32beebe1a971b82ce4dca8be766ed05478
  - name: cp.icr.io/cp/aibroker/maximo-mcc-predictor:1.3.0@sha256:151e80015498883afd5fd7665143ae5864490d0c205e831574029f9780ca1bdd
  - name: cp.icr.io/cp/aibroker/maximo-mcc-predictor:1.4.0@sha256:9e13de8920f2013ed938cf41cad428ed183c40716fba2e0214d4119554e69319
  - name: cp.icr.io/cp/aibroker/maximo-mcc-train:1.3.0@sha256:b0f0d419e1d1b1725646cb2d1f4ada2faed3f53648c858f1d8bca7f4c7323296
  - name: cp.icr.io/cp/aibroker/maximo-mcc-train:1.4.0@sha256:0b3d76bf9134933ca0e210577267f58e7d371a8f3dd6067c9c30f03b7e2ee2ee
  - name: cp.icr.io/cp/aibroker/maximo-nl2oslc-common:1.0.4@sha256:e7aba1a9808b0a4a36f216f1c7d1eb26c370fa15843e27b33df2d324c1f1d86b
  - name: cp.icr.io/cp/aibroker/maximo-nl2oslc-common:1.1.0@sha256:9911f68cdab8feac729047198639699308634269d4c2ac683e48de3a4d29b440
  - name: cp.icr.io/cp/aibroker/maximo-nl2oslc-predictor:1.0.4@sha256:0b351d0c9c2c67ed3ed75c99ce2955f53329ab3cea9ff61632aa1533459f473e
  - name: cp.icr.io/cp/aibroker/maximo-nl2oslc-predictor:1.1.0@sha256:97bc83d5560a440b89aecc02e4d6aad25cd1f0500f00c3f96df5f4f1b2af4710
  - name: cp.icr.io/cp/aibroker/maximo-pcc-common:1.4.0@sha256:88e48fcd8c025705cff531294217af90ea883f9b10e323997601a59a4a0f1b95
  - name: cp.icr.io/cp/aibroker/maximo-pcc-common:1.5.0@sha256:175cbf0e600bfbc09a2e62e283b8597167021f54b7e85107bf36af140a0367a5
  - name: cp.icr.io/cp/aibroker/maximo-pcc-predictor:1.4.0@sha256:d3dfd7f8d410c1bf832755ac2fbd551ea3427acc53365eb33f934d29bbd95064
  - name: cp.icr.io/cp/aibroker/maximo-pcc-predictor:1.5.0@sha256:8f10a3bfdbf93dcd182d48b306aa064da7c87257e661ac0fe80ad97333826685
  - name: cp.icr.io/cp/aibroker/maximo-pcc-pretrained:1.4.0@sha256:e5e8b026a0f4b9e9796a4e983527c27e28c3eb448b8c291d9c83ce12d9156810
  - name: cp.icr.io/cp/aibroker/maximo-pcc-pretrained:1.5.0@sha256:e66cc4f4781bcd65af09b76a762f556a339a8fbf22bf351fd3535182961924ef
  - name: cp.icr.io/cp/aibroker/maximo-pcc-train:1.4.0@sha256:b8948b0791fe380875ab743ed49c421a9728d5100b3f06fc7dd04aa73586deab
  - name: cp.icr.io/cp/aibroker/maximo-pcc-train:1.5.0@sha256:c87a14079a595dde8a313094d9ea8e91b65f52ccc38db80b535386913a564343
  - name: cp.icr.io/cp/aibroker/maximo-similarity-common:1.0.2@sha256:3e1310480367660710138920bc92f05cf37c1c9eff8f2335144141a686ea61ea
  - name: cp.icr.io/cp/aibroker/maximo-similarity-predictor:1.0.2@sha256:f1e07f38c5d95e645ad33659c9ebd95b6d52df9c16bc336691a3fd98829746ed
  - name: cp.icr.io/cp/aibroker/maximo-similarity-train:1.0.2@sha256:23985840e5c5afe87314acc6dc3b0498ce643bc7acd30bec4038e04ee9bc5e94
  - name: cp.icr.io/cp/aibroker/s3:1.0.4@sha256:ae384da4fef9467c8a6c6d80c431e71c46a0334d865b0ce92b5eade9ecf31c0f
  - name: cp.icr.io/cp/aibroker/store:1.3.0@sha256:40a8eddf3187661c18b7f2b8ef72bd5a02a3373c7ba2c87148bd4324f88e12e8
  - name: cp.icr.io/cp/aibroker/watcher:1.0.6@sha256:3f53007c095a138f4d4f50a7e3764f5013112ee3e6edee3a07059c1a119f0d45
  - name: cp.icr.io/cp/aiservice/ibm-aiservice-tenant:9.2.0-pre.stable_12908@sha256:44ba6343cc68f0ba03f3d9a3f8750b50a45f9a16cb1dacaabb6b89d716adf03b
  - name: icr.io/cpopen/ibm-aiservice-operator-bundle:9.2.0-pre.stable_12908@sha256:182a0a7f0893be97025b54489e1dfaec991003c05d4bb1ff52bb70c25fc2c5e8
  - name: icr.io/cpopen/ibm-aiservice:9.2.0-pre.stable_12908@sha256:58c757849a9acc501515d212be96a988d92f11df0dbba7fcfd14a51f3213c93a
