kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/artifacts:2.3.110@sha256:5f054f5801727505b25b123ab13a6f517eda84e86de79f0402e6ce9cc8d57ac1
  - name: cp.icr.io/cp/cpd/ca-cpd-addon-translation:v29.1.0-10442@sha256:a5dc8cd595d74fc0e390a9ea8251d3599129bf80c2a94fa33e2dd279de5d2d6a
  - name: cp.icr.io/cp/cpd/ca-cpd-cm:12.1.1-2601221241@sha256:31ed3d8262106e797146f4abb835e81e61aa80588b8bb141771eb65230e34b01
  - name: cp.icr.io/cp/cpd/ca-cpd-reporting:12.1.1-2601301215@sha256:de8409884b71d6a880da1ceb0b8ac784bdcb98665617d3bf860f4c38f59f4cf8
  - name: cp.icr.io/cp/cpd/ca-cpd-rest:12.1.1-2601221241@sha256:1c88cc7946e92ae3b29f2302553779ea05980ae711ea3641bda3c1d71fa2062a
  - name: cp.icr.io/cp/cpd/ca-cpd-smarts:12.1.1-2601221241@sha256:beeca18c62bd582bcb6e0b9c942fa2da17bc09a72f85ed317f3a3611861a3fb9
  - name: cp.icr.io/cp/cpd/ca-cpd-ubi-lite:12.1.1-2601301101@sha256:6e1dd3c5fc845179aee455917f48298794900c92e420322e4015e80e84d25737
  - name: cp.icr.io/cp/cpd/ibm-cognos-addon-sp:2.1.6@sha256:6fd5824ad889a4f82a847bc49cbc2e006bc1fc39c3963742014c68c801fe4d79
  - name: icr.io/cpopen/ibm-ca-operator:v29.1.0-10442@sha256:140324870368ee56cdb9a1bff3d8331844400a0e38ed60bacba9eb1b043eb128
