kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: icr.io/cpopen/ibm-informix-cp4d-operator-bundle:10.1.0-0000-x86_64@sha256:65f25dcb6b21208062d9d48c069ecb5f159a40ba9bd3350e1716e41bdac4f38f
  - name: icr.io/cpopen/ibm-informix-cp4d-operator:10.1.0-0000-x86_64@sha256:5e4a38b065e7fb4b7cbb2adf1af1877d81f41172d488628a70dc171002b59903
