kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/df/ceph:v4.19.10-5@sha256:b2817cf2f2f0d0d9206f144cebff7b3a7925eb6dfa25f4e6bb548c21847a66e9
  - name: cp.icr.io/cp/df/cephcsi-rhel9:v4.19.10-5@sha256:7cd72fbddc59fde0227ec0f750ee1d1d7395a0a4ca756c4be2ce8547629c2142
  - name: cp.icr.io/cp/df/mcg-core-rhel9:v4.19.10-5@sha256:a7a5a6175db73197b49726d5831a583c8e27808d5ec827eda1a9c53f0baa8b0c
  - name: cp.icr.io/cp/df/ocs-client-console-rhel9:v4.19.10-5@sha256:5f8cbcff3b666679f72c8fef06768dfbe17ac5a738a03f3b9a405dc62b65abbe
  - name: cp.icr.io/cp/df/ocs-metrics-exporter-rhel9:v4.19.10-5@sha256:66c38bf07d60b266cca86e113e583ab0a73bf23ddb4875b081d716e3fe625fb3
  - name: cp.icr.io/cp/df/odf-console-rhel9:v4.19.10-5@sha256:446c2d1c074855f282995c409e6860a0acdea001f5d071ee4bcd00c2f1f20414
  - name: cp.icr.io/cp/df/odf-cosi-sidecar-rhel9:v4.19.10-5@sha256:22ef71cf08faa27e77a55bbe8f4dc658ca37fb12fe67a09c33dd953166a22e6b
  - name: cp.icr.io/cp/df/odf-csi-addons-sidecar-rhel9:v4.19.10-5@sha256:a8573b880f5a5e1f699a86963e805cb2833339b37e2bce70ce7e180635c4e7f6
  - name: cp.icr.io/cp/df/odf-multicluster-console-rhel9:v4.19.10-5@sha256:baa7d60a2037d0f9467284323d1b7330b918dca177a4e242eda1320ab353b91a
  - name: icr.io/cpopen/cephcsi-operator-bundle:v4.19.10-5@sha256:9e0844de625e58bf10bfb741733cb362ce30aa6e48d70521432dfd3838fadfb9
  - name: icr.io/cpopen/cephcsi-operator:v4.19.10-5@sha256:4f1a03162b0900bb8d59c1d251f15319991025fdab40f763c8c7b94c0cbfa8b9
  - name: icr.io/cpopen/isf-data-foundation-catalog:v4.19.10-5@sha256:e166ea79a29099ef5944f6619ec90fa7a7b3b00c55a7fcb59d40db59042e4d29
  - name: icr.io/cpopen/mcg-operator-bundle:v4.19.10-5@sha256:e2436fe529b97d931b0950bd80244f197e14e39b29ec59baa53e4dedd0dca0d9
  - name: icr.io/cpopen/mcg-operator:v4.19.10-5@sha256:db09df68507d9243c104a299cc3a2bc337809e3bb0bff7c902dab1701fcc3981
  - name: icr.io/cpopen/ocs-client-operator-bundle:v4.19.10-5@sha256:d4666df27a5f34043c5956e7a6cf2358863749fd74b791cc94683a57e0857b68
  - name: icr.io/cpopen/ocs-client-operator:v4.19.10-5@sha256:c9f200613369f8d545dead8f0a034817aef435bf1665597d7f4c1318e00388fc
  - name: icr.io/cpopen/ocs-operator-bundle:v4.19.10-5@sha256:09ef71e33b74b89e526680dce0ad58a8270c1801296849f89744d97ea1e0dbd3
  - name: icr.io/cpopen/ocs-operator:v4.19.10-5@sha256:eb881d436f02bb4e1932f20c2ec9b080150ca312860eb0f10238012d4658afde
  - name: icr.io/cpopen/odf-csi-addons-operator-bundle:v4.19.10-5@sha256:3dc6ad2b0b6e7653a5a3b63f60474ff76114ee367d5fec01897c97b77e7b184b
  - name: icr.io/cpopen/odf-csi-addons-operator:v4.19.10-5@sha256:a7a87ce312c4608ecba60ef084e2139cb4bd66fa75d4396f1230eb8123ada841
  - name: icr.io/cpopen/odf-dependencies-operator-bundle:v4.19.10-5@sha256:710fa72552e8330e0ba5ed73d2c3d51d7584bc47f58c0a9cfa47045228d73d10
  - name: icr.io/cpopen/odf-multicluster-operator-bundle:v4.19.10-5@sha256:6c8d39979f00182e492e2781048c38b87bddec841ecf9202286bfef0587d0a8d
  - name: icr.io/cpopen/odf-multicluster-operator:v4.19.10-5@sha256:e8747ee2048ee63d800723607c1129b92d43cc1a6b817c483cbb57b995b295d7
  - name: icr.io/cpopen/odf-must-gather:v4.19.10-5@sha256:88a72afce7a043f8eb45488333cf1a868b3126a2995a6456a2e64124b018fb55
  - name: icr.io/cpopen/odf-operator-bundle:v4.19.10-5@sha256:d176ab52125ab052f30986a6532afc9e8d505d82c1242c498a1f314042c92b45
  - name: icr.io/cpopen/odf-operator:v4.19.10-5@sha256:effa3384c724c3101ad5feff90a1f3bbadc1c5bdbf85ab9f31c09a80c8c5471a
  - name: icr.io/cpopen/odf-prometheus-operator-bundle:v4.19.10-5@sha256:5bebfc62120ac6cb03137b5327e4f7c833621977ac41a378f1e03248568873b6
  - name: icr.io/cpopen/odr-cluster-operator-bundle:v4.19.10-5@sha256:85e6e48e95a5d043899c80ff617d82e91c95950936fcb1bf903f3f55b5639a37
  - name: icr.io/cpopen/odr-hub-operator-bundle:v4.19.10-5@sha256:4574b928764276087b30813c7b1ba388370ad542a1f98226585b4d2537ea6ded
  - name: icr.io/cpopen/odr-operator:v4.19.10-5@sha256:5c0db00fc3a1278ab359b9dc9709900534603496c7b6ab1fed2577e6b18dccd5
  - name: icr.io/cpopen/odr-recipe-operator-bundle:v4.19.10-5@sha256:040ea09d999b75533a60ba32b6255e8e5e87c021d6ff0a0467150fe74cb4ea9b
  - name: icr.io/cpopen/rook-ceph-operator-bundle:v4.19.10-5@sha256:11932c52a2b9e7c7f4babbf89620e01c2fece63a46ae284ce7f1c2d190ee173e
  - name: icr.io/cpopen/rook-ceph-operator:v4.19.10-5@sha256:ba5f032d72a6441c0c2c793a37aea8b8174b3e4a99bdaff8a5ad4220437ab73c
