kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/ds-assets:531.0.4@sha256:71dffa418043e8e981ad307b6a6cc46620a129a17f01c6dc31e4ef607e9fb113
  - name: cp.icr.io/cp/cpd/ds-canvas:531.0.19@sha256:361accc1cfed5e72078f3296f5138ee0c3c15cf1dd12fe4ee4cea6a9084a0b92
  - name: cp.icr.io/cp/cpd/ds-cas-lite:531.0.4@sha256:bbea930cbd03db624fc0fdf1862ecc005d17efd2a2c9179f7cf2f21b432b29ef
  - name: cp.icr.io/cp/cpd/ds-dataservice:531.0.4@sha256:d055be7f668be3bef74d087102ac89cbbc584015789e23a3ae33047b6eca3ecb
  - name: cp.icr.io/cp/cpd/ds-flows:531.0.14@sha256:0a90fd99362a2ae5cd0574a76ef4f649bd5e5a8fd139f1d05c72a24174a1b1fc
  - name: cp.icr.io/cp/cpd/ds-metrics:531.0.4@sha256:eff7c4dfe44e643116fdcbd983edd571d05c45861a06069023b6df28f2a32a03
  - name: cp.icr.io/cp/cpd/ds-migration:531.0.5@sha256:cac1172cd62ad8997c665a0c568e05dca3d736da6f7e3d885bf549b6874639b7
  - name: cp.icr.io/cp/cpd/ds-nginx-proxy:5.3.1@sha256:f20d61b123f899fb5ec6c75caf6e1490b47776f94fdf1697710fff25708fbe77
  - name: cp.icr.io/cp/cpd/ds-px-compute:531.0.11@sha256:c1a358fc882d6a26c8c44187a2c902008fe26950621cd5bf079a9d558d7eb069
  - name: cp.icr.io/cp/cpd/ds-px-runtime:531.0.11@sha256:c1ce7f84d6fe8e58e9b54b56e19436122ba5487e8bedde532f791986870acc03
  - name: cp.icr.io/cp/cpd/ds-runtime:531.0.5@sha256:abf7e8fd8880a4c44d99e47e371caf9d22901060438a6404925b657271dabfe7
  - name: cp.icr.io/cp/cpd/qs-ruleset:531.0.4@sha256:ead15475329f24326e1c7ebeed1979e813d33421c2d36bdc7658b5f1191fbbda
  - name: icr.io/cpopen/ds-operator-bundle:5.3.1-100@sha256:4447a3ad8139f791003116707bee8c65e1e803f804524aff6fab06ca32d11a78
  - name: icr.io/cpopen/ds-operator-catalog:5.3.1-100@sha256:d14f94246c4aaf8cecf0ddf6586e739dba32e29767c5209865ad2a3d303c46b7
  - name: icr.io/cpopen/ds-operator:5.3.1-100@sha256:e4f64cdb62693e53459b13a55969aa714c6bcc1b14c8feb14ddeffc9045d60dd
