kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  operators:
  - catalog: icr.io/cpopen/opencontent-elasticsearch-operator-catalog@sha256:a34169228887ff93161584753c990bb82a5520ad7945dfa1ff4078e70aede592
    packages:
    - name: ibm-elasticsearch-operator
      channels:
      - name: v1.1
    full: true
  additionalImages:
  - name: cp.icr.io/cp/cpd/asset-files-api:4.8.1.89@sha256:f67456e773c4cd4c86897911c8aa711f285f5d2bb308b3943170e2856bebd799
  - name: cp.icr.io/cp/cpd/catalog-api-aux_master:2.0.0-20231130191046-9526e86f20@sha256:ce3e2016025af2d5fe7d583d5afe36e9ed23073cae7a50b4caa4d3bc1ba9e7cb
  - name: cp.icr.io/cp/cpd/catalog_master:2.0.0-20231130191046-9526e86f20@sha256:bebacc380b6d2917f05a262fac6949b69c4b3d79e1244e43f7804bde5bc8eca4
  - name: cp.icr.io/cp/cpd/couchdb3:3.3.2-104@sha256:cc8c5117c6b136854331ea7bbb15e4ff38aa70c6bbc01ecfc1c65efc5fcba5b2
  - name: cp.icr.io/cp/cpd/dap-base-job:4.8.1.33@sha256:55c3dcaaaa962fd9e905eb54c8b30d40c44ed89a3aafa4356f07a5354a4a4688
  - name: cp.icr.io/cp/cpd/dataview-api-service:4.8.1.103@sha256:a2b568467ef011a9229b52a21668f709771f03617934a8e7237c0e198cb92f22
  - name: cp.icr.io/cp/cpd/dc-main:1.0.26@sha256:82d00e87bb87c6a0642798d55ebe56b456dbeca2b5a12aea0b3b7386ce6a7480
  - name: cp.icr.io/cp/cpd/dsx-requisite:v4.8.1.2@sha256:6c37b5a96e09894591094e65b12a677f3dfb62c419a97fdc71e5bd384625c14e
  - name: cp.icr.io/cp/cpd/environment-specifications-sync:8.1.0011@sha256:0c11767686b908bb12fc1b585c8f60736cb21d3e00b39040e49dba13354fb2a4
  - name: cp.icr.io/cp/cpd/environments-api:8.1.0011@sha256:3381fc508155d43eda240e2426f5e52cb00d241a3c4f3cd4618d24710b2995ca
  - name: cp.icr.io/cp/cpd/environments-init-job:8.1.0011@sha256:7e8f983f9245dea8a4606a03709a5c9b851f3adb76e17a912d7fd02345a7f123
  - name: cp.icr.io/cp/cpd/environments-ui:8.1.0011@sha256:e462eab3d1aaaaafabf551d0087fdfd08f5de3bdf38f404394e6ba68af1332f3
  - name: cp.icr.io/cp/cpd/event-logger-api:4.8.1.35@sha256:b56b2d39240d25ffa88f0a67f0fab7ff6a8ca4eedbdb641f26e0dca9af0a4c5b
  - name: cp.icr.io/cp/cpd/fdb-apple-foundationdb-sidecar:0.17.8@sha256:65811c6449a021ef209964c3d630a3c2266a8c04cfc7470b30d0d24808b5716e
  - name: cp.icr.io/cp/cpd/fdb-apple-foundationdb:0.17.8@sha256:988b7f3abfe7267614266bb3cefb61d366fbcb1608bdac45bcfdf9723c4684cc
  - name: cp.icr.io/cp/cpd/fdb-ibm-backup-agent:0.17.8@sha256:9f6d7468e8d687ecf66feaeb84500921e6b264e98441fa494ec4af629688d459
  - name: cp.icr.io/cp/cpd/fdb-ibm-restore-agent:0.17.8@sha256:228d230561b210b015b6a40e595711e38c7f7d3eca4c642a295bd133b2c5cf99
  - name: cp.icr.io/cp/cpd/haproxy:2.2.24-217@sha256:3872ca6ac99f0e99741f43e4f3cd79c4908df05950e0b66a953e96e1fa8dcc45
  - name: cp.icr.io/cp/cpd/job-trigger:4.8.1.325@sha256:65af5cb93df3fa0eccf185337f098f3564be9363db96404fc72520a39577c2ee
  - name: cp.icr.io/cp/cpd/jobs-api:4.8.1.324@sha256:28a34e8813fe80afae3aa89cb624b79a55e40a7976f09c8ff9dc035efb994ccf
  - name: cp.icr.io/cp/cpd/jobs-ui:4.8.1.269@sha256:533cb3d86e0e932f99e527dbd17e05a2d17b159264e4a3320ef2d1c6063f5e22
  - name: cp.icr.io/cp/cpd/mdm-audit-rsyslog:2.0.73@sha256:5f2ac639fd59700d052a107d3dbe18db120952a3d3e14643b6e8d5a8c50f920f
  - name: cp.icr.io/cp/cpd/mdm-boarding:0.33.21@sha256:fbf362b5f05471d8bf1ebd005ee89634000c84c9ccf4b0e2dab42e24c962d5ad
  - name: cp.icr.io/cp/cpd/mdm-config-ui:1.34.87@sha256:6402db9d034e6197ad6061b1d12614b1adb197f8bbfcf3366f27c7f174c35990
  - name: cp.icr.io/cp/cpd/mdm-configuration:1.33.50@sha256:c494432558cdab71aa8f93b13cc3adb9ffc64fe08b4f8778752130b71034d57e
  - name: cp.icr.io/cp/cpd/mdm-data-quality-maintenance-job:0.25.2@sha256:8cabc22a6962b766e186b3b82d266331442f74c725666bfc4440b2deda6de2bc
  - name: cp.icr.io/cp/cpd/mdm-data-sample-data:0.5.56@sha256:0bee193a038b6f8252dff37cf3f63008e61a71e2fa7ecf1c4e32721e452f43ac
  - name: cp.icr.io/cp/cpd/mdm-data-spark-driver:1.31.73@sha256:b98ba2c94f23b0a70387c1a4ba797d44c572384c4f069f6faac6d68a071a353b
  - name: cp.icr.io/cp/cpd/mdm-data:1.33.209@sha256:6fd9fefa21a662ef65938af43fb642234bdf216eff676120461afbf9076dbb24
  - name: cp.icr.io/cp/cpd/mdm-em-ui:1.33.121@sha256:3c6f3f6b129b4fdefc2916f62679e529522985ef2a0aa5a2d7dce80b25addaf6
  - name: cp.icr.io/cp/cpd/mdm-job:1.40.4@sha256:4fa878a078672f199d135603b6e5837b8e0d8678fd7ed2ab9e2370d4b781e654
  - name: cp.icr.io/cp/cpd/mdm-matching:1.33.64@sha256:ae802515d8fce78eb1b46c5e4e9d958db8b6520b50b67384b21763fac1e4e355
  - name: cp.icr.io/cp/cpd/mdm-migration:0.2.99@sha256:6bf02aef9be5982760fff4114467b067a143a9794e50e8c285eb1fed917ba91a
  - name: cp.icr.io/cp/cpd/mdm-model:1.33.78@sha256:1678e7f1f24ecb28b3af0257a58132d751a697aa95be9281b660cc6d3601331b
  - name: cp.icr.io/cp/cpd/mdm-post-restore-job:1.27.11@sha256:4513645aca61eb609090ad46374657e0ba795fa998e3d47f65fbae67742da77a
  - name: cp.icr.io/cp/cpd/mdm-post-translations-job:4.4.6@sha256:6d2a08c3b2db29452a8c5e47d4d2bb7a144074fb6ee6c921e9512f0506df28b3
  - name: cp.icr.io/cp/cpd/mdm-shutdown-job:0.20.10@sha256:1196494a72361925fb0e15f348f8814caab4c14894fc97df7961a955de567d6f
  - name: cp.icr.io/cp/cpd/mdm-spark-job:1.33.21@sha256:442de9182588f8ab7da135932311b6bde8c257e3877f805ba4cf765c4a145e7c
  - name: cp.icr.io/cp/cpd/mdm-spark-sample-job:1.33.21@sha256:595f6ea2fa90aba3f7fc925930193cf8c563b6c56d6f2be01f04c4a1335f3e56
  - name: cp.icr.io/cp/cpd/mdm-tuning-job:1.26.15@sha256:a75bf305b166f29204e59299a2f7afe41f9eca36fce8cfbf673b6f628ff6cdac
  - name: cp.icr.io/cp/cpd/mdmx-neo4j-migration-image:0.6.14@sha256:2dcf46d38d1dba9077675adcc06a69e85d3629c10b06ffefd99cc0d90e21b2cf
  - name: cp.icr.io/cp/cpd/ngp-projects-api:4.8.1.215@sha256:4652f5f89db63304107643b1d0c48cc85928a5a56117aae3364edee003e58c4d
  - name: cp.icr.io/cp/cpd/portal-catalog:1.0.154@sha256:2936deaeb4eede9554ca87b4ddf35d5d5f050f2527edb9ab430f259eadf2e672
  - name: cp.icr.io/cp/cpd/portal-common-api:4.8.1.258@sha256:f8128b13aaa62c401a0fe87c63aae29c1979677e9202e8cc0aa231fabfa9b02d
  - name: cp.icr.io/cp/cpd/portal-job-manager:4.8.1.338@sha256:243710586386d280b8b379fc6bf569489a7817bfd21d0dd6d6f37121b601cab6
  - name: cp.icr.io/cp/cpd/portal-main:4.8.1.421@sha256:6ed76544f7351fc2ab74cc07b70add186bd5e43123591b29d66f3536a17a5d76
  - name: cp.icr.io/cp/cpd/portal-notifications:4.8.1.333@sha256:58856cc3393423c87f6e321370c4a94d5779d53f87437265ca7a9fce95049d0e
  - name: cp.icr.io/cp/cpd/portal-projects:4.8.1.1431@sha256:f227ecf74e431a349fe4d267b02359ac98f85d91b8abd00018dc5ba1b200d72d
  - name: cp.icr.io/cp/cpd/rabbitmq:3.12.2-218@sha256:4ae5a94efdbc481e22df7acc0e0cb319638bb68ac0158cf6ae2c5c26b60f0846
  - name: cp.icr.io/cp/cpd/redis:7.2.0-336@sha256:2b277887075bfc7a42acf78476492d7fa39ff65f4d188aabcae8fd810d9abe66
  - name: cp.icr.io/cp/cpd/runtime-assemblies-operator:4.8.1-441@sha256:b5d12b23f2773c3bdf51929fbb519377b79b091e8928885775e1b14a14edf2de
  - name: cp.icr.io/cp/cpd/runtime-manager-api:4.8.1-1391@sha256:2f8c433333b879960318e215e5e7400e0a6d5f72bd8ac8c94552a3d5a370d4ea
  - name: cp.icr.io/cp/cpd/spaces-ui-job:4.8.1.1209@sha256:a7e3d8e3a6ffff9e306eb709f4db8b0f7370b1401a16bdd2679770cf29267b63
  - name: cp.icr.io/cp/cpd/spaces:v.4.8.0.15@sha256:fedd9a078e12eca2424342f58bd0857394edc78f7b8065bc634c1fdad54bb3e4
  - name: cp.icr.io/cp/cpd/task-credentials:0.0.152@sha256:65d90122abb626b9630f876c2a9d47b273334f7da6c6c43efbce6b50e1e7b6ed
  - name: cp.icr.io/cp/cpd/wdp-connect-connection:8.0.218@sha256:d107e6712f62048c0a0e0dc0545349716d6bcd91ebb0bb96e37aaa6207893a08
  - name: cp.icr.io/cp/cpd/wdp-connect-connector:8.0.218@sha256:959f00dd190a6da2568758cb32589c93bc7fffe62186c193a170d0aacc9a2b97
  - name: cp.icr.io/cp/cpd/wdp-connect-flight-svc:8.0.218@sha256:f36f0aeb8321122b156ea6d7e619de52a5e51612173b76b7811c086355a9bd6b
  - name: cp.icr.io/cp/cpd/wdp-dataview:4.8.1.196@sha256:e612299978f94ddd7f8c70360044fb91ff2da2442d8e051c66cd34d2c36ae7d9
  - name: cp.icr.io/cp/cpd/wkc-init-container-ccs:2.0.215@sha256:818ffa657c31d32b48a524752ed26ab6631ba0dd12bf95c31b907e7703858236
  - name: cp.icr.io/cp/cpd/wkc-search_master:4.8.39@sha256:d1749530d8f8011cc4691fa99681068d0883cd88d0312b894020ede39c64e79e
  - name: cp.icr.io/cp/cpd/wml-asset-registration:2.2.165@sha256:7f9564fdfc3c5f64366f21af53c55df48aaf41e7e27040309c6beb4c01bda471
  - name: cp.icr.io/cp/cpd/wml-main:4.8.1.1209@sha256:48002529fe4aecae63867b0856cf098f020b359d597dc041945629161598240c
  - name: cp.icr.io/cp/ibm-redis-cp-6.2.13:1.1.1@sha256:2bf8995531c3baa1700a533824e080a05a78db81ef88f2ec4ea34bf29cae1d39
  - name: cp.icr.io/cp/ibm-redis-cp-6.2.13:1.1.2@sha256:bdd97f085b7b6a05ee36a822d7cf8dda0b7d205a1ec68129609bc89a702578f6
  - name: cp.icr.io/cp/ibm-redis-cp-6.2.13:1.1.3@sha256:f3c31937995c0e24243019359e096845b954b43dddf8073d9edcc5347aa08856
  - name: cp.icr.io/cp/ibm-redis-cp-6.2.13:1.1.4@sha256:cbf1ddf8dcdeb7a35271d24ca5d873b45c00caf062b1d1efd8864d9b116e5484
  - name: cp.icr.io/cp/ibm-redis-cp-6.2.7:1.1.0@sha256:5286e66a33bce1a8d75c9f6aa714f2dfa8a25959ef463b96b88ba0464fba3d90
  - name: cp.icr.io/cp/ibm-redis-cp-haproxy:1.1.0@sha256:8bc992c093229509469fce5339e9d1c82ba9ce862485a196340ef8acdfd3b77a
  - name: cp.icr.io/cp/ibm-redis-cp-haproxy:1.1.1@sha256:961d8dfaecb90220d388587874c3316993c52036d820e515dea2dce7d5e60d92
  - name: cp.icr.io/cp/ibm-redis-cp-haproxy:1.1.2@sha256:1099a0ef09d7078c40f24c9dcc2e9f82adf4ba1b3ff95425400f88fbb6eee3b3
  - name: cp.icr.io/cp/ibm-redis-cp-haproxy:1.1.3@sha256:9348d0c1c5a39e6adfd99187583fe47b8c82b565a7f5ab296367f28632a49d0e
  - name: cp.icr.io/cp/ibm-redis-cp-haproxy:1.1.4@sha256:a2ae1d9bae9d122667c10e90ad36a8c5b5a69d0faa8ca4f8851d0f42e9932a71
  - name: cp.icr.io/cp/opencontent-rabbitmq-3:v3.11-1.2.69@sha256:ad55efa17f9ac2aca9d2e8244ff302753231dee4edb06459cf18cce0415e20e1
  - name: cp.icr.io/cp/opencontent-rabbitmq-3:v3.13-1.2.69@sha256:80192d4b6291de3312906108e59c58234281f6d081863c3a79d56529a55eeadc
  - name: cp.icr.io/cp/opencontent-rabbitmq-config-copy:1.1.99@sha256:a68289a79e25a944b263692901469f3c3e1fd23a0db253d39ebe9d43c1d7dad4
  - name: icr.io/cpopen/fdb-apple-operator-bundle:3.8.14@sha256:6eeb85cdbe37d1d18b8fa9b486f86eac36b03067bfff8fc11989f80c45032a86
  - name: icr.io/cpopen/fdb-apple-operator:3.8.14@sha256:dc2f2dedb6522ef766c60b97839bb423899a9c4102e217ea29bcee4e75b81acd
  - name: icr.io/cpopen/fdb-ibm-operator-bundle:3.8.14@sha256:7c393cc4464f211dda9dc431c2d26bb124746021cd295f51b39211c3ae6cfe92
  - name: icr.io/cpopen/fdb-ibm-operator:3.8.14@sha256:f920516091fa4eeda6afdaa473e135331e0f5e791bd49d4ff465a7d71f47978f
  - name: icr.io/cpopen/fdb-operator-catalog:3.8.14@sha256:f78a74139bed1d810a2badda5940abeb81d0936b45f734b04d0a10d056d4f0dd
  - name: icr.io/cpopen/ibm-cpd-ccs-operator-bundle:8.1.0-20231208.155538@sha256:f63140a0a38aecec989370a581ea41bfa211250abeae9ed6adb1e1dbf52971cf
  - name: icr.io/cpopen/ibm-cpd-ccs-operator-catalog:8.1-20231208.155538@sha256:4bd21976ae4986a0d644fcbb5d804f2a01cf202076c83d768c74d437352cc73b
  - name: icr.io/cpopen/ibm-cpd-ccs-operator:8.1.0-20231208.155538@sha256:6ac97dbd63df931dd68e45887af2d839d0374415444b59cc1818564063909c59
  - name: icr.io/cpopen/ibm-redis-cp-operator-bundle:1.1.4@sha256:bcd74d47636b726e8a5f90d167395e4bdf762ccd6da4dfedc78dadccaca7f3e5
  - name: icr.io/cpopen/ibm-redis-cp-operator-catalog:1.1.4@sha256:1e81cab5cf1f3e44527e8a893f6648c106b13c6df78b7abbe70993925e63033d
  - name: icr.io/cpopen/ibm-redis-cp-operator:1.1.4@sha256:1acf1d333bef4ae946a99afbd615e0781b2b31322f62a311412255d82c485f89
  - name: icr.io/cpopen/mdm-operator-bundle:4.11.50@sha256:d8fe0a026c07ee242bc8606bfe6589b0f4b0292b4923c600c6093870be4c739b
  - name: icr.io/cpopen/mdm-operator-catalog:4.11.50@sha256:cec0b304f696f74aa5365c116a0bb92e9c9d8147045eeca02f2ce0d92ebb9dc5
  - name: icr.io/cpopen/mdm-operator:4.11.50@sha256:26fdaf0f0c679857e8d7a84bc3ab63d1cf3df44e7e9b2e549051600cfa293030
  - name: icr.io/cpopen/opencontent-elasticsearch-operator-catalog:1.1.2667@sha256:a34169228887ff93161584753c990bb82a5520ad7945dfa1ff4078e70aede592
  - name: icr.io/cpopen/opencontent-rabbitmq-operator-bundle:1.2.72@sha256:6523cd3dd17cb64ff0da65acd135ea59dfe34f137fff0ab5954786921b02e1ab
  - name: icr.io/cpopen/opencontent-rabbitmq-operator-catalog:1.2.72@sha256:05fc303da5adf8f8dc67a432849d46341be900ef8a782432cfefd8a9c3df1f8d
  - name: icr.io/cpopen/opencontent-rabbitmq-operator:1.2.72@sha256:f47427a6f316c311ef09e69f00d025ef4d0782823506d8a08c6bbe6085a25887
