kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-scc/ibmscc:6.4.2.0.iFix01_2026-02-24@sha256:56df6b461d926dd58e7d7c15413e55dc920ef73baa35bfb651ce5a383feb5144
  - name: cp.icr.io/cp/ibm-scc/ibmscc_resources:dbdrivers@sha256:995b4efff9a9002baccab2034ce18ac8e7a39ecef4b3000b0541dba92685737f
