kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-scc/ibmscc:6.3.1.0.iFix06_2026-01-30@sha256:da1565c2fbe231268919d1fdcfb65a87f115e49d0fb60afd78efa58bca34f14b
  - name: cp.icr.io/cp/ibm-scc/ibmscc_resources:dbdrivers@sha256:995b4efff9a9002baccab2034ce18ac8e7a39ecef4b3000b0541dba92685737f
