kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/gpfs/csi/csi-attacher:v4.8.1@sha256:69888dba58159c8bc0d7c092b9fb97900c9ca8710d088b0b7ea7bd9052df86f6
  - name: cp.icr.io/cp/gpfs/csi/csi-node-driver-registrar:v2.13.0@sha256:d7138bcc3aa5f267403d45ad4292c95397e421ea17a0035888850f424c7de25d
  - name: cp.icr.io/cp/gpfs/csi/csi-provisioner:v5.2.0@sha256:d5e46da8aff7d73d6f00c761dae94472bcda6e78f4f17b3802dc89d44de0111b
  - name: cp.icr.io/cp/gpfs/csi/csi-resizer:v1.13.2@sha256:8ddd178ba5d08973f1607f9b84619b58320948de494b31c9d7cd5375b316d6d4
  - name: cp.icr.io/cp/gpfs/csi/csi-snapshotter:v8.2.1@sha256:5f4bb469fec51147ce157329dab598c758da1b018bad6dad26f0ff469326d769
  - name: cp.icr.io/cp/gpfs/csi/ibm-spectrum-scale-csi-driver:v2.14.5@sha256:1b7d11c7f07fe86d52dd990487e0dfa297366b69e2ff2fe6f2f62eae3779007b
  - name: cp.icr.io/cp/gpfs/csi/livenessprobe:v2.15.0@sha256:2c5f9dc4ea5ac5509d93c664ae7982d4ecdec40ca7b0638c24e5b16243b8360f
  - name: cp.icr.io/cp/gpfs/data-access/ibm-spectrum-scale-daemon:v5.2.3.6@sha256:c24a97bf8665c6b4f5f7586969103d570b6e9e8866a631a47d2645af32c194f4
  - name: cp.icr.io/cp/gpfs/ibm-spectrum-scale-core-init:v5.2.3.6@sha256:da99a1ca87759bc97955e1bb6362e4eccc08ffaa1bcaf3ff2822184ba5a8ca59
  - name: cp.icr.io/cp/gpfs/ibm-spectrum-scale-coredns:v5.2.3.6@sha256:bcad2bad5e0ec4629c1f3d8c6372674b94c1e82f7d8bdf950306668367eef765
  - name: cp.icr.io/cp/gpfs/ibm-spectrum-scale-grafana-bridge:v5.2.3.6@sha256:aa2de56ca0ed4fb24bd697e58275642c0fe9847748986ebc66c0b7b5ca5675fe
  - name: cp.icr.io/cp/gpfs/ibm-spectrum-scale-gui:v5.2.3.6@sha256:37dfbc4c85481e3392e2ee418947a11894833e230bb626b9e1719eaec5728062
  - name: cp.icr.io/cp/gpfs/ibm-spectrum-scale-logs:v5.2.3.6@sha256:f567a866db1c78d081bd952525339c04a5a8435da99cb545d9ffc2a0dbaae04b
  - name: cp.icr.io/cp/gpfs/ibm-spectrum-scale-monitor:v5.2.3.6@sha256:443d2d62ac369258598657f52e2f00405897701e868f67d5eea9b88c41cab604
  - name: cp.icr.io/cp/gpfs/ibm-spectrum-scale-pmcollector:v5.2.3.6@sha256:ff69995e2557a946b603611fee5ea2773cebc505b64ed96be00f258d299fd969
  - name: cp.icr.io/cp/gpfs/postgres:17.6-alpine3.22@sha256:ef257d85f76e48da1c64832459b59fcaba1a4dac97bf5d7450c77753542eee94
  - name: icr.io/cpopen/ibm-spectrum-scale-csi-operator:v2.14.5@sha256:e7b3fe21f3a87b75c115f366af45b79a164808e812e9e05ab8ed5fe41f460fae
  - name: icr.io/cpopen/ibm-spectrum-scale-must-gather:v5.2.3.6@sha256:4114c2514b2ea26acbb34a8c7e9701a129236e6b192c67dc78779f690d8dd73f
  - name: icr.io/cpopen/ibm-spectrum-scale-operator:v5.2.3.6@sha256:c0958ef1b8c48bdaec6b9b798334271e8c792f13ee272444f3ca9c3955d04f21
