kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-8k-ansible-part1:1.0.38@sha256:d2a3f8540014b94936eb24ffb315086b9049dda093b8ece033a98ca454ed2370
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-8k-ansible-part2:1.0.38@sha256:639926bbe55d9ca3955229200b6fa5f4678e27a23fc4622388dd4c4b327462c3
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-8k-ansible-part3:1.0.38@sha256:6a4555e3e93bd326172eaa8d6b39d0e7cbe0f15f776c617d475d7f0901b05407
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-8k-ansible-part4:1.0.38@sha256:0fff20195cc41ff00e89ff4eec492480f2c799bcb3976dc645b3152f942ae666
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-8k-ansible-part5:1.0.38@sha256:17c8bc45b299d061cdb97af9b528afb7f7f602317f7496aefe203bee38b60b63
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-8k-ansible-part6:1.0.38@sha256:0352fcd684b3851c80bd6c7b051e0ede728166bf51c7b0d12a151870b0a1c063
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-8k-ansible-part7:1.0.38@sha256:4b151e6e2f0c83a1e697ff0949c88db1491558a2a916ad707542b48697bedbdd
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-8k-ansible-part8:1.0.38@sha256:7c9c8f7faadf4b27d6ce538c913dba43df7e61d70fc348262c4009515be0149a
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-8k-ansible-part9:1.0.38@sha256:2201f006929f2082653128c2ea339e18e52ea91259435f106041ce9965f83e25
  - name: cp.icr.io/cp/cpd/wca-codegen:5.3.1-21@sha256:47f545f9e76cd2d042d4cfc40afed0ceb5000dd49b2bdd748cdba713366246e2
  - name: cp.icr.io/cp/cpd/wca-codematch-index:2.20.28@sha256:7f8db3805f0fe239951a2917122d0bb55c721490701b7f408fc2ad50290e1005
  - name: cp.icr.io/cp/cpd/wca-codematch:5.3.1-21@sha256:c1b00174da0cefcf2f7c660e5b7d4eb257d1948255053ca508e91b9d0585620a
  - name: icr.io/cpopen/ibm-wca-ansible-operator:5.3.1-21@sha256:24195d036aaeeac1fa698c64139fd4b8c1d4ab6baf30840f689c66ae4a6c55bd
