kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: icr.io/cpopen/ibm-truststore-mgr-operator-bundle:1.7.3-amd64@sha256:aa3b533a92ba8a81dd83dfb0836ac3573534f8023e6a134195a330092f63f9ee
  - name: icr.io/cpopen/ibm-truststore-mgr-operator-bundle:1.7.3-ppc64le@sha256:b61d0f9eb6e3012c62fc88e1a5fe44421ae6c8c0efb765fd82575f1fe7875b8d
  - name: icr.io/cpopen/ibm-truststore-mgr-operator-bundle:1.7.3-s390x@sha256:7d7cacef5525f27ce1b729e5b42c96c6df335da12cccac49b5140eebb1650b52
  - name: icr.io/cpopen/ibm-truststore-mgr/worker:1.7.3-amd64@sha256:2373c6c81a18efdc538156e59e07541db71aa7e79c48d769165422cb22502630
  - name: icr.io/cpopen/ibm-truststore-mgr/worker:1.7.3-ppc64le@sha256:4882134e68bd95a61e6579d59a51ddb2f876da12de3fd472cb9447479b0c00d2
  - name: icr.io/cpopen/ibm-truststore-mgr/worker:1.7.3-s390x@sha256:fc606f63aa111b7257e0fb09ad31e86acd66b88acbbc408bc47b5865ae7090d2
  - name: icr.io/cpopen/ibm-truststore-mgr:1.7.3-amd64@sha256:27007e280094716b774791f90300b6b28b7cad349a87ef4e6a7748a302c6b812
  - name: icr.io/cpopen/ibm-truststore-mgr:1.7.3-ppc64le@sha256:f1e79027f1dadacffebbf8fd6fc327dff8f91df40cba39d8bc46a48de8510dcd
  - name: icr.io/cpopen/ibm-truststore-mgr:1.7.3-s390x@sha256:b5665214fda9b2456262f45b912119e7ef2441fde034c604bdee89b8a6f2d599
