kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  operators:
  - catalog: icr.io/cpopen/ibm-zen-operator-catalog:5.1.19@sha256:c4120915f2275f0c23aef6d65ad6d6f89deec096cf40669ef2cb746a4e4cb69e
    packages:
    - name: ibm-zen-operator
      channels:
      - name: v4.4
    full: true
  additionalImages:
  - name: cp.icr.io/cp/cpd/edb-postgres-license-provider:2644@sha256:2f921d1c39f72f183ca285151acf5d0dc6bd9e71a24acd1db17e6b05baf4935c
  - name: icr.io/cpopen/edb/postgresql:13.22-5.22.0@sha256:841db53fc45ebcb3c0dbbb0f68c2fdfe80cda1c7a5871ac1956fc80e18198e27
  - name: icr.io/cpopen/edb/postgresql:14.19-5.22.0@sha256:bce78b457ffeb4080aaac01dee712aa0e852ab9a3b4b42414634310b85019d8e
  - name: icr.io/cpopen/edb/postgresql:15.14-5.22.0@sha256:44167b92101095992f3c1e1d7727db7e9e624fc5ed81c13a2d5efb1f1901c70d
  - name: icr.io/cpopen/edb/postgresql:16.10-5.22.0@sha256:0ec7d9cc2211ce38d9881bda9b0a1370f0420d54ff18f90495530c7cf02c0301
  - name: icr.io/cpopen/edb/postgresql:17.6-5.22.0@sha256:6985297657d7b7b916427f7a0da9684cf7b269cb9015dfdacbaa7f68659e7ae4
  - name: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-bundle:2660@sha256:b166e9d0129eb02080d8ccf44b5ac680a99eba9cb4040e0d686132ee78109467
  - name: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-catalog:2660@sha256:a333a9dc5f8c81aed7201a574f784a85b68ea55d8a45af235956aac1406009e4
  - name: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator:1.25.3@sha256:64fdfbe46284cdfda81d710f285ce75fc5f38a14634b8c27498e7de663342c8b
  - name: icr.io/cpopen/ibm-zen-operator-catalog:5.1.19@sha256:c4120915f2275f0c23aef6d65ad6d6f89deec096cf40669ef2cb746a4e4cb69e
