kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-javaenterprise-v2-part1:1.0.33@sha256:f60a93c84b52f7587b8bd42220f8a12c5e6da83becef3d207b57567eb15dfc13
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-javaenterprise-v2-part2:1.0.33@sha256:7ea1e46b4502de4bcb32bee6d7f32d5d431fc63837497f12d04073d467755ab6
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-javaenterprise-v2-part3:1.0.33@sha256:a75cb1c1ccb9d87dcf42732ff3d123666ba97c161d326c8abdc7cb69fae89090
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-javaenterprise-v2-part4:1.0.33@sha256:ec8dc32fe8e8c8e0434b6033619141502324947aca8aa5f63f1fa6cbae276698
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-javaenterprise-v2-part5:1.0.33@sha256:3e37b22ee99c642d98434b4009f31581ad01f6cd2e81775eb43657aea22ae60f
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-javaenterprise-v2-part6:1.0.33@sha256:d6dafafabdcbf9103a1ff13461be8be86f613525e2d56155ddab080aae2a8050
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-javaenterprise-v2-part7:1.0.33@sha256:e2609e29ca91b276f5fdb0ef6d7731d3a7fdc4b999d1a7e100a0647741936b86
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-javaenterprise-v2-part8:1.0.33@sha256:2d4a2f39eac00f3fc35da34dc315ba90f2d88e2abcd8c4b00b1ca35dabe6d331
  - name: cp.icr.io/cp/cpd/ibm-granite-20b-code-javaenterprise-v2-part9:1.0.33@sha256:8618379f04ee56dc443861b6316c843a2279f76c111d2e0c3d42b83ff2e5a6e7
  - name: cp.icr.io/cp/cpd/wca-config-main:5.3.1-22@sha256:71c364991024565f9a6dbadaf050fb352da792adb44f34e4487b121a52fe4252
  - name: cp.icr.io/cp/cpd/wca-core-microservice:5.3.1-22@sha256:d556853fadd8666231d22772e4869f5217d8a01d7c7db58f8b93168c154a7bf9
  - name: cp.icr.io/cp/cpd/wca-similarity-job:5.3.1-22@sha256:f99f41d832e31ef47a5fe4645191b0d9eef1034f1e7b8b36753a8ee87863f48a
  - name: icr.io/cpopen/ibm-wca-operator:5.3.1-22@sha256:b80f33bfbe5b42f00311e624ca3e27222bc1a6270461d83d387c299dbda813ea
