kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-mqadvanced-server-integration:9.4.5.0-r1@sha256:2b5150b4c2f35b68a2248663ed49ca771bb3d53ede5ee0c7d1576d3a3944d888
  - name: cp.icr.io/cp/ibm-mqadvanced-server:9.4.5.0-r1@sha256:62c2d36b8cd37436786a79981b496d0e8562bcd20fc2f05cc497080e2e0780dc
  - name: icr.io/cpopen/ibm-mq-operator-bundle:v1.3.8@sha256:b51116f645859c2125b73f0ed6c81b5decc6f885d6827a0c0a43fea426c39365
  - name: icr.io/cpopen/ibm-mq-operator-bundle:v1.8.2@sha256:185121d824e2df34ce7395dd0bfadb93e5506aa248885f5c21ee5de0e50ffc0c
  - name: icr.io/cpopen/ibm-mq-operator-bundle:v2.0.29@sha256:fc81103fe6f85a685f083ffb48314fdc632e83376ca92986901f09cf312526ab
  - name: icr.io/cpopen/ibm-mq-operator-bundle:v2.2.2@sha256:95f0f9eb7336ddb6da287ccb3d60a35cdc62938a4ccc916cc6fe1fe4fd14305e
  - name: icr.io/cpopen/ibm-mq-operator-bundle:v2.3.3@sha256:4f5ff887ec99514c74c47edc21c17252aa17cc0e7cb0ce94cdc11884fd1769dc
  - name: icr.io/cpopen/ibm-mq-operator-bundle:v2.4.8@sha256:a0c8474ab488fe54d1675c3d4580b640c344f7c24a4839a3de5a117deb2fc958
  - name: icr.io/cpopen/ibm-mq-operator-bundle:v3.0.1@sha256:d2f672bc99188c01ff41626fdd4d976ac5b6c3bd0b3e53950a8a42e0db840e58
  - name: icr.io/cpopen/ibm-mq-operator-bundle:v3.1.3@sha256:85e9a6560ee46860b06c2ad9ee55e99dd170d067b38f9789b1e05178918f27ae
  - name: icr.io/cpopen/ibm-mq-operator-bundle:v3.2.21@sha256:734ca1234e71591c2d1d55e078652aee3fca68ab0b4a03f8d0fd6110cda6219d
  - name: icr.io/cpopen/ibm-mq-operator-bundle:v3.3.0@sha256:df8616792892628148e7edeeb29b926f22a66372466b8c09feb25cae812193d7
  - name: icr.io/cpopen/ibm-mq-operator-bundle:v3.4.1@sha256:43e59d7c1b2524ed8bb02ee169ae1de6dc79c41202d2bac7209c9012c1261b3d
  - name: icr.io/cpopen/ibm-mq-operator-bundle:v3.5.3@sha256:09fa6626f65ef784f5c1dc843a59f5a0ad4cc435f69679f5524e3ea1dcc25057
  - name: icr.io/cpopen/ibm-mq-operator-bundle:v3.6.4@sha256:6f8d8a10acf9f824add90847a23636267470154e7a3c088bab5eb9c548ca8e65
  - name: icr.io/cpopen/ibm-mq-operator-bundle:v3.7.2@sha256:ab3dd3048e0168e1ea1c36b3fbd33f4f7089f1bc6fc83e7337a81c9e7da87602
  - name: icr.io/cpopen/ibm-mq-operator-bundle:v3.8.1@sha256:312c671bfd7988c9fe99276b58f15d9afb9e613c1c1ac345fa3d6556548296ef
  - name: icr.io/cpopen/ibm-mq-operator-bundle:v3.9.0@sha256:ca6d5929ae68bcbef0d3807aad25b23cd77e6817a579e540937eac06c74ebc9c
  - name: icr.io/cpopen/ibm-mq-operator-catalog:v3.9.0@sha256:7d6a2f91ea91f46a3e991422db9fd27e5b03f4d8defca77fd7ce3afd8b2e2695
  - name: icr.io/cpopen/ibm-mq-operator:v1.3.8@sha256:a50e9a5006f0e44078a5de26c0d6f56bdea3e1489f362aae2106dc40cadbbec8
  - name: icr.io/cpopen/ibm-mq-operator:v1.8.2@sha256:3cb8a3021a434a656eeff95e285d525158a8372c14ec04c1a234d9b639640e23
  - name: icr.io/cpopen/ibm-mq-operator:v2.0.29@sha256:806027108fd0051d93e93c11a3d273a76a435daeb24141d490ad82ed96a08360
  - name: icr.io/cpopen/ibm-mq-operator:v2.2.2@sha256:a6b37eedc436cf8673e82fd670722f61b375d281d26f38f8539f377a6d5d4abf
  - name: icr.io/cpopen/ibm-mq-operator:v2.3.3@sha256:f93a56a993ca6e1cd78b19b16031ee88594863c566521da732a885b64277d069
  - name: icr.io/cpopen/ibm-mq-operator:v2.4.8@sha256:1aa75c6dc6ce29f10e088073e1c1d7f4dcd511e601096493378478dbbfbe417b
  - name: icr.io/cpopen/ibm-mq-operator:v3.0.1@sha256:e471631d97a17ea6e0226a7a0f4406494784a600cdcd325c422bda80a7b8d916
  - name: icr.io/cpopen/ibm-mq-operator:v3.1.3@sha256:510a63020762d4185fc3ef0fe413e0da0587e34dcac7f3a0d94d9f462cf41851
  - name: icr.io/cpopen/ibm-mq-operator:v3.2.21@sha256:cabb93da5c41522e8b776fe18888101b67f4df1c66836730535a5d48216d17c4
  - name: icr.io/cpopen/ibm-mq-operator:v3.3.0@sha256:15b6f3d9d05a0cf901ded12ccee41be531abb3b89f5e0e7df48f6618d63ec4b8
  - name: icr.io/cpopen/ibm-mq-operator:v3.4.1@sha256:e4eceb4c8bdee9d16c9ef3c708af5e5e3622a20ba452cddacebf65b316565fa1
  - name: icr.io/cpopen/ibm-mq-operator:v3.5.3@sha256:454dd71fd8b3b3dbd9b6ff26edabf12327dac7f821b77d7cba181bf3cc373de3
  - name: icr.io/cpopen/ibm-mq-operator:v3.6.4@sha256:44d5373ce9258190f4c48383450fd76f8841c29915dd15dc461a7b86e6651e86
  - name: icr.io/cpopen/ibm-mq-operator:v3.7.2@sha256:4d83ff2ac825793974fdd74c9302ab346f54f57eb4d5f5c731132228248c7cc3
  - name: icr.io/cpopen/ibm-mq-operator:v3.8.1@sha256:148e594bfb39126aab932c1f0dfccfdb63fa989e99c597409ce0edabe77157dd
  - name: icr.io/cpopen/ibm-mq-operator:v3.9.0@sha256:68b733aecb0a3a447d4853a2394f06655f4cacc59401e3e6ddf340de2017523e
  - name: icr.io/ibm-messaging/mq:9.4.5.0-r1@sha256:50c635e55660d97edd6327620038fb562fcf05219018e3a4ee7e96737974b572
