kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-ssp-ps/ssp-ps-docker-image:6.1.0.3-iFix00-2026-01-19@sha256:405eea9d1b170697fe618472b0406351086b7d9ca754ae10c0402c10f5026268
