kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/df/ceph:v4.16.21-3@sha256:e862b5b76da02e77c1d10eea017ea1927f56358a461d26bcf417fa8e571395e7
  - name: cp.icr.io/cp/df/cephcsi-rhel9:v4.16.21-3@sha256:e694458b150aa9b3f9646c3866cace0bec54ec7bd15d19bcee831adc331b63cf
  - name: cp.icr.io/cp/df/mcg-core-rhel9:v4.16.21-3@sha256:086b583b30945f93dec27d56fa9e0da094af1182a9feccb590078525d72615d0
  - name: cp.icr.io/cp/df/ocs-client-console-rhel9:v4.16.21-3@sha256:e7e8627048b674844c08f725764516be0cf41f94ad770cefa31f950278536f8b
  - name: cp.icr.io/cp/df/ocs-metrics-exporter-rhel9:v4.16.21-3@sha256:73f641c17a4183cc541c8fc864d83c96029efb2ba4dc648e2cfb6f90c12db08e
  - name: cp.icr.io/cp/df/odf-console-rhel9:v4.16.21-3@sha256:6c54912787a493951cd23158e0d337a8ba42b15723db3c562a29c3fe58509b2f
  - name: cp.icr.io/cp/df/odf-cosi-sidecar-rhel9:v4.16.21-3@sha256:45bfdb92ad9eef1d42c5ff719f2bf4ef3d0498d913f0e95a91404f117ed76f7d
  - name: cp.icr.io/cp/df/odf-csi-addons-sidecar-rhel9:v4.16.21-3@sha256:8c71515b096e47cbd41b38c33dceac4fcc357679bbd107ee710eefc51c077fc4
  - name: cp.icr.io/cp/df/odf-multicluster-console-rhel9:v4.16.21-3@sha256:3960a0954f15cf2d0a2dd5f9afce8ee7093995301f3a751ac86296ad76a072f8
  - name: icr.io/cpopen/isf-data-foundation-catalog:v4.16.21-3@sha256:7a07b6c8d8d409c2ba241a31c221c522e6b70f65461aa9f6ce5e6eca66583406
  - name: icr.io/cpopen/mcg-operator-bundle:v4.16.21-3@sha256:463a95f7baa95af29a8bea53f58b79f1d0eb3729506bbb4287a94f66cbe88fc6
  - name: icr.io/cpopen/mcg-operator:v4.16.21-3@sha256:9d25c025b9860a3f712d68113cf28e6dcaa71fb18ad57ddbb5ee3d712f5be15d
  - name: icr.io/cpopen/ocs-client-operator-bundle:v4.16.21-3@sha256:d606bcf0b7c7949cd2d95fc09d26bd8a5b0ae46f80c093acd94c3d65f3cc3778
  - name: icr.io/cpopen/ocs-client-operator:v4.16.21-3@sha256:64f4b1fb2a1b2240b29ba5b9cfd55be03e68b466e919ddb5816bf3de504a6155
  - name: icr.io/cpopen/ocs-operator-bundle:v4.16.21-3@sha256:7b7220f6aaa4bbb031aa8dbde6fa6369b1010c6183e4b669adfa129c4ff8bf0d
  - name: icr.io/cpopen/ocs-operator:v4.16.21-3@sha256:088532592c16558c052e12cc49a7beccbe14d2a27457fb826872c0f1e6b4611b
  - name: icr.io/cpopen/odf-csi-addons-operator-bundle:v4.16.21-3@sha256:56c12f324e26e4c1b4daeecd17c3df9b0d613663ddb83d002930f6bfe24064b4
  - name: icr.io/cpopen/odf-csi-addons-operator:v4.16.21-3@sha256:59f9c84bf5f647bbb2854e7d6808d5ef5855e65792164a248c173f96f5abbb94
  - name: icr.io/cpopen/odf-multicluster-operator-bundle:v4.16.21-3@sha256:aa02fa7c70a47af33ae7d72e96346c62c7dc6741ad36b85caf5c9e9b45a1c378
  - name: icr.io/cpopen/odf-multicluster-operator:v4.16.21-3@sha256:dbbaa13c0e6460f02f60ebeac4ce8c601af97d79dda642f1890f18c1e5f2e46d
  - name: icr.io/cpopen/odf-must-gather:v4.16.21-3@sha256:2f20f7b490af6b0478dd081e58623970be18b4074bdb3c4f7c6e9202d4d9fe9e
  - name: icr.io/cpopen/odf-operator-bundle:v4.16.21-3@sha256:66197fe6ca1210146e5b4231f44ea5997a0baa2398471c18e46c8c9d4e820b0c
  - name: icr.io/cpopen/odf-operator:v4.16.21-3@sha256:cfdbad81ef8d22c34668276323e2bde27dc0cf655baacce804f3c81f71430f3e
  - name: icr.io/cpopen/odf-prometheus-operator-bundle:v4.16.21-3@sha256:98945ae870699a4f032443c8d588b5c333ec39e7d3a116bf595c75ca1e3b87a8
  - name: icr.io/cpopen/odr-cluster-operator-bundle:v4.16.21-3@sha256:a43c32d0ce57a716de5b5c8ad96a049a78507d94abf8741ac6510d4a3e58ebf5
  - name: icr.io/cpopen/odr-hub-operator-bundle:v4.16.21-3@sha256:85698f0bf091a330b51e375d2abc9b7bbf4c5c17a0ed8555ab06da4ac711506f
  - name: icr.io/cpopen/odr-operator:v4.16.21-3@sha256:82c9806498aca1f40a46403ee6104c3fd8121a50f729712045178d8688b732fd
  - name: icr.io/cpopen/odr-recipe-operator-bundle:v4.16.21-3@sha256:239661d26a92dc0dcdf2f33da425c35ff4b32d818c827aec194bf862fd5404df
  - name: icr.io/cpopen/rook-ceph-operator-bundle:v4.16.21-3@sha256:99deb61a0d4f857c6db228fd87f225ba4aad6372f9afffbcc660c4b8aa9d81e8
  - name: icr.io/cpopen/rook-ceph-operator:v4.16.21-3@sha256:f0ff09c0a99f41fb1891aebde3469ef09e3e0b3e604ce89dc66896f62695bb98
