kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-eventstreams-admin-ui:12.1.0@sha256:bdee8ed0601728d2fa12c94c0427c4b1068c035bbf9f444d517cef8fc41b904b
  - name: cp.icr.io/cp/ibm-eventstreams-admin-ui:12.2.2@sha256:bbe8e0bd42e1e8724a98dcc77c8f2f397f9d266f25750345cba53146d9dcdf1b
  - name: cp.icr.io/cp/ibm-eventstreams-admin:12.1.0@sha256:dfcb44f36fef087ecb27f2e639897e94312c90dd1f60c2f81894b448ccfb55a2
  - name: cp.icr.io/cp/ibm-eventstreams-admin:12.2.2@sha256:1673f44f9c1bd7e989a830736d820428d08c3eae3e3c0e954bf716dbafce48d9
  - name: cp.icr.io/cp/ibm-eventstreams-apicurio-registry-v3:12.1.0@sha256:6a1170a9928063ea03610a89a1d8638b625fcf30bd905864afafb390a0a6c399
  - name: cp.icr.io/cp/ibm-eventstreams-apicurio-registry:12.1.0@sha256:bac7f0f8ac0b738048561969093aae26e6b6da5ec3e0caab4021a99cc5cc1718
  - name: cp.icr.io/cp/ibm-eventstreams-apicurio-registry:12.2.2@sha256:dee032325230c7bbb33d3363d5f821feee9becb3292c0eef707ee5d23e16b95d
  - name: cp.icr.io/cp/ibm-eventstreams-kafka-bridge:12.1.0@sha256:4807cf7bed8a30bb673dc53bdc6a5dd7b9d484e1d35b32272daf7eed0cecc8d4
  - name: cp.icr.io/cp/ibm-eventstreams-kafka-bridge:12.2.2@sha256:03d53dd17c9bc37b200fe801c8edc3ddc624a424b9ad447083c78f843f9ae97b
  - name: cp.icr.io/cp/ibm-eventstreams-kafka-proxy:12.1.0@sha256:f1a75eb8dd3fea177bec96422d02af8b3fd87821b644bdfb52eb09c081fa2989
  - name: cp.icr.io/cp/ibm-eventstreams-kafka:12.1.0@sha256:f7403a21e3567a91cba9bdfe18dae81154b6ac5c560178ba3a216d532f5be3d4
  - name: cp.icr.io/cp/ibm-eventstreams-kafka:12.2.2@sha256:e4f02f1a86f3331aad142c11d0c8350f819447e59d30b251a1f1aa96f8d51f58
  - name: cp.icr.io/cp/ibm-eventstreams-kaniko-executor:12.1.0@sha256:aa888b7e11d7565f7562db240b1736c47da23fb77ef1dd9222f6c0fe3fe3600c
  - name: cp.icr.io/cp/ibm-eventstreams-kaniko-executor:12.2.2@sha256:5abc6ceaa206e41881d7d54e44c3a832ab5e14e108b019749f7a01ad9ec9549b
  - name: cp.icr.io/cp/ibm-eventstreams-maven-builder:12.1.0@sha256:f1b1890586e352244a635feb219065706dc60835d5a42befd9b75c627e7e0c92
  - name: cp.icr.io/cp/ibm-eventstreams-maven-builder:12.2.2@sha256:5d6a400341a4455b12ea067ea5b83ca2486f385c3de416fc8dfc4a6c3a54fc26
  - name: cp.icr.io/cp/ibm-eventstreams-metrics-collector:12.1.0@sha256:10032261873051968b89c161bd732b9cd50346928ef1644ee097e8ebec5d12ab
  - name: cp.icr.io/cp/ibm-eventstreams-metrics-collector:12.2.2@sha256:12b770acd0d72a3f80fceb145c741938c157e2208397004c05bc8c222e71a8fb
  - name: cp.icr.io/cp/ibm-eventstreams-rest-producer:12.1.0@sha256:63c8b6b21295bfd5ae6612f4e051c96c2ad57717c1b52c76c2dce23141c5c0a7
  - name: cp.icr.io/cp/ibm-eventstreams-rest-producer:12.2.2@sha256:53ed377c0282d015d3b120501ac8598489db941d6cd8f223490614f1154f63c8
  - name: cp.icr.io/cp/ibm-eventstreams-schema-proxy:12.1.0@sha256:461eb4dbbe56e95f134e0d95a7b0a9d6d8aaebc2a3645d32bdc1f7a1b452cb5f
  - name: cp.icr.io/cp/ibm-eventstreams-schema-proxy:12.2.2@sha256:0ca22162826aa0db84b3a7d64e06da1d74bbe98a13b8ede3ca4ff1023200985c
  - name: cp.icr.io/cp/ibm-eventstreams-session-store:12.1.0@sha256:bea255e97e96f029e67b282f4dbff2230d31906cee26ef6bc9d629d11b56fc5f
  - name: cp.icr.io/cp/ibm-eventstreams-session-store:12.2.2@sha256:c9f07e214e5b5518688201c46c4f319a5bc559c7f6f10acb00c7282a4247ac7e
  - name: cp.icr.io/cp/ibm-eventstreams/action-connectors:3.0.0@sha256:cbe955a55b1652b408c7622699dbf657cf6137dcd1eca97e9bb70ffb424c6695
  - name: cp.icr.io/cp/ibm-eventstreams/connectivity-pack-prehook:3.0.0@sha256:8d4c21d45c8030cff35cc2e65c36567b20805691946ebde5442a8b0d5bb35929
  - name: cp.icr.io/cp/ibm-eventstreams/event-connectors:3.0.0@sha256:2b116da33ce5202035374d1443e4af66e04223f174e033fbaf555df6aa6224aa
  - name: icr.io/cpopen/ibm-eventstreams-catalog:12.2.2@sha256:559772f8fd516aca39cb7392d110d1e2090a7762b0a2dccdef61b57f96978afd
  - name: icr.io/cpopen/ibm-eventstreams-operator-bundle:12.1.0@sha256:ceb7e178de511b6022edde3c86062074fd3ca45a68515b3b787c635023085302
  - name: icr.io/cpopen/ibm-eventstreams-operator-bundle:12.2.2@sha256:322f801aebcc782757b9357ad627ae263ba435cd9237679de6eaa9311b9b9a93
  - name: icr.io/cpopen/ibm-eventstreams-operator-init:12.1.0@sha256:304b3324a2daf3e8588c013d2bb8573116caadaac274e28a663de2fdf44f63a4
  - name: icr.io/cpopen/ibm-eventstreams-operator-init:12.2.2@sha256:705cff3828a114322330fc0392a94098bae0e781e48b3cb761126ca5f8e7df45
  - name: icr.io/cpopen/ibm-eventstreams-operator:12.1.0@sha256:9e543e33371268a319dda2a6cc502a98c46ef645a95c93f36868c96906f58d98
  - name: icr.io/cpopen/ibm-eventstreams-operator:12.2.2@sha256:1062d012b7e3c95044d11ff7c838385b071e41c261958968edf2b6034a112afa
