kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/fdb-apple-foundationdb-sidecar:0.30.5@sha256:fe33a244652a83e7f593755e3bf7e603280a288703dd854ee0e90c2a8a11090e
  - name: cp.icr.io/cp/cpd/fdb-apple-foundationdb:0.30.5@sha256:f5a90883085a2f8f74b43ff1dc2d9dde9bc832f5280e22f7948f438fbe7b569e
  - name: cp.icr.io/cp/cpd/fdb-ibm-backup-agent:0.30.5@sha256:87fdd93f4c12db70507a5d0ce2ed11a3d92dc4c6588f31906ff43e88693ae329
  - name: cp.icr.io/cp/cpd/fdb-ibm-restore-agent:0.30.5@sha256:0ddedc592401cd89d49ac621bf41458b56c74deb2f74871b2f4a9b9f99cd2412
  - name: icr.io/cpopen/fdb-apple-operator-bundle:3.34.10@sha256:5b003a763246c885b4a1f4f8c8a3adfcf139eb872b55f5228a1a3a87a899657c
  - name: icr.io/cpopen/fdb-apple-operator:3.34.10@sha256:f4636bd180340eff8e9f0bacfe95a515300d1ea32751984979b3bf2da4d170df
  - name: icr.io/cpopen/fdb-ibm-operator-bundle:3.34.10@sha256:c5cf92427e73dffde9793ff10469516161c3819e215a1b96c59d08db0c7a8511
  - name: icr.io/cpopen/fdb-ibm-operator:3.34.10@sha256:e554ff3af1f48d5d8ed5be014e517d531c4fb59cf9a3a685c19d4e7aef80874e
  - name: icr.io/cpopen/fdb-operator-catalog:3.34.10@sha256:76a1589c411e998c79022caada599e8cffaccd6fda5ebc54fdc27fc3dbd27492
