kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/opencontent-rabbitmq-3:v3.13-1.3.0@sha256:9836c64aef7a8760f07a54b7a64d9d01cbe9d7fa8372a2ecc2d5e33cc315cefc
  - name: cp.icr.io/cp/opencontent-rabbitmq-config-copy:1.3.0@sha256:52472f1d1f10bb6bc424ffda1eb48d6ce6bf29aa6b5a21bbabf6878fcd64a69d
  - name: icr.io/cpopen/opencontent-rabbitmq-operator-bundle:1.3.0@sha256:88e6d4b8775e8db5efb1f711727a0a570c9ad87da78509cc7f3db59f945b6822
  - name: icr.io/cpopen/opencontent-rabbitmq-operator-catalog:1.3.0@sha256:480b830a4b08d7fee2b29e1571d6ac8cd5ada7999d2048146796d0723905353c
  - name: icr.io/cpopen/opencontent-rabbitmq-operator:1.3.0@sha256:cc64f8ec113746d804527f50b5e2d2c83be4eb2318c3d8d95075f02bca46197b
