kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/cpd/action-connectors:1.7.2-1@sha256:3a3ea4bdddda140e7a957094fc07c3a71de0c015ef27c94e428a575216863295
  - name: cp.icr.io/cp/cpd/datasift-api:5.3.141@sha256:d6b89a9c70bd35a95e4278f4a2c003355cb2fb4b5ff894883c02a3d0358bc13a
  - name: cp.icr.io/cp/cpd/datasift-ui:5.3.111@sha256:e2c243e3417a78fa7c506144f7bc7b221e5e72ea39c2be9486eec970ce3a0141
  - name: cp.icr.io/cp/cpd/wdp-connect-adapter-appconnect-flight:0.4.38@sha256:4c3cf5dd6040213f5244a6a8f6385db065b12cf199b1fdac26c95ee1c89f3f62
  - name: icr.io/cpopen/ibm-cpd-datasift-operator-bundle:v5.3.119@sha256:e04488116de891c09bfef46f25cbd905d790f75d336194d9785d6bea33e14277
  - name: icr.io/cpopen/ibm-cpd-datasift-operator-catalog:v5.3.119@sha256:8a057039eb475164c17c17561f8daafe01e5b145b24dbfd43bbb0b7858b558dc
  - name: icr.io/cpopen/ibm-cpd-datasift-operator:v5.3.119@sha256:94ce8fa11511220afe571fe9feaf701ed665f48ebef42821bb87d15376665b70
